-- v1 -> v2 bridge: drop cross-owner foreign keys (v2 forbids cross-owner FK)
-- Same-owner FKs are intentionally retained.
-- Regenerated from live catalog + corrected owner map.
ALTER TABLE public.bot_heartbeat_logs DROP CONSTRAINT IF EXISTS bot_heartbeat_logs_bot_id_fkey; -- agent.bot_heartbeat_logs -> api.bots
ALTER TABLE public.bot_heartbeat_logs DROP CONSTRAINT IF EXISTS bot_heartbeat_logs_model_id_fkey; -- agent.bot_heartbeat_logs -> model.models
ALTER TABLE public.bot_heartbeat_logs DROP CONSTRAINT IF EXISTS bot_heartbeat_logs_team_id_fkey; -- agent.bot_heartbeat_logs -> iam.teams
ALTER TABLE public.bot_history_message_assets DROP CONSTRAINT IF EXISTS bot_history_message_assets_team_id_fkey; -- agent.bot_history_message_assets -> iam.teams
ALTER TABLE public.bot_history_message_compacts DROP CONSTRAINT IF EXISTS bot_history_message_compacts_bot_id_fkey; -- agent.bot_history_message_compacts -> api.bots
ALTER TABLE public.bot_history_message_compacts DROP CONSTRAINT IF EXISTS bot_history_message_compacts_model_id_fkey; -- agent.bot_history_message_compacts -> model.models
ALTER TABLE public.bot_history_message_compacts DROP CONSTRAINT IF EXISTS bot_history_message_compacts_team_id_fkey; -- agent.bot_history_message_compacts -> iam.teams
ALTER TABLE public.bot_history_messages DROP CONSTRAINT IF EXISTS bot_history_messages_bot_id_fkey; -- agent.bot_history_messages -> api.bots
ALTER TABLE public.bot_history_messages DROP CONSTRAINT IF EXISTS bot_history_messages_event_id_fkey; -- agent.bot_history_messages -> channel.bot_session_events
ALTER TABLE public.bot_history_messages DROP CONSTRAINT IF EXISTS bot_history_messages_model_id_fkey; -- agent.bot_history_messages -> model.models
ALTER TABLE public.bot_history_messages DROP CONSTRAINT IF EXISTS bot_history_messages_sender_account_user_id_fkey; -- agent.bot_history_messages -> iam.team_members
ALTER TABLE public.bot_history_messages DROP CONSTRAINT IF EXISTS bot_history_messages_sender_channel_identity_id_fkey; -- agent.bot_history_messages -> channel.channel_identities
ALTER TABLE public.bot_history_messages DROP CONSTRAINT IF EXISTS bot_history_messages_team_id_fkey; -- agent.bot_history_messages -> iam.teams
ALTER TABLE public.bot_plugin_installations DROP CONSTRAINT IF EXISTS bot_plugin_installations_bot_id_fkey; -- agent.bot_plugin_installations -> api.bots
ALTER TABLE public.bot_plugin_installations DROP CONSTRAINT IF EXISTS bot_plugin_installations_team_id_fkey; -- agent.bot_plugin_installations -> iam.teams
ALTER TABLE public.bot_plugin_resources DROP CONSTRAINT IF EXISTS bot_plugin_resources_team_id_fkey; -- agent.bot_plugin_resources -> iam.teams
ALTER TABLE public.bot_sessions DROP CONSTRAINT IF EXISTS bot_sessions_bot_id_fkey; -- agent.bot_sessions -> api.bots
ALTER TABLE public.bot_sessions DROP CONSTRAINT IF EXISTS bot_sessions_created_by_user_id_fkey; -- agent.bot_sessions -> iam.team_members
ALTER TABLE public.bot_sessions DROP CONSTRAINT IF EXISTS bot_sessions_route_id_fkey; -- agent.bot_sessions -> channel.bot_channel_routes
ALTER TABLE public.bot_sessions DROP CONSTRAINT IF EXISTS bot_sessions_team_id_fkey; -- agent.bot_sessions -> iam.teams
ALTER TABLE public.mcp_connections DROP CONSTRAINT IF EXISTS mcp_connections_bot_id_fkey; -- agent.mcp_connections -> api.bots
ALTER TABLE public.mcp_connections DROP CONSTRAINT IF EXISTS mcp_connections_team_id_fkey; -- agent.mcp_connections -> iam.teams
ALTER TABLE public.mcp_oauth_tokens DROP CONSTRAINT IF EXISTS mcp_oauth_tokens_team_id_fkey; -- agent.mcp_oauth_tokens -> iam.teams
ALTER TABLE public.schedule DROP CONSTRAINT IF EXISTS schedule_bot_id_fkey; -- agent.schedule -> api.bots
ALTER TABLE public.schedule DROP CONSTRAINT IF EXISTS schedule_team_id_fkey; -- agent.schedule -> iam.teams
ALTER TABLE public.schedule_logs DROP CONSTRAINT IF EXISTS schedule_logs_bot_id_fkey; -- agent.schedule_logs -> api.bots
ALTER TABLE public.schedule_logs DROP CONSTRAINT IF EXISTS schedule_logs_model_id_fkey; -- agent.schedule_logs -> model.models
ALTER TABLE public.schedule_logs DROP CONSTRAINT IF EXISTS schedule_logs_team_id_fkey; -- agent.schedule_logs -> iam.teams
ALTER TABLE public.subagent_configs DROP CONSTRAINT IF EXISTS subagent_configs_model_uuid_fkey; -- agent.subagent_configs -> model.models
ALTER TABLE public.subagent_configs DROP CONSTRAINT IF EXISTS subagent_configs_team_id_fkey; -- agent.subagent_configs -> iam.teams
ALTER TABLE public.tool_approval_requests DROP CONSTRAINT IF EXISTS tool_approval_requests_bot_id_fkey; -- agent.tool_approval_requests -> api.bots
ALTER TABLE public.tool_approval_requests DROP CONSTRAINT IF EXISTS tool_approval_requests_channel_identity_id_fkey; -- agent.tool_approval_requests -> channel.channel_identities
ALTER TABLE public.tool_approval_requests DROP CONSTRAINT IF EXISTS tool_approval_requests_decided_by_channel_identity_id_fkey; -- agent.tool_approval_requests -> channel.channel_identities
ALTER TABLE public.tool_approval_requests DROP CONSTRAINT IF EXISTS tool_approval_requests_requested_by_channel_identity_id_fkey; -- agent.tool_approval_requests -> channel.channel_identities
ALTER TABLE public.tool_approval_requests DROP CONSTRAINT IF EXISTS tool_approval_requests_route_id_fkey; -- agent.tool_approval_requests -> channel.bot_channel_routes
ALTER TABLE public.tool_approval_requests DROP CONSTRAINT IF EXISTS tool_approval_requests_team_id_fkey; -- agent.tool_approval_requests -> iam.teams
ALTER TABLE public.user_input_requests DROP CONSTRAINT IF EXISTS user_input_requests_bot_id_fkey; -- agent.user_input_requests -> api.bots
ALTER TABLE public.user_input_requests DROP CONSTRAINT IF EXISTS user_input_requests_channel_identity_id_fkey; -- agent.user_input_requests -> channel.channel_identities
ALTER TABLE public.user_input_requests DROP CONSTRAINT IF EXISTS user_input_requests_requested_by_channel_identity_id_fkey; -- agent.user_input_requests -> channel.channel_identities
ALTER TABLE public.user_input_requests DROP CONSTRAINT IF EXISTS user_input_requests_responded_by_channel_identity_id_fkey; -- agent.user_input_requests -> channel.channel_identities
ALTER TABLE public.user_input_requests DROP CONSTRAINT IF EXISTS user_input_requests_route_id_fkey; -- agent.user_input_requests -> channel.bot_channel_routes
ALTER TABLE public.user_input_requests DROP CONSTRAINT IF EXISTS user_input_requests_team_id_fkey; -- agent.user_input_requests -> iam.teams
ALTER TABLE public.bot_acl_rules DROP CONSTRAINT IF EXISTS bot_acl_rules_channel_identity_id_fkey; -- api.bot_acl_rules -> channel.channel_identities
ALTER TABLE public.bot_acl_rules DROP CONSTRAINT IF EXISTS bot_acl_rules_created_by_user_id_fkey; -- api.bot_acl_rules -> iam.team_members
ALTER TABLE public.bot_acl_rules DROP CONSTRAINT IF EXISTS bot_acl_rules_team_id_fkey; -- api.bot_acl_rules -> iam.teams
ALTER TABLE public.bot_channel_admins DROP CONSTRAINT IF EXISTS bot_channel_admins_channel_identity_id_fkey; -- api.bot_channel_admins -> channel.channel_identities
ALTER TABLE public.bot_channel_admins DROP CONSTRAINT IF EXISTS bot_channel_admins_created_by_user_id_fkey; -- api.bot_channel_admins -> iam.team_members
ALTER TABLE public.bot_channel_admins DROP CONSTRAINT IF EXISTS bot_channel_admins_team_id_fkey; -- api.bot_channel_admins -> iam.teams
ALTER TABLE public.bot_user_grants DROP CONSTRAINT IF EXISTS bot_user_grants_created_by_user_id_fkey; -- api.bot_user_grants -> iam.team_members
ALTER TABLE public.bot_user_grants DROP CONSTRAINT IF EXISTS bot_user_grants_team_id_fkey; -- api.bot_user_grants -> iam.teams
ALTER TABLE public.bot_user_grants DROP CONSTRAINT IF EXISTS bot_user_grants_user_id_fkey; -- api.bot_user_grants -> iam.team_members
ALTER TABLE public.bots DROP CONSTRAINT IF EXISTS bots_chat_model_id_fkey; -- api.bots -> model.models
ALTER TABLE public.bots DROP CONSTRAINT IF EXISTS bots_compaction_model_id_fkey; -- api.bots -> model.models
ALTER TABLE public.bots DROP CONSTRAINT IF EXISTS bots_discuss_probe_model_id_fkey; -- api.bots -> model.models
ALTER TABLE public.bots DROP CONSTRAINT IF EXISTS bots_fetch_provider_id_fkey; -- api.bots -> model.fetch_providers
ALTER TABLE public.bots DROP CONSTRAINT IF EXISTS bots_heartbeat_model_id_fkey; -- api.bots -> model.models
ALTER TABLE public.bots DROP CONSTRAINT IF EXISTS bots_image_model_id_fkey; -- api.bots -> model.models
ALTER TABLE public.bots DROP CONSTRAINT IF EXISTS bots_memory_provider_id_fkey; -- api.bots -> memory.memory_providers
ALTER TABLE public.bots DROP CONSTRAINT IF EXISTS bots_owner_user_id_fkey; -- api.bots -> iam.team_members
ALTER TABLE public.bots DROP CONSTRAINT IF EXISTS bots_search_provider_id_fkey; -- api.bots -> model.search_providers
ALTER TABLE public.bots DROP CONSTRAINT IF EXISTS bots_team_id_fkey; -- api.bots -> iam.teams
ALTER TABLE public.bots DROP CONSTRAINT IF EXISTS bots_transcription_model_id_fkey; -- api.bots -> model.models
ALTER TABLE public.bots DROP CONSTRAINT IF EXISTS bots_tts_model_id_fkey; -- api.bots -> model.models
ALTER TABLE public.bots DROP CONSTRAINT IF EXISTS bots_video_model_id_fkey; -- api.bots -> model.models
ALTER TABLE public.channel_link_codes DROP CONSTRAINT IF EXISTS channel_link_codes_consumed_channel_identity_id_fkey; -- api.channel_link_codes -> channel.channel_identities
ALTER TABLE public.channel_link_codes DROP CONSTRAINT IF EXISTS channel_link_codes_team_id_fkey; -- api.channel_link_codes -> iam.teams
ALTER TABLE public.channel_link_codes DROP CONSTRAINT IF EXISTS channel_link_codes_user_id_fkey; -- api.channel_link_codes -> iam.team_members
ALTER TABLE public.user_channel_bindings DROP CONSTRAINT IF EXISTS user_channel_bindings_team_id_fkey; -- api.user_channel_bindings -> iam.teams
ALTER TABLE public.user_channel_bindings DROP CONSTRAINT IF EXISTS user_channel_bindings_user_id_fkey; -- api.user_channel_bindings -> iam.team_members
ALTER TABLE public.user_channel_identity_bindings DROP CONSTRAINT IF EXISTS user_channel_identity_bindings_channel_identity_id_fkey; -- api.user_channel_identity_bindings -> channel.channel_identities
ALTER TABLE public.user_channel_identity_bindings DROP CONSTRAINT IF EXISTS user_channel_identity_bindings_team_id_fkey; -- api.user_channel_identity_bindings -> iam.teams
ALTER TABLE public.user_channel_identity_bindings DROP CONSTRAINT IF EXISTS user_channel_identity_bindings_user_id_fkey; -- api.user_channel_identity_bindings -> iam.team_members
ALTER TABLE public.bot_channel_configs DROP CONSTRAINT IF EXISTS bot_channel_configs_bot_id_fkey; -- channel.bot_channel_configs -> api.bots
ALTER TABLE public.bot_channel_configs DROP CONSTRAINT IF EXISTS bot_channel_configs_team_id_fkey; -- channel.bot_channel_configs -> iam.teams
ALTER TABLE public.bot_channel_routes DROP CONSTRAINT IF EXISTS bot_channel_routes_bot_id_fkey; -- channel.bot_channel_routes -> api.bots
ALTER TABLE public.bot_channel_routes DROP CONSTRAINT IF EXISTS bot_channel_routes_team_id_fkey; -- channel.bot_channel_routes -> iam.teams
ALTER TABLE public.bot_channel_routes DROP CONSTRAINT IF EXISTS fk_bot_channel_routes_active_session; -- channel.bot_channel_routes -> agent.bot_sessions
ALTER TABLE public.bot_email_bindings DROP CONSTRAINT IF EXISTS bot_email_bindings_bot_id_fkey; -- channel.bot_email_bindings -> api.bots
ALTER TABLE public.bot_email_bindings DROP CONSTRAINT IF EXISTS bot_email_bindings_team_id_fkey; -- channel.bot_email_bindings -> iam.teams
ALTER TABLE public.bot_session_discuss_cursors DROP CONSTRAINT IF EXISTS bot_session_discuss_cursors_session_id_fkey; -- channel.bot_session_discuss_cursors -> agent.bot_sessions
ALTER TABLE public.bot_session_discuss_cursors DROP CONSTRAINT IF EXISTS bot_session_discuss_cursors_team_id_fkey; -- channel.bot_session_discuss_cursors -> iam.teams
ALTER TABLE public.bot_session_events DROP CONSTRAINT IF EXISTS bot_session_events_bot_id_fkey; -- channel.bot_session_events -> api.bots
ALTER TABLE public.bot_session_events DROP CONSTRAINT IF EXISTS bot_session_events_session_id_fkey; -- channel.bot_session_events -> agent.bot_sessions
ALTER TABLE public.bot_session_events DROP CONSTRAINT IF EXISTS bot_session_events_team_id_fkey; -- channel.bot_session_events -> iam.teams
ALTER TABLE public.channel_identities DROP CONSTRAINT IF EXISTS channel_identities_team_id_fkey; -- channel.channel_identities -> iam.teams
ALTER TABLE public.email_oauth_tokens DROP CONSTRAINT IF EXISTS email_oauth_tokens_team_id_fkey; -- channel.email_oauth_tokens -> iam.teams
ALTER TABLE public.email_outbox DROP CONSTRAINT IF EXISTS email_outbox_bot_id_fkey; -- channel.email_outbox -> api.bots
ALTER TABLE public.email_outbox DROP CONSTRAINT IF EXISTS email_outbox_team_id_fkey; -- channel.email_outbox -> iam.teams
ALTER TABLE public.email_providers DROP CONSTRAINT IF EXISTS email_providers_team_id_fkey; -- channel.email_providers -> iam.teams
ALTER TABLE public.email_providers DROP CONSTRAINT IF EXISTS email_providers_user_id_fkey; -- channel.email_providers -> iam.team_members
ALTER TABLE public.bot_storage_bindings DROP CONSTRAINT IF EXISTS bot_storage_bindings_bot_id_fkey; -- media.bot_storage_bindings -> api.bots
ALTER TABLE public.bot_storage_bindings DROP CONSTRAINT IF EXISTS bot_storage_bindings_team_id_fkey; -- media.bot_storage_bindings -> iam.teams
ALTER TABLE public.media_assets DROP CONSTRAINT IF EXISTS media_assets_bot_id_fkey; -- media.media_assets -> api.bots
ALTER TABLE public.media_assets DROP CONSTRAINT IF EXISTS media_assets_team_id_fkey; -- media.media_assets -> iam.teams
ALTER TABLE public.storage_providers DROP CONSTRAINT IF EXISTS storage_providers_team_id_fkey; -- media.storage_providers -> iam.teams
ALTER TABLE public.memory_edges DROP CONSTRAINT IF EXISTS memory_edges_bot_id_fkey; -- memory.memory_edges -> api.bots
ALTER TABLE public.memory_edges DROP CONSTRAINT IF EXISTS memory_edges_team_id_fkey; -- memory.memory_edges -> iam.teams
ALTER TABLE public.memory_nodes DROP CONSTRAINT IF EXISTS memory_nodes_bot_id_fkey; -- memory.memory_nodes -> api.bots
ALTER TABLE public.memory_nodes DROP CONSTRAINT IF EXISTS memory_nodes_team_id_fkey; -- memory.memory_nodes -> iam.teams
ALTER TABLE public.memory_providers DROP CONSTRAINT IF EXISTS memory_providers_team_id_fkey; -- memory.memory_providers -> iam.teams
ALTER TABLE public.fetch_providers DROP CONSTRAINT IF EXISTS fetch_providers_team_id_fkey; -- model.fetch_providers -> iam.teams
ALTER TABLE public.model_variants DROP CONSTRAINT IF EXISTS model_variants_team_id_fkey; -- model.model_variants -> iam.teams
ALTER TABLE public.models DROP CONSTRAINT IF EXISTS models_team_id_fkey; -- model.models -> iam.teams
ALTER TABLE public.provider_oauth_tokens DROP CONSTRAINT IF EXISTS provider_oauth_tokens_team_id_fkey; -- model.provider_oauth_tokens -> iam.teams
ALTER TABLE public.providers DROP CONSTRAINT IF EXISTS providers_team_id_fkey; -- model.providers -> iam.teams
ALTER TABLE public.search_providers DROP CONSTRAINT IF EXISTS search_providers_team_id_fkey; -- model.search_providers -> iam.teams
ALTER TABLE public.tts_models DROP CONSTRAINT IF EXISTS tts_models_team_id_fkey; -- model.tts_models -> iam.teams
ALTER TABLE public.tts_providers DROP CONSTRAINT IF EXISTS tts_providers_team_id_fkey; -- model.tts_providers -> iam.teams
ALTER TABLE public.user_provider_oauth_tokens DROP CONSTRAINT IF EXISTS user_provider_oauth_tokens_team_id_fkey; -- model.user_provider_oauth_tokens -> iam.teams
ALTER TABLE public.user_provider_oauth_tokens DROP CONSTRAINT IF EXISTS user_provider_oauth_tokens_user_id_fkey; -- model.user_provider_oauth_tokens -> iam.team_members
ALTER TABLE public.team_members DROP CONSTRAINT IF EXISTS team_members_title_model_id_fkey; -- iam.team_members -> model.models
ALTER TABLE public.bot_remote_runtime_bindings DROP CONSTRAINT IF EXISTS bot_remote_runtime_bindings_bot_id_fkey; -- runtime.bot_remote_runtime_bindings -> api.bots
ALTER TABLE public.bot_remote_runtime_bindings DROP CONSTRAINT IF EXISTS bot_remote_runtime_bindings_team_id_fkey; -- runtime.bot_remote_runtime_bindings -> iam.teams
ALTER TABLE public.bot_workspace_resource_limits DROP CONSTRAINT IF EXISTS bot_workspace_resource_limits_bot_id_fkey; -- runtime.bot_workspace_resource_limits -> api.bots
ALTER TABLE public.bot_workspace_resource_limits DROP CONSTRAINT IF EXISTS bot_workspace_resource_limits_team_id_fkey; -- runtime.bot_workspace_resource_limits -> iam.teams
ALTER TABLE public.container_versions DROP CONSTRAINT IF EXISTS container_versions_team_id_fkey; -- runtime.container_versions -> iam.teams
ALTER TABLE public.containers DROP CONSTRAINT IF EXISTS containers_bot_id_fkey; -- runtime.containers -> api.bots
ALTER TABLE public.containers DROP CONSTRAINT IF EXISTS containers_team_id_fkey; -- runtime.containers -> iam.teams
ALTER TABLE public.lifecycle_events DROP CONSTRAINT IF EXISTS lifecycle_events_team_id_fkey; -- runtime.lifecycle_events -> iam.teams
ALTER TABLE public.snapshots DROP CONSTRAINT IF EXISTS snapshots_team_id_fkey; -- runtime.snapshots -> iam.teams
ALTER TABLE public.tasks DROP CONSTRAINT IF EXISTS tasks_team_id_fkey; -- runtime.tasks -> iam.teams
ALTER TABLE public.user_runtimes DROP CONSTRAINT IF EXISTS user_runtimes_team_id_fkey; -- runtime.user_runtimes -> iam.teams
ALTER TABLE public.user_runtimes DROP CONSTRAINT IF EXISTS user_runtimes_user_id_fkey; -- runtime.user_runtimes -> iam.team_members
