// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_authorizations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAgentAuthorizations = `-- name: CountAgentAuthorizations :one
SELECT count(*) FROM agent_authorizations
WHERE owner_user_id = $1 AND team_id = public.memoh_current_team_id() AND status <> 'claimed' AND expires_at > now()
`

func (q *Queries) CountAgentAuthorizations(ctx context.Context, ownerUserID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAgentAuthorizations, ownerUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgentAuthorization = `-- name: CreateAgentAuthorization :one
INSERT INTO agent_authorizations (owner_user_id, runtime, auth_kind, status, encrypted_payload, encryption_nonce, expires_at, poll_after)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, team_id, owner_user_id, runtime, auth_kind, status, encrypted_payload, encryption_nonce, expires_at, poll_after, claimed_agent_id, created_at
`

type CreateAgentAuthorizationParams struct {
	OwnerUserID      pgtype.UUID        `json:"owner_user_id"`
	Runtime          string             `json:"runtime"`
	AuthKind         string             `json:"auth_kind"`
	Status           string             `json:"status"`
	EncryptedPayload []byte             `json:"encrypted_payload"`
	EncryptionNonce  []byte             `json:"encryption_nonce"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	PollAfter        pgtype.Timestamptz `json:"poll_after"`
}

func (q *Queries) CreateAgentAuthorization(ctx context.Context, arg CreateAgentAuthorizationParams) (AgentAuthorization, error) {
	row := q.db.QueryRow(ctx, createAgentAuthorization,
		arg.OwnerUserID,
		arg.Runtime,
		arg.AuthKind,
		arg.Status,
		arg.EncryptedPayload,
		arg.EncryptionNonce,
		arg.ExpiresAt,
		arg.PollAfter,
	)
	var i AgentAuthorization
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.OwnerUserID,
		&i.Runtime,
		&i.AuthKind,
		&i.Status,
		&i.EncryptedPayload,
		&i.EncryptionNonce,
		&i.ExpiresAt,
		&i.PollAfter,
		&i.ClaimedAgentID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAgentAuthorization = `-- name: DeleteAgentAuthorization :exec
DELETE FROM agent_authorizations
WHERE id = $1 AND owner_user_id = $2 AND team_id = public.memoh_current_team_id()
`

type DeleteAgentAuthorizationParams struct {
	ID          pgtype.UUID `json:"id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

func (q *Queries) DeleteAgentAuthorization(ctx context.Context, arg DeleteAgentAuthorizationParams) error {
	_, err := q.db.Exec(ctx, deleteAgentAuthorization, arg.ID, arg.OwnerUserID)
	return err
}

const getAgentAuthorization = `-- name: GetAgentAuthorization :one
SELECT id, team_id, owner_user_id, runtime, auth_kind, status, encrypted_payload, encryption_nonce, expires_at, poll_after, claimed_agent_id, created_at FROM agent_authorizations
WHERE id = $1 AND owner_user_id = $2 AND team_id = public.memoh_current_team_id()
  AND expires_at > now()
FOR UPDATE
`

type GetAgentAuthorizationParams struct {
	ID          pgtype.UUID `json:"id"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
}

func (q *Queries) GetAgentAuthorization(ctx context.Context, arg GetAgentAuthorizationParams) (AgentAuthorization, error) {
	row := q.db.QueryRow(ctx, getAgentAuthorization, arg.ID, arg.OwnerUserID)
	var i AgentAuthorization
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.OwnerUserID,
		&i.Runtime,
		&i.AuthKind,
		&i.Status,
		&i.EncryptedPayload,
		&i.EncryptionNonce,
		&i.ExpiresAt,
		&i.PollAfter,
		&i.ClaimedAgentID,
		&i.CreatedAt,
	)
	return i, err
}

const lockAgentAuthorizationOwner = `-- name: LockAgentAuthorizationOwner :exec
SELECT pg_advisory_xact_lock(hashtextextended(public.memoh_current_team_id()::text || $1::text, 0))
`

func (q *Queries) LockAgentAuthorizationOwner(ctx context.Context, ownerUserID string) error {
	_, err := q.db.Exec(ctx, lockAgentAuthorizationOwner, ownerUserID)
	return err
}

const pruneAgentAuthorizations = `-- name: PruneAgentAuthorizations :exec
DELETE FROM agent_authorizations WHERE team_id = public.memoh_current_team_id() AND expires_at <= now()
`

func (q *Queries) PruneAgentAuthorizations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneAgentAuthorizations)
	return err
}

const updateAgentAuthorization = `-- name: UpdateAgentAuthorization :one
UPDATE agent_authorizations SET status = $2, encrypted_payload = $3, encryption_nonce = $4,
    expires_at = $5, poll_after = $6, claimed_agent_id = $7
WHERE id = $1 AND team_id = public.memoh_current_team_id() RETURNING id, team_id, owner_user_id, runtime, auth_kind, status, encrypted_payload, encryption_nonce, expires_at, poll_after, claimed_agent_id, created_at
`

type UpdateAgentAuthorizationParams struct {
	ID               pgtype.UUID        `json:"id"`
	Status           string             `json:"status"`
	EncryptedPayload []byte             `json:"encrypted_payload"`
	EncryptionNonce  []byte             `json:"encryption_nonce"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	PollAfter        pgtype.Timestamptz `json:"poll_after"`
	ClaimedAgentID   pgtype.UUID        `json:"claimed_agent_id"`
}

func (q *Queries) UpdateAgentAuthorization(ctx context.Context, arg UpdateAgentAuthorizationParams) (AgentAuthorization, error) {
	row := q.db.QueryRow(ctx, updateAgentAuthorization,
		arg.ID,
		arg.Status,
		arg.EncryptedPayload,
		arg.EncryptionNonce,
		arg.ExpiresAt,
		arg.PollAfter,
		arg.ClaimedAgentID,
	)
	var i AgentAuthorization
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.OwnerUserID,
		&i.Runtime,
		&i.AuthKind,
		&i.Status,
		&i.EncryptedPayload,
		&i.EncryptionNonce,
		&i.ExpiresAt,
		&i.PollAfter,
		&i.ClaimedAgentID,
		&i.CreatedAt,
	)
	return i, err
}
