// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_session_state.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAgentSessionPublicationsBySession = `-- name: DeleteAgentSessionPublicationsBySession :execrows
DELETE FROM agent_session_publications publication
WHERE publication.team_id = public.memoh_current_team_id()
  AND publication.session_id = $1
`

func (q *Queries) DeleteAgentSessionPublicationsBySession(ctx context.Context, sessionID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAgentSessionPublicationsBySession, sessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRuntimeDecisionProjectionsByRun = `-- name: DeleteRuntimeDecisionProjectionsByRun :execrows
DELETE FROM bot_history_messages message
WHERE message.team_id = public.memoh_current_team_id()
  AND message.bot_id = $1
  AND message.session_id = $2
  AND message.run_id = $3
  AND message.role = 'assistant'
  AND message.runtime_type <> 'model'
  AND message.metadata @> '{"agent_decision_projection": true}'::jsonb
`

type DeleteRuntimeDecisionProjectionsByRunParams struct {
	BotID     pgtype.UUID `json:"bot_id"`
	SessionID pgtype.UUID `json:"session_id"`
	RunID     pgtype.UUID `json:"run_id"`
}

// Decision cards are temporary stream projections. Delete by their stable
// run marker as well as by returned IDs so an insert whose COMMIT ack was lost
// cannot survive the final canonical round as a duplicate assistant message.
func (q *Queries) DeleteRuntimeDecisionProjectionsByRun(ctx context.Context, arg DeleteRuntimeDecisionProjectionsByRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRuntimeDecisionProjectionsByRun, arg.BotID, arg.SessionID, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAgentSessionPublicationHead = `-- name: GetAgentSessionPublicationHead :one
SELECT publication.run_id
FROM agent_session_publications publication
JOIN bot_sessions session
  ON session.team_id = publication.team_id
 AND session.id = publication.session_id
WHERE publication.team_id = public.memoh_current_team_id()
  AND publication.session_id = $1
  AND session.bot_id = $2
  AND session.runtime_type <> 'model'
  AND session.deleted_at IS NULL
`

type GetAgentSessionPublicationHeadParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	BotID     pgtype.UUID `json:"bot_id"`
}

// Return the last committed round. Warm runtimes check it before every native
// prompt so another server instance (or a history clear) cannot leave two
// process-local conversations advancing from different canonical heads.
func (q *Queries) GetAgentSessionPublicationHead(ctx context.Context, arg GetAgentSessionPublicationHeadParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getAgentSessionPublicationHead, arg.SessionID, arg.BotID)
	var run_id pgtype.UUID
	err := row.Scan(&run_id)
	return run_id, err
}

const getRuntimeConfigEpoch = `-- name: GetRuntimeConfigEpoch :one
SELECT
  bot.runtime_config_epoch AS bot_runtime_config_epoch,
  COALESCE(session.runtime_config_epoch, 0)::bigint AS session_runtime_config_epoch
FROM bots bot
LEFT JOIN bot_sessions session
  ON session.team_id = bot.team_id
 AND session.bot_id = bot.id
 AND session.id = $1
 AND session.deleted_at IS NULL
WHERE bot.team_id = public.memoh_current_team_id()
  AND bot.id = $2
  AND (
    $1::uuid IS NULL
    OR session.id IS NOT NULL
  )
`

type GetRuntimeConfigEpochParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	BotID     pgtype.UUID `json:"bot_id"`
}

type GetRuntimeConfigEpochRow struct {
	BotRuntimeConfigEpoch     int64 `json:"bot_runtime_config_epoch"`
	SessionRuntimeConfigEpoch int64 `json:"session_runtime_config_epoch"`
}

// A handle records this pair before its process starts. Bound resolution and
// every prompt compare it again, so a reset on another server invalidates
// idle and unbound processes that have no active session_run to route to.
func (q *Queries) GetRuntimeConfigEpoch(ctx context.Context, arg GetRuntimeConfigEpochParams) (GetRuntimeConfigEpochRow, error) {
	row := q.db.QueryRow(ctx, getRuntimeConfigEpoch, arg.SessionID, arg.BotID)
	var i GetRuntimeConfigEpochRow
	err := row.Scan(&i.BotRuntimeConfigEpoch, &i.SessionRuntimeConfigEpoch)
	return i, err
}

const getRuntimeLeadingUserMessageID = `-- name: GetRuntimeLeadingUserMessageID :one
SELECT message.id
FROM bot_history_messages message
JOIN session_runs run
  ON run.team_id = message.team_id
 AND run.run_id = message.run_id
 AND run.bot_id = message.bot_id
 AND run.session_id = message.session_id
 AND run.turn_id = message.turn_id
 AND run.turn_position = message.turn_position
WHERE message.team_id = public.memoh_current_team_id()
  AND message.bot_id = $1
  AND message.session_id = $2
  AND message.run_id = $3
  AND message.turn_id = $4
  AND message.role = 'user'
  AND message.runtime_type <> 'model'
  AND message.turn_message_seq = 1
ORDER BY message.created_at DESC, message.id DESC
LIMIT 1
`

type GetRuntimeLeadingUserMessageIDParams struct {
	BotID     pgtype.UUID `json:"bot_id"`
	SessionID pgtype.UUID `json:"session_id"`
	RunID     pgtype.UUID `json:"run_id"`
	TurnID    pgtype.UUID `json:"turn_id"`
}

// Reconcile the single eager user row after an uncertain COMMIT. The caller
// first waits on the session row in a separate statement, so no row here is a
// definitive rollback rather than an observation racing the old backend.
func (q *Queries) GetRuntimeLeadingUserMessageID(ctx context.Context, arg GetRuntimeLeadingUserMessageIDParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getRuntimeLeadingUserMessageID,
		arg.BotID,
		arg.SessionID,
		arg.RunID,
		arg.TurnID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getRuntimeRoundOutcome = `-- name: GetRuntimeRoundOutcome :one
SELECT COALESCE(message.metadata->>'agent_turn_outcome', '')::text AS outcome
FROM bot_history_messages message
JOIN session_runs run
  ON run.team_id = message.team_id
 AND run.run_id = message.run_id
 AND run.bot_id = message.bot_id
 AND run.session_id = message.session_id
 AND run.turn_id = message.turn_id
 AND run.turn_position = message.turn_position
WHERE message.team_id = public.memoh_current_team_id()
  AND message.bot_id = $1
  AND message.session_id = $2
  AND message.run_id = $3
  AND message.role = 'assistant'
  AND message.runtime_type <> 'model'
  AND message.turn_visible = true
  AND message.metadata->>'agent_turn_outcome' IN ('succeeded', 'failed', 'aborted')
ORDER BY message.turn_message_seq DESC, message.created_at DESC, message.id DESC
LIMIT 1
`

type GetRuntimeRoundOutcomeParams struct {
	BotID     pgtype.UUID `json:"bot_id"`
	SessionID pgtype.UUID `json:"session_id"`
	RunID     pgtype.UUID `json:"run_id"`
}

// Read the terminal runtime outcome for commit-unknown reconciliation after
// the caller has first waited on the session write lock.
func (q *Queries) GetRuntimeRoundOutcome(ctx context.Context, arg GetRuntimeRoundOutcomeParams) (string, error) {
	row := q.db.QueryRow(ctx, getRuntimeRoundOutcome, arg.BotID, arg.SessionID, arg.RunID)
	var outcome string
	err := row.Scan(&outcome)
	return outcome, err
}

const upsertAgentSessionPublication = `-- name: UpsertAgentSessionPublication :execrows
WITH target_session AS MATERIALIZED (
  SELECT session.team_id, session.id, session.runtime_fencing_token
  FROM bot_sessions session
  WHERE session.team_id = public.memoh_current_team_id()
    AND session.id = $1
    AND session.bot_id = $2
    AND session.runtime_type <> 'model'
    AND session.deleted_at IS NULL
),
target_run AS MATERIALIZED (
  SELECT target.team_id, target.id AS session_id, run.run_id
  FROM target_session target
  JOIN session_runs run
    ON run.team_id = target.team_id
   AND run.session_id = target.id
   AND run.bot_id = $2
   AND run.run_id = $3
   AND run.fencing_token = target.runtime_fencing_token
)
INSERT INTO agent_session_publications (team_id, session_id, run_id)
SELECT target.team_id, target.session_id, target.run_id
FROM target_run target
ON CONFLICT (team_id, session_id) DO UPDATE SET
  run_id = EXCLUDED.run_id,
  updated_at = now()
`

type UpsertAgentSessionPublicationParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	BotID     pgtype.UUID `json:"bot_id"`
	RunID     pgtype.UUID `json:"run_id"`
}

// Written in the same transaction as the round's canonical messages. The run
// join proves the run belongs to this tenant+session and still owns the
// session's current fencing generation, so a stale runtime cannot move the
// head.
func (q *Queries) UpsertAgentSessionPublication(ctx context.Context, arg UpsertAgentSessionPublicationParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertAgentSessionPublication, arg.SessionID, arg.BotID, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
