// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: context_fragment_texts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listContextFragmentPreviews = `-- name: ListContextFragmentPreviews :many
SELECT content_hash, kind, label, left(text, $1::int) AS preview, text_bytes, truncated
FROM context_fragment_texts
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $2
  AND content_hash = ANY($3::text[])
`

type ListContextFragmentPreviewsParams struct {
	PreviewChars  int32       `json:"preview_chars"`
	BotID         pgtype.UUID `json:"bot_id"`
	ContentHashes []string    `json:"content_hashes"`
}

type ListContextFragmentPreviewsRow struct {
	ContentHash string `json:"content_hash"`
	Kind        string `json:"kind"`
	Label       string `json:"label"`
	Preview     string `json:"preview"`
	TextBytes   int32  `json:"text_bytes"`
	Truncated   bool   `json:"truncated"`
}

func (q *Queries) ListContextFragmentPreviews(ctx context.Context, arg ListContextFragmentPreviewsParams) ([]ListContextFragmentPreviewsRow, error) {
	rows, err := q.db.Query(ctx, listContextFragmentPreviews, arg.PreviewChars, arg.BotID, arg.ContentHashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContextFragmentPreviewsRow
	for rows.Next() {
		var i ListContextFragmentPreviewsRow
		if err := rows.Scan(
			&i.ContentHash,
			&i.Kind,
			&i.Label,
			&i.Preview,
			&i.TextBytes,
			&i.Truncated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContextFragmentTexts = `-- name: ListContextFragmentTexts :many
SELECT content_hash, kind, label, text, text_bytes, truncated
FROM context_fragment_texts
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND content_hash = ANY($2::text[])
`

type ListContextFragmentTextsParams struct {
	BotID         pgtype.UUID `json:"bot_id"`
	ContentHashes []string    `json:"content_hashes"`
}

type ListContextFragmentTextsRow struct {
	ContentHash string `json:"content_hash"`
	Kind        string `json:"kind"`
	Label       string `json:"label"`
	Text        string `json:"text"`
	TextBytes   int32  `json:"text_bytes"`
	Truncated   bool   `json:"truncated"`
}

func (q *Queries) ListContextFragmentTexts(ctx context.Context, arg ListContextFragmentTextsParams) ([]ListContextFragmentTextsRow, error) {
	rows, err := q.db.Query(ctx, listContextFragmentTexts, arg.BotID, arg.ContentHashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContextFragmentTextsRow
	for rows.Next() {
		var i ListContextFragmentTextsRow
		if err := rows.Scan(
			&i.ContentHash,
			&i.Kind,
			&i.Label,
			&i.Text,
			&i.TextBytes,
			&i.Truncated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertContextFragmentTexts = `-- name: UpsertContextFragmentTexts :exec
INSERT INTO context_fragment_texts (bot_id, content_hash, kind, label, text, text_bytes, truncated)
SELECT
  $1::uuid,
  unnest($2::text[]),
  unnest($3::text[]),
  unnest($4::text[]),
  unnest($5::text[]),
  unnest($6::int[]),
  unnest($7::boolean[])
ON CONFLICT (team_id, bot_id, content_hash) DO NOTHING
`

type UpsertContextFragmentTextsParams struct {
	BotID         pgtype.UUID `json:"bot_id"`
	ContentHashes []string    `json:"content_hashes"`
	Kinds         []string    `json:"kinds"`
	Labels        []string    `json:"labels"`
	Texts         []string    `json:"texts"`
	TextBytes     []int32     `json:"text_bytes"`
	Truncated     []bool      `json:"truncated"`
}

func (q *Queries) UpsertContextFragmentTexts(ctx context.Context, arg UpsertContextFragmentTextsParams) error {
	_, err := q.db.Exec(ctx, upsertContextFragmentTexts,
		arg.BotID,
		arg.ContentHashes,
		arg.Kinds,
		arg.Labels,
		arg.Texts,
		arg.TextBytes,
		arg.Truncated,
	)
	return err
}
