// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dependency_plans.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDependencyGraph = `-- name: ClaimDependencyGraph :one
INSERT INTO bot_dependency_graphs (bot_id, owner, lease_until)
SELECT $1, $2, now() + interval '60 seconds'
WHERE NOT EXISTS (
    SELECT 1 FROM bot_dependency_installations
    WHERE team_id = public.memoh_current_team_id() AND bot_id = $1
      AND status IN ('installing', 'updating', 'removing')
)
ON CONFLICT (team_id, bot_id) DO UPDATE
SET owner = EXCLUDED.owner, lease_until = EXCLUDED.lease_until
WHERE bot_dependency_graphs.owner = '' OR bot_dependency_graphs.lease_until < now()
RETURNING graph
`

type ClaimDependencyGraphParams struct {
	BotID pgtype.UUID `json:"bot_id"`
	Owner string      `json:"owner"`
}

func (q *Queries) ClaimDependencyGraph(ctx context.Context, arg ClaimDependencyGraphParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, claimDependencyGraph, arg.BotID, arg.Owner)
	var graph []byte
	err := row.Scan(&graph)
	return graph, err
}

const ensureDependencyGraph = `-- name: EnsureDependencyGraph :exec
INSERT INTO bot_dependency_graphs (bot_id) VALUES ($1)
ON CONFLICT (team_id, bot_id) DO NOTHING
`

func (q *Queries) EnsureDependencyGraph(ctx context.Context, botID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, ensureDependencyGraph, botID)
	return err
}

const getDependencyGraph = `-- name: GetDependencyGraph :one
SELECT graph FROM bot_dependency_graphs
WHERE team_id = public.memoh_current_team_id() AND bot_id = $1
`

func (q *Queries) GetDependencyGraph(ctx context.Context, botID pgtype.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getDependencyGraph, botID)
	var graph []byte
	err := row.Scan(&graph)
	return graph, err
}

const getDependencyPlan = `-- name: GetDependencyPlan :one
SELECT plan FROM bot_dependency_plans
WHERE team_id = public.memoh_current_team_id() AND bot_id = $1 AND id = $2
`

type GetDependencyPlanParams struct {
	BotID pgtype.UUID `json:"bot_id"`
	ID    string      `json:"id"`
}

func (q *Queries) GetDependencyPlan(ctx context.Context, arg GetDependencyPlanParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getDependencyPlan, arg.BotID, arg.ID)
	var plan []byte
	err := row.Scan(&plan)
	return plan, err
}

const listDependencyAppUsers = `-- name: ListDependencyAppUsers :many
SELECT app.id::text AS installation_id, app.app_id
FROM bot_app_dependency_refs AS ref
JOIN bot_app_installations AS app ON app.id = ref.installation_id
WHERE app.team_id = public.memoh_current_team_id() AND app.bot_id = $1 AND ref.dependency_id = $2
`

type ListDependencyAppUsersParams struct {
	BotID        pgtype.UUID `json:"bot_id"`
	DependencyID string      `json:"dependency_id"`
}

type ListDependencyAppUsersRow struct {
	InstallationID string `json:"installation_id"`
	AppID          string `json:"app_id"`
}

func (q *Queries) ListDependencyAppUsers(ctx context.Context, arg ListDependencyAppUsersParams) ([]ListDependencyAppUsersRow, error) {
	rows, err := q.db.Query(ctx, listDependencyAppUsers, arg.BotID, arg.DependencyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDependencyAppUsersRow
	for rows.Next() {
		var i ListDependencyAppUsersRow
		if err := rows.Scan(&i.InstallationID, &i.AppID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDependencyGraph = `-- name: LockDependencyGraph :one
SELECT owner FROM bot_dependency_graphs
WHERE team_id = public.memoh_current_team_id() AND bot_id = $1
FOR UPDATE
`

func (q *Queries) LockDependencyGraph(ctx context.Context, botID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, lockDependencyGraph, botID)
	var owner string
	err := row.Scan(&owner)
	return owner, err
}

const releaseDependencyGraph = `-- name: ReleaseDependencyGraph :exec
UPDATE bot_dependency_graphs SET owner = '', lease_until = now()
WHERE team_id = public.memoh_current_team_id() AND bot_id = $1 AND owner = $2
`

type ReleaseDependencyGraphParams struct {
	BotID pgtype.UUID `json:"bot_id"`
	Owner string      `json:"owner"`
}

func (q *Queries) ReleaseDependencyGraph(ctx context.Context, arg ReleaseDependencyGraphParams) error {
	_, err := q.db.Exec(ctx, releaseDependencyGraph, arg.BotID, arg.Owner)
	return err
}

const renewDependencyGraph = `-- name: RenewDependencyGraph :execrows
UPDATE bot_dependency_graphs SET lease_until = now() + interval '60 seconds'
WHERE team_id = public.memoh_current_team_id() AND bot_id = $1 AND owner = $2 AND lease_until > now()
`

type RenewDependencyGraphParams struct {
	BotID pgtype.UUID `json:"bot_id"`
	Owner string      `json:"owner"`
}

func (q *Queries) RenewDependencyGraph(ctx context.Context, arg RenewDependencyGraphParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewDependencyGraph, arg.BotID, arg.Owner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveDependencyPlan = `-- name: SaveDependencyPlan :exec
INSERT INTO bot_dependency_plans (bot_id, id, plan) VALUES ($1, $2, $3)
ON CONFLICT (team_id, bot_id, id) DO NOTHING
`

type SaveDependencyPlanParams struct {
	BotID pgtype.UUID `json:"bot_id"`
	ID    string      `json:"id"`
	Plan  []byte      `json:"plan"`
}

func (q *Queries) SaveDependencyPlan(ctx context.Context, arg SaveDependencyPlanParams) error {
	_, err := q.db.Exec(ctx, saveDependencyPlan, arg.BotID, arg.ID, arg.Plan)
	return err
}

const writeDependencyGraph = `-- name: WriteDependencyGraph :execrows
UPDATE bot_dependency_graphs SET graph = $3
WHERE team_id = public.memoh_current_team_id() AND bot_id = $1 AND owner = $2 AND lease_until > now()
`

type WriteDependencyGraphParams struct {
	BotID pgtype.UUID `json:"bot_id"`
	Owner string      `json:"owner"`
	Graph []byte      `json:"graph"`
}

func (q *Queries) WriteDependencyGraph(ctx context.Context, arg WriteDependencyGraphParams) (int64, error) {
	result, err := q.db.Exec(ctx, writeDependencyGraph, arg.BotID, arg.Owner, arg.Graph)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
