// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memory_providers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMemoryProvidersByDefault = `-- name: CountMemoryProvidersByDefault :one
SELECT COUNT(*) FROM memory_providers WHERE team_id = public.memoh_current_team_id() AND is_default = true
`

func (q *Queries) CountMemoryProvidersByDefault(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMemoryProvidersByDefault)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMemoryProvider = `-- name: CreateMemoryProvider :one
INSERT INTO memory_providers (name, provider, config, is_default)
VALUES ($1, $2, $3, $4)
RETURNING id, name, provider, config, is_default, created_at, updated_at, team_id
`

type CreateMemoryProviderParams struct {
	Name      string `json:"name"`
	Provider  string `json:"provider"`
	Config    []byte `json:"config"`
	IsDefault bool   `json:"is_default"`
}

func (q *Queries) CreateMemoryProvider(ctx context.Context, arg CreateMemoryProviderParams) (MemoryProvider, error) {
	row := q.db.QueryRow(ctx, createMemoryProvider,
		arg.Name,
		arg.Provider,
		arg.Config,
		arg.IsDefault,
	)
	var i MemoryProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Config,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
	)
	return i, err
}

const getBuiltinMemoryProvider = `-- name: GetBuiltinMemoryProvider :one
SELECT id, name, provider, config, is_default, created_at, updated_at, team_id FROM memory_providers
WHERE team_id = public.memoh_current_team_id() AND provider = 'builtin'
ORDER BY created_at ASC, id ASC
LIMIT 1
`

// The team's Built-in Memory configuration row: the earliest builtin row,
// matching the one the memory settings page has always edited.
func (q *Queries) GetBuiltinMemoryProvider(ctx context.Context) (MemoryProvider, error) {
	row := q.db.QueryRow(ctx, getBuiltinMemoryProvider)
	var i MemoryProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Config,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
	)
	return i, err
}

const getMemoryProviderByID = `-- name: GetMemoryProviderByID :one
SELECT id, name, provider, config, is_default, created_at, updated_at, team_id FROM memory_providers WHERE team_id = public.memoh_current_team_id() AND id = $1
`

func (q *Queries) GetMemoryProviderByID(ctx context.Context, id pgtype.UUID) (MemoryProvider, error) {
	row := q.db.QueryRow(ctx, getMemoryProviderByID, id)
	var i MemoryProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Config,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
	)
	return i, err
}

const listMemoryProviders = `-- name: ListMemoryProviders :many
SELECT id, name, provider, config, is_default, created_at, updated_at, team_id FROM memory_providers WHERE team_id = public.memoh_current_team_id() ORDER BY created_at ASC
`

func (q *Queries) ListMemoryProviders(ctx context.Context) ([]MemoryProvider, error) {
	rows, err := q.db.Query(ctx, listMemoryProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemoryProvider
	for rows.Next() {
		var i MemoryProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Provider,
			&i.Config,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemoryProvider = `-- name: UpdateMemoryProvider :one
UPDATE memory_providers
SET name = $2,
    config = $3,
    updated_at = now()
WHERE team_id = public.memoh_current_team_id() AND id = $1
RETURNING id, name, provider, config, is_default, created_at, updated_at, team_id
`

type UpdateMemoryProviderParams struct {
	ID     pgtype.UUID `json:"id"`
	Name   string      `json:"name"`
	Config []byte      `json:"config"`
}

func (q *Queries) UpdateMemoryProvider(ctx context.Context, arg UpdateMemoryProviderParams) (MemoryProvider, error) {
	row := q.db.QueryRow(ctx, updateMemoryProvider, arg.ID, arg.Name, arg.Config)
	var i MemoryProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Config,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
	)
	return i, err
}
