// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: packages.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearPackageConnectorRefConnection = `-- name: ClearPackageConnectorRefConnection :execrows
UPDATE bot_package_connector_refs
SET connection_id = '',
    updated_at = now()
WHERE team_id = public.memoh_current_team_id()
  AND connection_id = $1
`

func (q *Queries) ClearPackageConnectorRefConnection(ctx context.Context, connectionID string) (int64, error) {
	result, err := q.db.Exec(ctx, clearPackageConnectorRefConnection, connectionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteBotPackageInstallation = `-- name: DeleteBotPackageInstallation :one
DELETE FROM bot_package_installations
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND id = $2
RETURNING id, team_id, bot_id, workspace_target_id, registry_id, package_id, revision, version,
          status, reason, available_revision, available_version, last_checked_at, last_error,
          release, installed_at, updated_at
`

type DeleteBotPackageInstallationParams struct {
	BotID pgtype.UUID `json:"bot_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteBotPackageInstallation(ctx context.Context, arg DeleteBotPackageInstallationParams) (BotPackageInstallation, error) {
	row := q.db.QueryRow(ctx, deleteBotPackageInstallation, arg.BotID, arg.ID)
	var i BotPackageInstallation
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BotID,
		&i.WorkspaceTargetID,
		&i.RegistryID,
		&i.PackageID,
		&i.Revision,
		&i.Version,
		&i.Status,
		&i.Reason,
		&i.AvailableRevision,
		&i.AvailableVersion,
		&i.LastCheckedAt,
		&i.LastError,
		&i.Release,
		&i.InstalledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePackageConnectorRef = `-- name: DeletePackageConnectorRef :execrows
DELETE FROM bot_package_connector_refs
WHERE team_id = public.memoh_current_team_id()
  AND installation_id = $1
  AND connector_type = $2
`

type DeletePackageConnectorRefParams struct {
	InstallationID pgtype.UUID `json:"installation_id"`
	ConnectorType  string      `json:"connector_type"`
}

func (q *Queries) DeletePackageConnectorRef(ctx context.Context, arg DeletePackageConnectorRefParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePackageConnectorRef, arg.InstallationID, arg.ConnectorType)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePackageDependencyRef = `-- name: DeletePackageDependencyRef :execrows
DELETE FROM bot_package_dependency_refs
WHERE team_id = public.memoh_current_team_id()
  AND installation_id = $1
  AND dependency_id = $2
`

type DeletePackageDependencyRefParams struct {
	InstallationID pgtype.UUID `json:"installation_id"`
	DependencyID   string      `json:"dependency_id"`
}

func (q *Queries) DeletePackageDependencyRef(ctx context.Context, arg DeletePackageDependencyRefParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePackageDependencyRef, arg.InstallationID, arg.DependencyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBotPackageInstallation = `-- name: GetBotPackageInstallation :one
SELECT id, team_id, bot_id, workspace_target_id, registry_id, package_id, revision, version,
       status, reason, available_revision, available_version, last_checked_at, last_error,
       release, installed_at, updated_at
FROM bot_package_installations
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND workspace_target_id = $2
  AND registry_id = $3
  AND package_id = $4
LIMIT 1
`

type GetBotPackageInstallationParams struct {
	BotID             pgtype.UUID `json:"bot_id"`
	WorkspaceTargetID string      `json:"workspace_target_id"`
	RegistryID        string      `json:"registry_id"`
	PackageID         string      `json:"package_id"`
}

func (q *Queries) GetBotPackageInstallation(ctx context.Context, arg GetBotPackageInstallationParams) (BotPackageInstallation, error) {
	row := q.db.QueryRow(ctx, getBotPackageInstallation,
		arg.BotID,
		arg.WorkspaceTargetID,
		arg.RegistryID,
		arg.PackageID,
	)
	var i BotPackageInstallation
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BotID,
		&i.WorkspaceTargetID,
		&i.RegistryID,
		&i.PackageID,
		&i.Revision,
		&i.Version,
		&i.Status,
		&i.Reason,
		&i.AvailableRevision,
		&i.AvailableVersion,
		&i.LastCheckedAt,
		&i.LastError,
		&i.Release,
		&i.InstalledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBotPackageInstallationByID = `-- name: GetBotPackageInstallationByID :one
SELECT id, team_id, bot_id, workspace_target_id, registry_id, package_id, revision, version,
       status, reason, available_revision, available_version, last_checked_at, last_error,
       release, installed_at, updated_at
FROM bot_package_installations
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND id = $2
LIMIT 1
`

type GetBotPackageInstallationByIDParams struct {
	BotID pgtype.UUID `json:"bot_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) GetBotPackageInstallationByID(ctx context.Context, arg GetBotPackageInstallationByIDParams) (BotPackageInstallation, error) {
	row := q.db.QueryRow(ctx, getBotPackageInstallationByID, arg.BotID, arg.ID)
	var i BotPackageInstallation
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BotID,
		&i.WorkspaceTargetID,
		&i.RegistryID,
		&i.PackageID,
		&i.Revision,
		&i.Version,
		&i.Status,
		&i.Reason,
		&i.AvailableRevision,
		&i.AvailableVersion,
		&i.LastCheckedAt,
		&i.LastError,
		&i.Release,
		&i.InstalledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBotPackageInstallations = `-- name: ListBotPackageInstallations :many
SELECT id, team_id, bot_id, workspace_target_id, registry_id, package_id, revision, version,
       status, reason, available_revision, available_version, last_checked_at, last_error,
       release, installed_at, updated_at
FROM bot_package_installations
WHERE team_id = public.memoh_current_team_id() AND bot_id = $1
ORDER BY registry_id, package_id, workspace_target_id
`

func (q *Queries) ListBotPackageInstallations(ctx context.Context, botID pgtype.UUID) ([]BotPackageInstallation, error) {
	rows, err := q.db.Query(ctx, listBotPackageInstallations, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotPackageInstallation
	for rows.Next() {
		var i BotPackageInstallation
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.BotID,
			&i.WorkspaceTargetID,
			&i.RegistryID,
			&i.PackageID,
			&i.Revision,
			&i.Version,
			&i.Status,
			&i.Reason,
			&i.AvailableRevision,
			&i.AvailableVersion,
			&i.LastCheckedAt,
			&i.LastError,
			&i.Release,
			&i.InstalledAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBotPackageInstallationsForTarget = `-- name: ListBotPackageInstallationsForTarget :many
SELECT id, team_id, bot_id, workspace_target_id, registry_id, package_id, revision, version,
       status, reason, available_revision, available_version, last_checked_at, last_error,
       release, installed_at, updated_at
FROM bot_package_installations
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND workspace_target_id = $2
ORDER BY registry_id, package_id
`

type ListBotPackageInstallationsForTargetParams struct {
	BotID             pgtype.UUID `json:"bot_id"`
	WorkspaceTargetID string      `json:"workspace_target_id"`
}

func (q *Queries) ListBotPackageInstallationsForTarget(ctx context.Context, arg ListBotPackageInstallationsForTargetParams) ([]BotPackageInstallation, error) {
	rows, err := q.db.Query(ctx, listBotPackageInstallationsForTarget, arg.BotID, arg.WorkspaceTargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotPackageInstallation
	for rows.Next() {
		var i BotPackageInstallation
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.BotID,
			&i.WorkspaceTargetID,
			&i.RegistryID,
			&i.PackageID,
			&i.Revision,
			&i.Version,
			&i.Status,
			&i.Reason,
			&i.AvailableRevision,
			&i.AvailableVersion,
			&i.LastCheckedAt,
			&i.LastError,
			&i.Release,
			&i.InstalledAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackageConnectorRefs = `-- name: ListPackageConnectorRefs :many
SELECT id, team_id, installation_id, connector_type, connection_id, required, created_at, updated_at
FROM bot_package_connector_refs
WHERE team_id = public.memoh_current_team_id()
  AND installation_id = $1
ORDER BY connector_type
`

func (q *Queries) ListPackageConnectorRefs(ctx context.Context, installationID pgtype.UUID) ([]BotPackageConnectorRef, error) {
	rows, err := q.db.Query(ctx, listPackageConnectorRefs, installationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotPackageConnectorRef
	for rows.Next() {
		var i BotPackageConnectorRef
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.InstallationID,
			&i.ConnectorType,
			&i.ConnectionID,
			&i.Required,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackageConnectorRefsForBot = `-- name: ListPackageConnectorRefsForBot :many
SELECT r.id, r.team_id, r.installation_id, r.connector_type, r.connection_id, r.required,
       r.created_at, r.updated_at, i.registry_id, i.package_id, i.workspace_target_id
FROM bot_package_connector_refs r
JOIN bot_package_installations i
  ON i.team_id = r.team_id AND i.id = r.installation_id
WHERE r.team_id = public.memoh_current_team_id()
  AND i.bot_id = $1
ORDER BY r.connector_type, i.registry_id, i.package_id, i.workspace_target_id
`

type ListPackageConnectorRefsForBotRow struct {
	ID                pgtype.UUID        `json:"id"`
	TeamID            pgtype.UUID        `json:"team_id"`
	InstallationID    pgtype.UUID        `json:"installation_id"`
	ConnectorType     string             `json:"connector_type"`
	ConnectionID      string             `json:"connection_id"`
	Required          bool               `json:"required"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	RegistryID        string             `json:"registry_id"`
	PackageID         string             `json:"package_id"`
	WorkspaceTargetID string             `json:"workspace_target_id"`
}

func (q *Queries) ListPackageConnectorRefsForBot(ctx context.Context, botID pgtype.UUID) ([]ListPackageConnectorRefsForBotRow, error) {
	rows, err := q.db.Query(ctx, listPackageConnectorRefsForBot, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPackageConnectorRefsForBotRow
	for rows.Next() {
		var i ListPackageConnectorRefsForBotRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.InstallationID,
			&i.ConnectorType,
			&i.ConnectionID,
			&i.Required,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RegistryID,
			&i.PackageID,
			&i.WorkspaceTargetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackageDependencyRefs = `-- name: ListPackageDependencyRefs :many
SELECT id, team_id, installation_id, dependency_id, created_at
FROM bot_package_dependency_refs
WHERE team_id = public.memoh_current_team_id()
  AND installation_id = $1
ORDER BY dependency_id
`

func (q *Queries) ListPackageDependencyRefs(ctx context.Context, installationID pgtype.UUID) ([]BotPackageDependencyRef, error) {
	rows, err := q.db.Query(ctx, listPackageDependencyRefs, installationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotPackageDependencyRef
	for rows.Next() {
		var i BotPackageDependencyRef
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.InstallationID,
			&i.DependencyID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackageDependencyRefsForTarget = `-- name: ListPackageDependencyRefsForTarget :many
SELECT r.id, r.team_id, r.installation_id, r.dependency_id, r.created_at,
       i.registry_id, i.package_id
FROM bot_package_dependency_refs r
JOIN bot_package_installations i
  ON i.team_id = r.team_id AND i.id = r.installation_id
WHERE r.team_id = public.memoh_current_team_id()
  AND i.bot_id = $1
  AND i.workspace_target_id = $2
ORDER BY r.dependency_id, i.registry_id, i.package_id
`

type ListPackageDependencyRefsForTargetParams struct {
	BotID             pgtype.UUID `json:"bot_id"`
	WorkspaceTargetID string      `json:"workspace_target_id"`
}

type ListPackageDependencyRefsForTargetRow struct {
	ID             pgtype.UUID        `json:"id"`
	TeamID         pgtype.UUID        `json:"team_id"`
	InstallationID pgtype.UUID        `json:"installation_id"`
	DependencyID   string             `json:"dependency_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	RegistryID     string             `json:"registry_id"`
	PackageID      string             `json:"package_id"`
}

func (q *Queries) ListPackageDependencyRefsForTarget(ctx context.Context, arg ListPackageDependencyRefsForTargetParams) ([]ListPackageDependencyRefsForTargetRow, error) {
	rows, err := q.db.Query(ctx, listPackageDependencyRefsForTarget, arg.BotID, arg.WorkspaceTargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPackageDependencyRefsForTargetRow
	for rows.Next() {
		var i ListPackageDependencyRefsForTargetRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.InstallationID,
			&i.DependencyID,
			&i.CreatedAt,
			&i.RegistryID,
			&i.PackageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPackageConnectorRefConnection = `-- name: SetPackageConnectorRefConnection :one
UPDATE bot_package_connector_refs
SET connection_id = $1,
    updated_at = now()
WHERE team_id = public.memoh_current_team_id()
  AND installation_id = $2
  AND connector_type = $3
RETURNING id, team_id, installation_id, connector_type, connection_id, required, created_at, updated_at
`

type SetPackageConnectorRefConnectionParams struct {
	ConnectionID   string      `json:"connection_id"`
	InstallationID pgtype.UUID `json:"installation_id"`
	ConnectorType  string      `json:"connector_type"`
}

func (q *Queries) SetPackageConnectorRefConnection(ctx context.Context, arg SetPackageConnectorRefConnectionParams) (BotPackageConnectorRef, error) {
	row := q.db.QueryRow(ctx, setPackageConnectorRefConnection, arg.ConnectionID, arg.InstallationID, arg.ConnectorType)
	var i BotPackageConnectorRef
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.InstallationID,
		&i.ConnectorType,
		&i.ConnectionID,
		&i.Required,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBotPackageInstallationCheck = `-- name: UpdateBotPackageInstallationCheck :one
UPDATE bot_package_installations
SET available_revision = $1,
    available_version = $2,
    last_checked_at = $3,
    updated_at = now()
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $4
  AND id = $5
RETURNING id, team_id, bot_id, workspace_target_id, registry_id, package_id, revision, version,
          status, reason, available_revision, available_version, last_checked_at, last_error,
          release, installed_at, updated_at
`

type UpdateBotPackageInstallationCheckParams struct {
	AvailableRevision string             `json:"available_revision"`
	AvailableVersion  string             `json:"available_version"`
	LastCheckedAt     pgtype.Timestamptz `json:"last_checked_at"`
	BotID             pgtype.UUID        `json:"bot_id"`
	ID                pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateBotPackageInstallationCheck(ctx context.Context, arg UpdateBotPackageInstallationCheckParams) (BotPackageInstallation, error) {
	row := q.db.QueryRow(ctx, updateBotPackageInstallationCheck,
		arg.AvailableRevision,
		arg.AvailableVersion,
		arg.LastCheckedAt,
		arg.BotID,
		arg.ID,
	)
	var i BotPackageInstallation
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BotID,
		&i.WorkspaceTargetID,
		&i.RegistryID,
		&i.PackageID,
		&i.Revision,
		&i.Version,
		&i.Status,
		&i.Reason,
		&i.AvailableRevision,
		&i.AvailableVersion,
		&i.LastCheckedAt,
		&i.LastError,
		&i.Release,
		&i.InstalledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBotPackageInstallationRelease = `-- name: UpdateBotPackageInstallationRelease :one
UPDATE bot_package_installations
SET revision = $1,
    version = $2,
    release = $3,
    available_revision = '',
    available_version = '',
    updated_at = now()
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $4
  AND id = $5
RETURNING id, team_id, bot_id, workspace_target_id, registry_id, package_id, revision, version,
          status, reason, available_revision, available_version, last_checked_at, last_error,
          release, installed_at, updated_at
`

type UpdateBotPackageInstallationReleaseParams struct {
	Revision string      `json:"revision"`
	Version  string      `json:"version"`
	Release  []byte      `json:"release"`
	BotID    pgtype.UUID `json:"bot_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateBotPackageInstallationRelease(ctx context.Context, arg UpdateBotPackageInstallationReleaseParams) (BotPackageInstallation, error) {
	row := q.db.QueryRow(ctx, updateBotPackageInstallationRelease,
		arg.Revision,
		arg.Version,
		arg.Release,
		arg.BotID,
		arg.ID,
	)
	var i BotPackageInstallation
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BotID,
		&i.WorkspaceTargetID,
		&i.RegistryID,
		&i.PackageID,
		&i.Revision,
		&i.Version,
		&i.Status,
		&i.Reason,
		&i.AvailableRevision,
		&i.AvailableVersion,
		&i.LastCheckedAt,
		&i.LastError,
		&i.Release,
		&i.InstalledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBotPackageInstallationStatus = `-- name: UpdateBotPackageInstallationStatus :one
UPDATE bot_package_installations
SET status = $1,
    last_error = $2,
    updated_at = now()
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $3
  AND id = $4
RETURNING id, team_id, bot_id, workspace_target_id, registry_id, package_id, revision, version,
          status, reason, available_revision, available_version, last_checked_at, last_error,
          release, installed_at, updated_at
`

type UpdateBotPackageInstallationStatusParams struct {
	Status    string      `json:"status"`
	LastError string      `json:"last_error"`
	BotID     pgtype.UUID `json:"bot_id"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateBotPackageInstallationStatus(ctx context.Context, arg UpdateBotPackageInstallationStatusParams) (BotPackageInstallation, error) {
	row := q.db.QueryRow(ctx, updateBotPackageInstallationStatus,
		arg.Status,
		arg.LastError,
		arg.BotID,
		arg.ID,
	)
	var i BotPackageInstallation
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BotID,
		&i.WorkspaceTargetID,
		&i.RegistryID,
		&i.PackageID,
		&i.Revision,
		&i.Version,
		&i.Status,
		&i.Reason,
		&i.AvailableRevision,
		&i.AvailableVersion,
		&i.LastCheckedAt,
		&i.LastError,
		&i.Release,
		&i.InstalledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBotPackageInstallation = `-- name: UpsertBotPackageInstallation :one
INSERT INTO bot_package_installations (
  bot_id, workspace_target_id, registry_id, package_id, revision, version, status, reason, release
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (team_id, bot_id, workspace_target_id, registry_id, package_id)
DO UPDATE SET revision = EXCLUDED.revision,
              version = EXCLUDED.version,
              status = EXCLUDED.status,
              reason = CASE WHEN EXCLUDED.reason = 'user' THEN 'user' ELSE bot_package_installations.reason END,
              release = EXCLUDED.release,
              last_error = '',
              updated_at = now()
RETURNING id, team_id, bot_id, workspace_target_id, registry_id, package_id, revision, version,
          status, reason, available_revision, available_version, last_checked_at, last_error,
          release, installed_at, updated_at
`

type UpsertBotPackageInstallationParams struct {
	BotID             pgtype.UUID `json:"bot_id"`
	WorkspaceTargetID string      `json:"workspace_target_id"`
	RegistryID        string      `json:"registry_id"`
	PackageID         string      `json:"package_id"`
	Revision          string      `json:"revision"`
	Version           string      `json:"version"`
	Status            string      `json:"status"`
	Reason            string      `json:"reason"`
	Release           []byte      `json:"release"`
}

func (q *Queries) UpsertBotPackageInstallation(ctx context.Context, arg UpsertBotPackageInstallationParams) (BotPackageInstallation, error) {
	row := q.db.QueryRow(ctx, upsertBotPackageInstallation,
		arg.BotID,
		arg.WorkspaceTargetID,
		arg.RegistryID,
		arg.PackageID,
		arg.Revision,
		arg.Version,
		arg.Status,
		arg.Reason,
		arg.Release,
	)
	var i BotPackageInstallation
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BotID,
		&i.WorkspaceTargetID,
		&i.RegistryID,
		&i.PackageID,
		&i.Revision,
		&i.Version,
		&i.Status,
		&i.Reason,
		&i.AvailableRevision,
		&i.AvailableVersion,
		&i.LastCheckedAt,
		&i.LastError,
		&i.Release,
		&i.InstalledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPackageConnectorRef = `-- name: UpsertPackageConnectorRef :one
INSERT INTO bot_package_connector_refs (installation_id, connector_type, connection_id, required)
VALUES ($1, $2, $3, $4)
ON CONFLICT (team_id, installation_id, connector_type)
DO UPDATE SET connection_id = CASE WHEN EXCLUDED.connection_id <> '' THEN EXCLUDED.connection_id ELSE bot_package_connector_refs.connection_id END,
              required = EXCLUDED.required,
              updated_at = now()
RETURNING id, team_id, installation_id, connector_type, connection_id, required, created_at, updated_at
`

type UpsertPackageConnectorRefParams struct {
	InstallationID pgtype.UUID `json:"installation_id"`
	ConnectorType  string      `json:"connector_type"`
	ConnectionID   string      `json:"connection_id"`
	Required       bool        `json:"required"`
}

func (q *Queries) UpsertPackageConnectorRef(ctx context.Context, arg UpsertPackageConnectorRefParams) (BotPackageConnectorRef, error) {
	row := q.db.QueryRow(ctx, upsertPackageConnectorRef,
		arg.InstallationID,
		arg.ConnectorType,
		arg.ConnectionID,
		arg.Required,
	)
	var i BotPackageConnectorRef
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.InstallationID,
		&i.ConnectorType,
		&i.ConnectionID,
		&i.Required,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPackageDependencyRef = `-- name: UpsertPackageDependencyRef :one
INSERT INTO bot_package_dependency_refs (installation_id, dependency_id)
VALUES ($1, $2)
ON CONFLICT (team_id, installation_id, dependency_id) DO UPDATE SET dependency_id = EXCLUDED.dependency_id
RETURNING id, team_id, installation_id, dependency_id, created_at
`

type UpsertPackageDependencyRefParams struct {
	InstallationID pgtype.UUID `json:"installation_id"`
	DependencyID   string      `json:"dependency_id"`
}

func (q *Queries) UpsertPackageDependencyRef(ctx context.Context, arg UpsertPackageDependencyRefParams) (BotPackageDependencyRef, error) {
	row := q.db.QueryRow(ctx, upsertPackageDependencyRef, arg.InstallationID, arg.DependencyID)
	var i BotPackageDependencyRef
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.InstallationID,
		&i.DependencyID,
		&i.CreatedAt,
	)
	return i, err
}
