// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_input_queues.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireContinuationRun = `-- name: AcquireContinuationRun :one
WITH candidate AS MATERIALIZED (
  SELECT run.run_id
  FROM session_runs run
  JOIN bot_sessions session ON session.team_id=run.team_id AND session.id=run.session_id
  JOIN bots bot ON bot.team_id=run.team_id AND bot.id=run.bot_id
  WHERE run.team_id=public.memoh_current_team_id() AND run.run_id=$3
    AND run.state='accepted' AND run.owner_id IS NULL AND run.source_follow_up_item_id IS NOT NULL
    AND session.deleted_at IS NULL AND bot.status <> 'deleting'
    AND (bot.runtime_reset_expires_at IS NULL OR bot.runtime_reset_expires_at <= clock_timestamp())
    AND (session.runtime_reset_expires_at IS NULL OR session.runtime_reset_expires_at <= clock_timestamp())
  FOR UPDATE OF run
)
UPDATE session_runs run
SET owner_id=$1, owner_since=now(), fencing_token=nextval('session_runtime_fencing_token_seq'),
    live_generation=$2, state='running', updated_at=now()
FROM candidate
WHERE run.team_id=public.memoh_current_team_id() AND run.run_id=candidate.run_id
RETURNING run.run_id, run.team_id, run.bot_id, run.session_id, run.invocation_id, run.turn_id, run.turn_position, run.state, run.input_json, run.input_fingerprint, run.owner_id, run.fencing_token, run.owner_since, run.live_generation, run.source_follow_up_item_id, run.abort_requested_at, run.error_code, run.error_message, run.created_at, run.updated_at
`

type AcquireContinuationRunParams struct {
	ExecutionOwnerID  pgtype.Text `json:"execution_owner_id"`
	LiveGeneration    pgtype.Text `json:"live_generation"`
	ContinuationRunID pgtype.UUID `json:"continuation_run_id"`
}

func (q *Queries) AcquireContinuationRun(ctx context.Context, arg AcquireContinuationRunParams) (SessionRun, error) {
	row := q.db.QueryRow(ctx, acquireContinuationRun, arg.ExecutionOwnerID, arg.LiveGeneration, arg.ContinuationRunID)
	var i SessionRun
	err := row.Scan(
		&i.RunID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.InvocationID,
		&i.TurnID,
		&i.TurnPosition,
		&i.State,
		&i.InputJson,
		&i.InputFingerprint,
		&i.OwnerID,
		&i.FencingToken,
		&i.OwnerSince,
		&i.LiveGeneration,
		&i.SourceFollowUpItemID,
		&i.AbortRequestedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const acquireQueuedRun = `-- name: AcquireQueuedRun :one
UPDATE session_runs
SET owner_id=$1, owner_since=now(),
    fencing_token=nextval('session_runtime_fencing_token_seq'),
    live_generation=$2, updated_at=now()
WHERE team_id=public.memoh_current_team_id() AND run_id=$3
  AND state='running' AND owner_id IS NOT NULL
  AND fencing_token=$4
RETURNING run_id, team_id, bot_id, session_id, invocation_id, turn_id, turn_position, state, input_json, input_fingerprint, owner_id, fencing_token, owner_since, live_generation, source_follow_up_item_id, abort_requested_at, error_code, error_message, created_at, updated_at
`

type AcquireQueuedRunParams struct {
	ExecutionOwnerID     pgtype.Text `json:"execution_owner_id"`
	LiveGeneration       pgtype.Text `json:"live_generation"`
	RunID                pgtype.UUID `json:"run_id"`
	PreviousFencingToken int64       `json:"previous_fencing_token"`
}

func (q *Queries) AcquireQueuedRun(ctx context.Context, arg AcquireQueuedRunParams) (SessionRun, error) {
	row := q.db.QueryRow(ctx, acquireQueuedRun,
		arg.ExecutionOwnerID,
		arg.LiveGeneration,
		arg.RunID,
		arg.PreviousFencingToken,
	)
	var i SessionRun
	err := row.Scan(
		&i.RunID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.InvocationID,
		&i.TurnID,
		&i.TurnPosition,
		&i.State,
		&i.InputJson,
		&i.InputFingerprint,
		&i.OwnerID,
		&i.FencingToken,
		&i.OwnerSince,
		&i.LiveGeneration,
		&i.SourceFollowUpItemID,
		&i.AbortRequestedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const applyFollowUpQueueItem = `-- name: ApplyFollowUpQueueItem :one
UPDATE session_follow_up_queue AS target SET status='applied', claim_run_id=NULL, claim_owner_id=NULL, claim_fencing_token=NULL, updated_at=now()
WHERE target.team_id=public.memoh_current_team_id() AND target.item_id=$1 AND target.claim_run_id=$2 AND target.claim_owner_id=$3 AND target.claim_fencing_token=$4 AND target.status='claimed'
  AND EXISTS (SELECT 1 FROM session_runs run WHERE run.team_id=public.memoh_current_team_id() AND run.run_id=$2 AND run.owner_id=$3 AND run.fencing_token=$4 AND run.state IN ('accepted','running','waiting_decision'))
RETURNING item_id, team_id, bot_id, session_id, enqueued_during_run_id, assigned_run_id, invocation_id, payload, status, position, claim_run_id, claim_owner_id, claim_fencing_token, created_at, updated_at
`

type ApplyFollowUpQueueItemParams struct {
	QueueItemID           pgtype.UUID `json:"queue_item_id"`
	ExecutionRunID        pgtype.UUID `json:"execution_run_id"`
	ExecutionOwnerID      pgtype.Text `json:"execution_owner_id"`
	ExecutionFencingToken pgtype.Int8 `json:"execution_fencing_token"`
}

func (q *Queries) ApplyFollowUpQueueItem(ctx context.Context, arg ApplyFollowUpQueueItemParams) (SessionFollowUpQueue, error) {
	row := q.db.QueryRow(ctx, applyFollowUpQueueItem,
		arg.QueueItemID,
		arg.ExecutionRunID,
		arg.ExecutionOwnerID,
		arg.ExecutionFencingToken,
	)
	var i SessionFollowUpQueue
	err := row.Scan(
		&i.ItemID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.EnqueuedDuringRunID,
		&i.AssignedRunID,
		&i.InvocationID,
		&i.Payload,
		&i.Status,
		&i.Position,
		&i.ClaimRunID,
		&i.ClaimOwnerID,
		&i.ClaimFencingToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const applySteerQueueItem = `-- name: ApplySteerQueueItem :one
UPDATE session_steer_queue AS target SET status='applied', claim_run_id=NULL, claim_owner_id=NULL, claim_fencing_token=NULL, updated_at=now()
WHERE target.team_id=public.memoh_current_team_id() AND target.item_id=$1 AND target.claim_run_id=$2 AND target.claim_owner_id=$3 AND target.claim_fencing_token=$4 AND target.status='claimed'
  AND EXISTS (SELECT 1 FROM session_runs run WHERE run.team_id=public.memoh_current_team_id() AND run.run_id=$2 AND run.owner_id=$3 AND run.fencing_token=$4 AND run.state IN ('accepted','running','waiting_decision'))
RETURNING item_id, team_id, bot_id, session_id, target_run_id, invocation_id, payload, status, position, claim_run_id, claim_owner_id, claim_fencing_token, created_at, updated_at
`

type ApplySteerQueueItemParams struct {
	QueueItemID           pgtype.UUID `json:"queue_item_id"`
	ExecutionRunID        pgtype.UUID `json:"execution_run_id"`
	ExecutionOwnerID      pgtype.Text `json:"execution_owner_id"`
	ExecutionFencingToken pgtype.Int8 `json:"execution_fencing_token"`
}

func (q *Queries) ApplySteerQueueItem(ctx context.Context, arg ApplySteerQueueItemParams) (SessionSteerQueue, error) {
	row := q.db.QueryRow(ctx, applySteerQueueItem,
		arg.QueueItemID,
		arg.ExecutionRunID,
		arg.ExecutionOwnerID,
		arg.ExecutionFencingToken,
	)
	var i SessionSteerQueue
	err := row.Scan(
		&i.ItemID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.TargetRunID,
		&i.InvocationID,
		&i.Payload,
		&i.Status,
		&i.Position,
		&i.ClaimRunID,
		&i.ClaimOwnerID,
		&i.ClaimFencingToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const assignFollowUpQueueItem = `-- name: AssignFollowUpQueueItem :one
UPDATE session_follow_up_queue AS target SET assigned_run_id=$1, updated_at=now() WHERE target.team_id=public.memoh_current_team_id() AND target.item_id=(SELECT pending.item_id FROM session_follow_up_queue AS pending WHERE pending.team_id=public.memoh_current_team_id() AND pending.session_id=$2 AND pending.status='accepted' AND pending.assigned_run_id IS NULL ORDER BY pending.position,pending.item_id LIMIT 1) RETURNING target.item_id, target.team_id, target.bot_id, target.session_id, target.enqueued_during_run_id, target.assigned_run_id, target.invocation_id, target.payload, target.status, target.position, target.claim_run_id, target.claim_owner_id, target.claim_fencing_token, target.created_at, target.updated_at
`

type AssignFollowUpQueueItemParams struct {
	RunID     pgtype.UUID `json:"run_id"`
	SessionID pgtype.UUID `json:"session_id"`
}

func (q *Queries) AssignFollowUpQueueItem(ctx context.Context, arg AssignFollowUpQueueItemParams) (SessionFollowUpQueue, error) {
	row := q.db.QueryRow(ctx, assignFollowUpQueueItem, arg.RunID, arg.SessionID)
	var i SessionFollowUpQueue
	err := row.Scan(
		&i.ItemID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.EnqueuedDuringRunID,
		&i.AssignedRunID,
		&i.InvocationID,
		&i.Payload,
		&i.Status,
		&i.Position,
		&i.ClaimRunID,
		&i.ClaimOwnerID,
		&i.ClaimFencingToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelAcceptedFollowUpQueueItem = `-- name: CancelAcceptedFollowUpQueueItem :one
UPDATE session_follow_up_queue SET status='canceled', updated_at=now()
WHERE team_id=public.memoh_current_team_id() AND session_id=$1
  AND item_id=$2 AND status='accepted' AND assigned_run_id IS NULL
RETURNING item_id, team_id, bot_id, session_id, enqueued_during_run_id, assigned_run_id, invocation_id, payload, status, position, claim_run_id, claim_owner_id, claim_fencing_token, created_at, updated_at
`

type CancelAcceptedFollowUpQueueItemParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	ItemID    pgtype.UUID `json:"item_id"`
}

func (q *Queries) CancelAcceptedFollowUpQueueItem(ctx context.Context, arg CancelAcceptedFollowUpQueueItemParams) (SessionFollowUpQueue, error) {
	row := q.db.QueryRow(ctx, cancelAcceptedFollowUpQueueItem, arg.SessionID, arg.ItemID)
	var i SessionFollowUpQueue
	err := row.Scan(
		&i.ItemID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.EnqueuedDuringRunID,
		&i.AssignedRunID,
		&i.InvocationID,
		&i.Payload,
		&i.Status,
		&i.Position,
		&i.ClaimRunID,
		&i.ClaimOwnerID,
		&i.ClaimFencingToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelAcceptedSteerQueueItem = `-- name: CancelAcceptedSteerQueueItem :one
UPDATE session_steer_queue SET status='canceled', updated_at=now()
WHERE team_id=public.memoh_current_team_id() AND session_id=$1
  AND item_id=$2 AND status='accepted'
RETURNING item_id, team_id, bot_id, session_id, target_run_id, invocation_id, payload, status, position, claim_run_id, claim_owner_id, claim_fencing_token, created_at, updated_at
`

type CancelAcceptedSteerQueueItemParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	ItemID    pgtype.UUID `json:"item_id"`
}

func (q *Queries) CancelAcceptedSteerQueueItem(ctx context.Context, arg CancelAcceptedSteerQueueItemParams) (SessionSteerQueue, error) {
	row := q.db.QueryRow(ctx, cancelAcceptedSteerQueueItem, arg.SessionID, arg.ItemID)
	var i SessionSteerQueue
	err := row.Scan(
		&i.ItemID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.TargetRunID,
		&i.InvocationID,
		&i.Payload,
		&i.Status,
		&i.Position,
		&i.ClaimRunID,
		&i.ClaimOwnerID,
		&i.ClaimFencingToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimAssignedFollowUpQueueItem = `-- name: ClaimAssignedFollowUpQueueItem :one
UPDATE session_follow_up_queue AS target SET status='claimed', claim_run_id=$1, claim_owner_id=$2, claim_fencing_token=$3, updated_at=now()
WHERE target.team_id=public.memoh_current_team_id() AND target.item_id=$4 AND target.assigned_run_id=$1 AND target.status='accepted'
  AND EXISTS (SELECT 1 FROM session_runs run WHERE run.team_id=public.memoh_current_team_id() AND run.run_id=$1 AND run.owner_id=$2 AND run.fencing_token=$3 AND run.state IN ('accepted','running','waiting_decision'))
  AND NOT EXISTS (SELECT 1 FROM session_steer_queue claimed WHERE claimed.team_id=public.memoh_current_team_id() AND claimed.claim_run_id=$1 AND claimed.status='claimed')
  AND NOT EXISTS (SELECT 1 FROM session_follow_up_queue claimed WHERE claimed.team_id=public.memoh_current_team_id() AND claimed.claim_run_id=$1 AND claimed.status='claimed')
RETURNING item_id, team_id, bot_id, session_id, enqueued_during_run_id, assigned_run_id, invocation_id, payload, status, position, claim_run_id, claim_owner_id, claim_fencing_token, created_at, updated_at
`

type ClaimAssignedFollowUpQueueItemParams struct {
	ExecutionRunID        pgtype.UUID `json:"execution_run_id"`
	ExecutionOwnerID      pgtype.Text `json:"execution_owner_id"`
	ExecutionFencingToken pgtype.Int8 `json:"execution_fencing_token"`
	QueueItemID           pgtype.UUID `json:"queue_item_id"`
}

func (q *Queries) ClaimAssignedFollowUpQueueItem(ctx context.Context, arg ClaimAssignedFollowUpQueueItemParams) (SessionFollowUpQueue, error) {
	row := q.db.QueryRow(ctx, claimAssignedFollowUpQueueItem,
		arg.ExecutionRunID,
		arg.ExecutionOwnerID,
		arg.ExecutionFencingToken,
		arg.QueueItemID,
	)
	var i SessionFollowUpQueue
	err := row.Scan(
		&i.ItemID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.EnqueuedDuringRunID,
		&i.AssignedRunID,
		&i.InvocationID,
		&i.Payload,
		&i.Status,
		&i.Position,
		&i.ClaimRunID,
		&i.ClaimOwnerID,
		&i.ClaimFencingToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimSteerQueueItem = `-- name: ClaimSteerQueueItem :one
UPDATE session_steer_queue AS target SET status='claimed', claim_run_id=$1, claim_owner_id=$2, claim_fencing_token=$3, updated_at=now()
WHERE target.team_id=public.memoh_current_team_id() AND target.item_id=$4 AND target.target_run_id=$1 AND target.status='accepted'
  AND EXISTS (SELECT 1 FROM session_runs run WHERE run.team_id=public.memoh_current_team_id() AND run.run_id=$1 AND run.owner_id=$2 AND run.fencing_token=$3 AND run.state IN ('accepted','running','waiting_decision'))
  AND NOT EXISTS (SELECT 1 FROM session_steer_queue claimed WHERE claimed.team_id=public.memoh_current_team_id() AND claimed.claim_run_id=$1 AND claimed.status='claimed')
  AND NOT EXISTS (SELECT 1 FROM session_follow_up_queue claimed WHERE claimed.team_id=public.memoh_current_team_id() AND claimed.claim_run_id=$1 AND claimed.status='claimed')
RETURNING item_id, team_id, bot_id, session_id, target_run_id, invocation_id, payload, status, position, claim_run_id, claim_owner_id, claim_fencing_token, created_at, updated_at
`

type ClaimSteerQueueItemParams struct {
	ExecutionRunID        pgtype.UUID `json:"execution_run_id"`
	ExecutionOwnerID      pgtype.Text `json:"execution_owner_id"`
	ExecutionFencingToken pgtype.Int8 `json:"execution_fencing_token"`
	QueueItemID           pgtype.UUID `json:"queue_item_id"`
}

func (q *Queries) ClaimSteerQueueItem(ctx context.Context, arg ClaimSteerQueueItemParams) (SessionSteerQueue, error) {
	row := q.db.QueryRow(ctx, claimSteerQueueItem,
		arg.ExecutionRunID,
		arg.ExecutionOwnerID,
		arg.ExecutionFencingToken,
		arg.QueueItemID,
	)
	var i SessionSteerQueue
	err := row.Scan(
		&i.ItemID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.TargetRunID,
		&i.InvocationID,
		&i.Payload,
		&i.Status,
		&i.Position,
		&i.ClaimRunID,
		&i.ClaimOwnerID,
		&i.ClaimFencingToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createContinuationFromFollowUp = `-- name: CreateContinuationFromFollowUp :one
WITH parent AS MATERIALIZED (
  SELECT run.run_id, run.team_id, run.bot_id, run.session_id
  FROM session_runs run
  WHERE run.team_id=public.memoh_current_team_id() AND run.run_id=$1
    AND run.fencing_token=$2 AND run.state='completed'
), picked AS MATERIALIZED (
  SELECT f.item_id, f.team_id, f.bot_id, f.session_id, f.payload, f.assigned_run_id
  FROM session_follow_up_queue f
  JOIN parent ON parent.team_id=f.team_id AND parent.bot_id=f.bot_id AND parent.session_id=f.session_id
  WHERE f.team_id=public.memoh_current_team_id() AND f.item_id=$3 AND f.status='accepted'
    AND (f.assigned_run_id IS NULL OR f.assigned_run_id=$4)
  FOR UPDATE
), existing AS MATERIALIZED (
  SELECT run.run_id, run.team_id, run.bot_id, run.session_id, run.invocation_id, run.turn_id, run.turn_position, run.state, run.input_json, run.input_fingerprint, run.owner_id, run.fencing_token, run.owner_since, run.live_generation, run.source_follow_up_item_id, run.abort_requested_at, run.error_code, run.error_message, run.created_at, run.updated_at
  FROM session_runs run JOIN picked p ON p.team_id=run.team_id AND p.item_id=run.source_follow_up_item_id
  WHERE run.run_id=$4
), position AS (
  UPDATE bot_sessions s SET next_turn_position=s.next_turn_position+1
  FROM picked p WHERE s.team_id=p.team_id AND s.id=p.session_id AND p.assigned_run_id IS NULL AND NOT EXISTS (SELECT 1 FROM existing)
  RETURNING s.next_turn_position-1 AS turn_position
), assigned AS (
  UPDATE session_follow_up_queue f SET assigned_run_id=$4, updated_at=now()
  FROM picked p WHERE f.team_id=p.team_id AND f.item_id=p.item_id AND f.assigned_run_id IS NULL
  RETURNING f.item_id
), inserted AS (
INSERT INTO session_runs (run_id, team_id, bot_id, session_id, invocation_id, turn_id, turn_position, state, input_json, input_fingerprint, source_follow_up_item_id)
SELECT $4, p.team_id, p.bot_id, p.session_id, $5, $6, pos.turn_position, 'accepted', p.payload, $7, p.item_id
FROM picked p CROSS JOIN position pos JOIN assigned a ON a.item_id=p.item_id
ON CONFLICT (team_id, run_id) DO NOTHING
RETURNING run_id, team_id, bot_id, session_id, invocation_id, turn_id, turn_position, state, input_json, input_fingerprint, owner_id, fencing_token, owner_since, live_generation, source_follow_up_item_id, abort_requested_at, error_code, error_message, created_at, updated_at
)
SELECT run_id, team_id, bot_id, session_id, invocation_id, turn_id, turn_position, state, input_json, input_fingerprint, owner_id, fencing_token, owner_since, live_generation, source_follow_up_item_id, abort_requested_at, error_code, error_message, created_at, updated_at FROM inserted
UNION ALL
SELECT run_id, team_id, bot_id, session_id, invocation_id, turn_id, turn_position, state, input_json, input_fingerprint, owner_id, fencing_token, owner_since, live_generation, source_follow_up_item_id, abort_requested_at, error_code, error_message, created_at, updated_at FROM existing
LIMIT 1
`

type CreateContinuationFromFollowUpParams struct {
	ParentRunID        pgtype.UUID `json:"parent_run_id"`
	ParentFencingToken int64       `json:"parent_fencing_token"`
	ItemID             pgtype.UUID `json:"item_id"`
	RunID              pgtype.UUID `json:"run_id"`
	InvocationID       string      `json:"invocation_id"`
	TurnID             pgtype.UUID `json:"turn_id"`
	InputFingerprint   string      `json:"input_fingerprint"`
}

type CreateContinuationFromFollowUpRow struct {
	RunID                pgtype.UUID        `json:"run_id"`
	TeamID               pgtype.UUID        `json:"team_id"`
	BotID                pgtype.UUID        `json:"bot_id"`
	SessionID            pgtype.UUID        `json:"session_id"`
	InvocationID         string             `json:"invocation_id"`
	TurnID               pgtype.UUID        `json:"turn_id"`
	TurnPosition         int64              `json:"turn_position"`
	State                string             `json:"state"`
	InputJson            []byte             `json:"input_json"`
	InputFingerprint     string             `json:"input_fingerprint"`
	OwnerID              pgtype.Text        `json:"owner_id"`
	FencingToken         int64              `json:"fencing_token"`
	OwnerSince           pgtype.Timestamptz `json:"owner_since"`
	LiveGeneration       pgtype.Text        `json:"live_generation"`
	SourceFollowUpItemID pgtype.UUID        `json:"source_follow_up_item_id"`
	AbortRequestedAt     pgtype.Timestamptz `json:"abort_requested_at"`
	ErrorCode            pgtype.Text        `json:"error_code"`
	ErrorMessage         pgtype.Text        `json:"error_message"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

// A follow-up's enqueued_during_run_id is admission provenance, not a parent
// constraint. The next completed continuation may hand off the next accepted
// item from the same session, preserving FIFO across R1, R2, and later runs.
func (q *Queries) CreateContinuationFromFollowUp(ctx context.Context, arg CreateContinuationFromFollowUpParams) (CreateContinuationFromFollowUpRow, error) {
	row := q.db.QueryRow(ctx, createContinuationFromFollowUp,
		arg.ParentRunID,
		arg.ParentFencingToken,
		arg.ItemID,
		arg.RunID,
		arg.InvocationID,
		arg.TurnID,
		arg.InputFingerprint,
	)
	var i CreateContinuationFromFollowUpRow
	err := row.Scan(
		&i.RunID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.InvocationID,
		&i.TurnID,
		&i.TurnPosition,
		&i.State,
		&i.InputJson,
		&i.InputFingerprint,
		&i.OwnerID,
		&i.FencingToken,
		&i.OwnerSince,
		&i.LiveGeneration,
		&i.SourceFollowUpItemID,
		&i.AbortRequestedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSessionQueueStepCommit = `-- name: CreateSessionQueueStepCommit :one
INSERT INTO session_queue_step_commits (
  team_id, run_id, step_index, commit_hash, action,
  steer_item_id, follow_up_item_id, continuation_run_id
) VALUES (
  public.memoh_current_team_id(), $1, $2, $3, $4,
  $5, $6, $7
)
ON CONFLICT (team_id, run_id, step_index) DO NOTHING
RETURNING team_id, run_id, step_index, commit_hash, action, steer_item_id, follow_up_item_id, continuation_run_id, created_at
`

type CreateSessionQueueStepCommitParams struct {
	RunID             pgtype.UUID `json:"run_id"`
	StepIndex         int64       `json:"step_index"`
	CommitHash        string      `json:"commit_hash"`
	Action            string      `json:"action"`
	SteerItemID       pgtype.UUID `json:"steer_item_id"`
	FollowUpItemID    pgtype.UUID `json:"follow_up_item_id"`
	ContinuationRunID pgtype.UUID `json:"continuation_run_id"`
}

func (q *Queries) CreateSessionQueueStepCommit(ctx context.Context, arg CreateSessionQueueStepCommitParams) (SessionQueueStepCommit, error) {
	row := q.db.QueryRow(ctx, createSessionQueueStepCommit,
		arg.RunID,
		arg.StepIndex,
		arg.CommitHash,
		arg.Action,
		arg.SteerItemID,
		arg.FollowUpItemID,
		arg.ContinuationRunID,
	)
	var i SessionQueueStepCommit
	err := row.Scan(
		&i.TeamID,
		&i.RunID,
		&i.StepIndex,
		&i.CommitHash,
		&i.Action,
		&i.SteerItemID,
		&i.FollowUpItemID,
		&i.ContinuationRunID,
		&i.CreatedAt,
	)
	return i, err
}

const enqueueFollowUpQueueItem = `-- name: EnqueueFollowUpQueueItem :one
WITH locked_session AS MATERIALIZED (
  SELECT s.id
  FROM bot_sessions s
  JOIN bots bot ON bot.team_id=s.team_id AND bot.id=s.bot_id
  WHERE s.team_id=public.memoh_current_team_id() AND s.id=$3
    AND s.bot_id=$2 AND s.deleted_at IS NULL AND bot.status <> 'deleting'
  FOR UPDATE OF s
), active_run AS MATERIALIZED (
  SELECT run.run_id
  FROM session_runs run
  JOIN locked_session s ON s.id=run.session_id
  WHERE run.team_id=public.memoh_current_team_id() AND run.bot_id=$2
    AND run.state IN ('accepted','running','waiting_decision')
)
INSERT INTO session_follow_up_queue (item_id, team_id, bot_id, session_id, enqueued_during_run_id, invocation_id, payload, position)
SELECT $1, public.memoh_current_team_id(), $2, $3, run.run_id, $4, $5, COALESCE((SELECT max(position)+1 FROM session_follow_up_queue WHERE team_id=public.memoh_current_team_id() AND session_id=$3),1)
FROM active_run run
ON CONFLICT (team_id, session_id, invocation_id) DO NOTHING
RETURNING item_id, team_id, bot_id, session_id, enqueued_during_run_id, assigned_run_id, invocation_id, payload, status, position, claim_run_id, claim_owner_id, claim_fencing_token, created_at, updated_at
`

type EnqueueFollowUpQueueItemParams struct {
	ItemID       pgtype.UUID `json:"item_id"`
	BotID        pgtype.UUID `json:"bot_id"`
	SessionID    pgtype.UUID `json:"session_id"`
	InvocationID string      `json:"invocation_id"`
	Payload      []byte      `json:"payload"`
}

func (q *Queries) EnqueueFollowUpQueueItem(ctx context.Context, arg EnqueueFollowUpQueueItemParams) (SessionFollowUpQueue, error) {
	row := q.db.QueryRow(ctx, enqueueFollowUpQueueItem,
		arg.ItemID,
		arg.BotID,
		arg.SessionID,
		arg.InvocationID,
		arg.Payload,
	)
	var i SessionFollowUpQueue
	err := row.Scan(
		&i.ItemID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.EnqueuedDuringRunID,
		&i.AssignedRunID,
		&i.InvocationID,
		&i.Payload,
		&i.Status,
		&i.Position,
		&i.ClaimRunID,
		&i.ClaimOwnerID,
		&i.ClaimFencingToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const enqueueSteerQueueItem = `-- name: EnqueueSteerQueueItem :one
WITH locked_session AS MATERIALIZED (
  SELECT s.id
  FROM bot_sessions s
  JOIN bots bot ON bot.team_id=s.team_id AND bot.id=s.bot_id
  WHERE s.team_id=public.memoh_current_team_id() AND s.id=$3
    AND s.bot_id=$2 AND s.deleted_at IS NULL AND bot.status <> 'deleting'
  FOR UPDATE OF s
), active_run AS MATERIALIZED (
  SELECT run.run_id
  FROM session_runs run
  JOIN locked_session s ON s.id=run.session_id
  WHERE run.team_id=public.memoh_current_team_id() AND run.bot_id=$2
    AND run.state IN ('accepted','running','waiting_decision')
)
INSERT INTO session_steer_queue (item_id, team_id, bot_id, session_id, target_run_id, invocation_id, payload, position)
SELECT $1, public.memoh_current_team_id(), $2, $3, run.run_id, $4, $5, COALESCE((SELECT max(position)+1 FROM session_steer_queue WHERE team_id=public.memoh_current_team_id() AND session_id=$3),1)
FROM active_run run
ON CONFLICT (team_id, session_id, invocation_id) DO NOTHING
RETURNING item_id, team_id, bot_id, session_id, target_run_id, invocation_id, payload, status, position, claim_run_id, claim_owner_id, claim_fencing_token, created_at, updated_at
`

type EnqueueSteerQueueItemParams struct {
	ItemID       pgtype.UUID `json:"item_id"`
	BotID        pgtype.UUID `json:"bot_id"`
	SessionID    pgtype.UUID `json:"session_id"`
	InvocationID string      `json:"invocation_id"`
	Payload      []byte      `json:"payload"`
}

func (q *Queries) EnqueueSteerQueueItem(ctx context.Context, arg EnqueueSteerQueueItemParams) (SessionSteerQueue, error) {
	row := q.db.QueryRow(ctx, enqueueSteerQueueItem,
		arg.ItemID,
		arg.BotID,
		arg.SessionID,
		arg.InvocationID,
		arg.Payload,
	)
	var i SessionSteerQueue
	err := row.Scan(
		&i.ItemID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.TargetRunID,
		&i.InvocationID,
		&i.Payload,
		&i.Status,
		&i.Position,
		&i.ClaimRunID,
		&i.ClaimOwnerID,
		&i.ClaimFencingToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClaimedSteerQueueItemForRun = `-- name: GetClaimedSteerQueueItemForRun :one
SELECT item_id, team_id, bot_id, session_id, target_run_id, invocation_id, payload, status, position, claim_run_id, claim_owner_id, claim_fencing_token, created_at, updated_at FROM session_steer_queue
WHERE team_id=public.memoh_current_team_id() AND claim_run_id=$1
  AND status='claimed'
  AND EXISTS (
    SELECT 1 FROM session_queue_step_commits commit
    WHERE commit.team_id=public.memoh_current_team_id()
      AND commit.run_id=$1
      AND commit.steer_item_id=session_steer_queue.item_id
      AND commit.action='continue_with_steer'
  )
ORDER BY created_at, item_id LIMIT 1
`

func (q *Queries) GetClaimedSteerQueueItemForRun(ctx context.Context, runID pgtype.UUID) (SessionSteerQueue, error) {
	row := q.db.QueryRow(ctx, getClaimedSteerQueueItemForRun, runID)
	var i SessionSteerQueue
	err := row.Scan(
		&i.ItemID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.TargetRunID,
		&i.InvocationID,
		&i.Payload,
		&i.Status,
		&i.Position,
		&i.ClaimRunID,
		&i.ClaimOwnerID,
		&i.ClaimFencingToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContinuationRunForParent = `-- name: GetContinuationRunForParent :one
SELECT continuation.run_id, continuation.team_id, continuation.bot_id, continuation.session_id, continuation.invocation_id, continuation.turn_id, continuation.turn_position, continuation.state, continuation.input_json, continuation.input_fingerprint, continuation.owner_id, continuation.fencing_token, continuation.owner_since, continuation.live_generation, continuation.source_follow_up_item_id, continuation.abort_requested_at, continuation.error_code, continuation.error_message, continuation.created_at, continuation.updated_at
FROM session_runs continuation
JOIN session_follow_up_queue source ON source.team_id=continuation.team_id AND source.item_id=continuation.source_follow_up_item_id
WHERE continuation.team_id=public.memoh_current_team_id() AND source.enqueued_during_run_id=$1
ORDER BY continuation.turn_position, continuation.run_id
LIMIT 1
`

func (q *Queries) GetContinuationRunForParent(ctx context.Context, parentRunID pgtype.UUID) (SessionRun, error) {
	row := q.db.QueryRow(ctx, getContinuationRunForParent, parentRunID)
	var i SessionRun
	err := row.Scan(
		&i.RunID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.InvocationID,
		&i.TurnID,
		&i.TurnPosition,
		&i.State,
		&i.InputJson,
		&i.InputFingerprint,
		&i.OwnerID,
		&i.FencingToken,
		&i.OwnerSince,
		&i.LiveGeneration,
		&i.SourceFollowUpItemID,
		&i.AbortRequestedAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFollowUpQueueItem = `-- name: GetFollowUpQueueItem :one
SELECT item_id, team_id, bot_id, session_id, enqueued_during_run_id, assigned_run_id, invocation_id, payload, status, position, claim_run_id, claim_owner_id, claim_fencing_token, created_at, updated_at FROM session_follow_up_queue WHERE team_id=public.memoh_current_team_id() AND item_id=$1
`

func (q *Queries) GetFollowUpQueueItem(ctx context.Context, itemID pgtype.UUID) (SessionFollowUpQueue, error) {
	row := q.db.QueryRow(ctx, getFollowUpQueueItem, itemID)
	var i SessionFollowUpQueue
	err := row.Scan(
		&i.ItemID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.EnqueuedDuringRunID,
		&i.AssignedRunID,
		&i.InvocationID,
		&i.Payload,
		&i.Status,
		&i.Position,
		&i.ClaimRunID,
		&i.ClaimOwnerID,
		&i.ClaimFencingToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFollowUpQueueItemByInvocation = `-- name: GetFollowUpQueueItemByInvocation :one
SELECT item_id, team_id, bot_id, session_id, enqueued_during_run_id, assigned_run_id, invocation_id, payload, status, position, claim_run_id, claim_owner_id, claim_fencing_token, created_at, updated_at FROM session_follow_up_queue WHERE team_id=public.memoh_current_team_id() AND session_id=$1 AND invocation_id=$2
`

type GetFollowUpQueueItemByInvocationParams struct {
	SessionID    pgtype.UUID `json:"session_id"`
	InvocationID string      `json:"invocation_id"`
}

func (q *Queries) GetFollowUpQueueItemByInvocation(ctx context.Context, arg GetFollowUpQueueItemByInvocationParams) (SessionFollowUpQueue, error) {
	row := q.db.QueryRow(ctx, getFollowUpQueueItemByInvocation, arg.SessionID, arg.InvocationID)
	var i SessionFollowUpQueue
	err := row.Scan(
		&i.ItemID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.EnqueuedDuringRunID,
		&i.AssignedRunID,
		&i.InvocationID,
		&i.Payload,
		&i.Status,
		&i.Position,
		&i.ClaimRunID,
		&i.ClaimOwnerID,
		&i.ClaimFencingToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionQueueStepCommit = `-- name: GetSessionQueueStepCommit :one
SELECT team_id, run_id, step_index, commit_hash, action, steer_item_id, follow_up_item_id, continuation_run_id, created_at FROM session_queue_step_commits
WHERE team_id=public.memoh_current_team_id() AND run_id=$1 AND step_index=$2
`

type GetSessionQueueStepCommitParams struct {
	RunID     pgtype.UUID `json:"run_id"`
	StepIndex int64       `json:"step_index"`
}

func (q *Queries) GetSessionQueueStepCommit(ctx context.Context, arg GetSessionQueueStepCommitParams) (SessionQueueStepCommit, error) {
	row := q.db.QueryRow(ctx, getSessionQueueStepCommit, arg.RunID, arg.StepIndex)
	var i SessionQueueStepCommit
	err := row.Scan(
		&i.TeamID,
		&i.RunID,
		&i.StepIndex,
		&i.CommitHash,
		&i.Action,
		&i.SteerItemID,
		&i.FollowUpItemID,
		&i.ContinuationRunID,
		&i.CreatedAt,
	)
	return i, err
}

const getSteerQueueItem = `-- name: GetSteerQueueItem :one
SELECT item_id, team_id, bot_id, session_id, target_run_id, invocation_id, payload, status, position, claim_run_id, claim_owner_id, claim_fencing_token, created_at, updated_at FROM session_steer_queue WHERE team_id=public.memoh_current_team_id() AND item_id=$1
`

func (q *Queries) GetSteerQueueItem(ctx context.Context, itemID pgtype.UUID) (SessionSteerQueue, error) {
	row := q.db.QueryRow(ctx, getSteerQueueItem, itemID)
	var i SessionSteerQueue
	err := row.Scan(
		&i.ItemID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.TargetRunID,
		&i.InvocationID,
		&i.Payload,
		&i.Status,
		&i.Position,
		&i.ClaimRunID,
		&i.ClaimOwnerID,
		&i.ClaimFencingToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSteerQueueItemByInvocation = `-- name: GetSteerQueueItemByInvocation :one
SELECT item_id, team_id, bot_id, session_id, target_run_id, invocation_id, payload, status, position, claim_run_id, claim_owner_id, claim_fencing_token, created_at, updated_at FROM session_steer_queue WHERE team_id=public.memoh_current_team_id() AND session_id=$1 AND invocation_id=$2
`

type GetSteerQueueItemByInvocationParams struct {
	SessionID    pgtype.UUID `json:"session_id"`
	InvocationID string      `json:"invocation_id"`
}

func (q *Queries) GetSteerQueueItemByInvocation(ctx context.Context, arg GetSteerQueueItemByInvocationParams) (SessionSteerQueue, error) {
	row := q.db.QueryRow(ctx, getSteerQueueItemByInvocation, arg.SessionID, arg.InvocationID)
	var i SessionSteerQueue
	err := row.Scan(
		&i.ItemID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.TargetRunID,
		&i.InvocationID,
		&i.Payload,
		&i.Status,
		&i.Position,
		&i.ClaimRunID,
		&i.ClaimOwnerID,
		&i.ClaimFencingToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOwnerlessContinuationRuns = `-- name: ListOwnerlessContinuationRuns :many
SELECT run_id, team_id, bot_id, session_id, invocation_id, turn_id, turn_position, state, input_json, input_fingerprint, owner_id, fencing_token, owner_since, live_generation, source_follow_up_item_id, abort_requested_at, error_code, error_message, created_at, updated_at FROM session_runs WHERE team_id=public.memoh_current_team_id() AND state='accepted' AND owner_id IS NULL AND source_follow_up_item_id IS NOT NULL ORDER BY created_at,run_id LIMIT $1
`

func (q *Queries) ListOwnerlessContinuationRuns(ctx context.Context, batchSize int32) ([]SessionRun, error) {
	rows, err := q.db.Query(ctx, listOwnerlessContinuationRuns, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionRun
	for rows.Next() {
		var i SessionRun
		if err := rows.Scan(
			&i.RunID,
			&i.TeamID,
			&i.BotID,
			&i.SessionID,
			&i.InvocationID,
			&i.TurnID,
			&i.TurnPosition,
			&i.State,
			&i.InputJson,
			&i.InputFingerprint,
			&i.OwnerID,
			&i.FencingToken,
			&i.OwnerSince,
			&i.LiveGeneration,
			&i.SourceFollowUpItemID,
			&i.AbortRequestedAt,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingFollowUpQueue = `-- name: ListPendingFollowUpQueue :many
SELECT item_id, team_id, bot_id, session_id, enqueued_during_run_id, assigned_run_id, invocation_id, payload, status, position, claim_run_id, claim_owner_id, claim_fencing_token, created_at, updated_at FROM session_follow_up_queue WHERE team_id = public.memoh_current_team_id() AND session_id = $1 AND status = 'accepted' AND assigned_run_id IS NULL ORDER BY position, item_id
`

func (q *Queries) ListPendingFollowUpQueue(ctx context.Context, sessionID pgtype.UUID) ([]SessionFollowUpQueue, error) {
	rows, err := q.db.Query(ctx, listPendingFollowUpQueue, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionFollowUpQueue
	for rows.Next() {
		var i SessionFollowUpQueue
		if err := rows.Scan(
			&i.ItemID,
			&i.TeamID,
			&i.BotID,
			&i.SessionID,
			&i.EnqueuedDuringRunID,
			&i.AssignedRunID,
			&i.InvocationID,
			&i.Payload,
			&i.Status,
			&i.Position,
			&i.ClaimRunID,
			&i.ClaimOwnerID,
			&i.ClaimFencingToken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingSteerQueue = `-- name: ListPendingSteerQueue :many
SELECT item_id, team_id, bot_id, session_id, target_run_id, invocation_id, payload, status, position, claim_run_id, claim_owner_id, claim_fencing_token, created_at, updated_at FROM session_steer_queue WHERE team_id = public.memoh_current_team_id() AND session_id = $1 AND status = 'accepted' ORDER BY position, item_id
`

func (q *Queries) ListPendingSteerQueue(ctx context.Context, sessionID pgtype.UUID) ([]SessionSteerQueue, error) {
	rows, err := q.db.Query(ctx, listPendingSteerQueue, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionSteerQueue
	for rows.Next() {
		var i SessionSteerQueue
		if err := rows.Scan(
			&i.ItemID,
			&i.TeamID,
			&i.BotID,
			&i.SessionID,
			&i.TargetRunID,
			&i.InvocationID,
			&i.Payload,
			&i.Status,
			&i.Position,
			&i.ClaimRunID,
			&i.ClaimOwnerID,
			&i.ClaimFencingToken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSessionForQueueAdmission = `-- name: LockSessionForQueueAdmission :one
SELECT id FROM bot_sessions WHERE team_id=public.memoh_current_team_id() AND id=$1 AND bot_id=$2 AND deleted_at IS NULL FOR UPDATE
`

type LockSessionForQueueAdmissionParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	BotID     pgtype.UUID `json:"bot_id"`
}

func (q *Queries) LockSessionForQueueAdmission(ctx context.Context, arg LockSessionForQueueAdmissionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockSessionForQueueAdmission, arg.SessionID, arg.BotID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const lockSessionForQueueMutation = `-- name: LockSessionForQueueMutation :one
SELECT id FROM bot_sessions WHERE team_id=public.memoh_current_team_id() AND id=$1 AND deleted_at IS NULL FOR UPDATE
`

func (q *Queries) LockSessionForQueueMutation(ctx context.Context, sessionID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockSessionForQueueMutation, sessionID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const nextSessionQueueStepIndex = `-- name: NextSessionQueueStepIndex :one
SELECT COALESCE(MAX(step_index) + 1, 0)::BIGINT AS next_step_index
FROM session_queue_step_commits
WHERE team_id=public.memoh_current_team_id() AND run_id=$1
`

func (q *Queries) NextSessionQueueStepIndex(ctx context.Context, runID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, nextSessionQueueStepIndex, runID)
	var next_step_index int64
	err := row.Scan(&next_step_index)
	return next_step_index, err
}

const reclaimAssignedFollowUpQueueItem = `-- name: ReclaimAssignedFollowUpQueueItem :one
UPDATE session_follow_up_queue AS target SET claim_owner_id=$1, claim_fencing_token=$2, updated_at=now()
WHERE target.team_id=public.memoh_current_team_id() AND target.item_id=$3 AND target.assigned_run_id=$4 AND target.claim_run_id=$4 AND target.status='claimed'
  AND EXISTS (SELECT 1 FROM session_runs run WHERE run.team_id=public.memoh_current_team_id() AND run.run_id=$4 AND run.owner_id=$1 AND run.fencing_token=$2 AND run.state IN ('accepted','running','waiting_decision'))
RETURNING item_id, team_id, bot_id, session_id, enqueued_during_run_id, assigned_run_id, invocation_id, payload, status, position, claim_run_id, claim_owner_id, claim_fencing_token, created_at, updated_at
`

type ReclaimAssignedFollowUpQueueItemParams struct {
	ExecutionOwnerID      pgtype.Text `json:"execution_owner_id"`
	ExecutionFencingToken pgtype.Int8 `json:"execution_fencing_token"`
	QueueItemID           pgtype.UUID `json:"queue_item_id"`
	ExecutionRunID        pgtype.UUID `json:"execution_run_id"`
}

func (q *Queries) ReclaimAssignedFollowUpQueueItem(ctx context.Context, arg ReclaimAssignedFollowUpQueueItemParams) (SessionFollowUpQueue, error) {
	row := q.db.QueryRow(ctx, reclaimAssignedFollowUpQueueItem,
		arg.ExecutionOwnerID,
		arg.ExecutionFencingToken,
		arg.QueueItemID,
		arg.ExecutionRunID,
	)
	var i SessionFollowUpQueue
	err := row.Scan(
		&i.ItemID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.EnqueuedDuringRunID,
		&i.AssignedRunID,
		&i.InvocationID,
		&i.Payload,
		&i.Status,
		&i.Position,
		&i.ClaimRunID,
		&i.ClaimOwnerID,
		&i.ClaimFencingToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reclaimSteerQueueItem = `-- name: ReclaimSteerQueueItem :one
UPDATE session_steer_queue AS target SET claim_owner_id=$1, claim_fencing_token=$2, updated_at=now()
WHERE target.team_id=public.memoh_current_team_id() AND target.item_id=$3 AND target.target_run_id=$4 AND target.claim_run_id=$4 AND target.status='claimed'
  AND EXISTS (SELECT 1 FROM session_runs run WHERE run.team_id=public.memoh_current_team_id() AND run.run_id=$4 AND run.owner_id=$1 AND run.fencing_token=$2 AND run.state IN ('accepted','running','waiting_decision'))
RETURNING item_id, team_id, bot_id, session_id, target_run_id, invocation_id, payload, status, position, claim_run_id, claim_owner_id, claim_fencing_token, created_at, updated_at
`

type ReclaimSteerQueueItemParams struct {
	ExecutionOwnerID      pgtype.Text `json:"execution_owner_id"`
	ExecutionFencingToken pgtype.Int8 `json:"execution_fencing_token"`
	QueueItemID           pgtype.UUID `json:"queue_item_id"`
	ExecutionRunID        pgtype.UUID `json:"execution_run_id"`
}

func (q *Queries) ReclaimSteerQueueItem(ctx context.Context, arg ReclaimSteerQueueItemParams) (SessionSteerQueue, error) {
	row := q.db.QueryRow(ctx, reclaimSteerQueueItem,
		arg.ExecutionOwnerID,
		arg.ExecutionFencingToken,
		arg.QueueItemID,
		arg.ExecutionRunID,
	)
	var i SessionSteerQueue
	err := row.Scan(
		&i.ItemID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.TargetRunID,
		&i.InvocationID,
		&i.Payload,
		&i.Status,
		&i.Position,
		&i.ClaimRunID,
		&i.ClaimOwnerID,
		&i.ClaimFencingToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rejectFollowUpForContinuation = `-- name: RejectFollowUpForContinuation :exec
UPDATE session_follow_up_queue SET status='rejected', claim_run_id=NULL, claim_owner_id=NULL, claim_fencing_token=NULL, updated_at=now() WHERE team_id=public.memoh_current_team_id() AND assigned_run_id=$1 AND status IN ('accepted','claimed')
`

func (q *Queries) RejectFollowUpForContinuation(ctx context.Context, runID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, rejectFollowUpForContinuation, runID)
	return err
}

const rejectSteerItemsForRun = `-- name: RejectSteerItemsForRun :exec
UPDATE session_steer_queue SET status='rejected', claim_run_id=NULL, claim_owner_id=NULL, claim_fencing_token=NULL, updated_at=now() WHERE team_id=public.memoh_current_team_id() AND target_run_id=$1 AND status IN ('accepted','claimed')
`

func (q *Queries) RejectSteerItemsForRun(ctx context.Context, runID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, rejectSteerItemsForRun, runID)
	return err
}

const rejectUnassignedFollowUpsForRun = `-- name: RejectUnassignedFollowUpsForRun :exec
UPDATE session_follow_up_queue SET status='rejected', claim_run_id=NULL, claim_owner_id=NULL, claim_fencing_token=NULL, updated_at=now()
WHERE team_id=public.memoh_current_team_id() AND enqueued_during_run_id=$1 AND assigned_run_id IS NULL AND status IN ('accepted','claimed')
`

func (q *Queries) RejectUnassignedFollowUpsForRun(ctx context.Context, runID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, rejectUnassignedFollowUpsForRun, runID)
	return err
}

const rejectUnassignedFollowUpsForSession = `-- name: RejectUnassignedFollowUpsForSession :exec
UPDATE session_follow_up_queue SET status='rejected', claim_run_id=NULL, claim_owner_id=NULL, claim_fencing_token=NULL, updated_at=now()
WHERE team_id=public.memoh_current_team_id() AND session_id=$1 AND assigned_run_id IS NULL AND status IN ('accepted','claimed')
`

func (q *Queries) RejectUnassignedFollowUpsForSession(ctx context.Context, sessionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, rejectUnassignedFollowUpsForSession, sessionID)
	return err
}

const updateAcceptedFollowUpQueueItemPayload = `-- name: UpdateAcceptedFollowUpQueueItemPayload :one
UPDATE session_follow_up_queue SET payload=$1, updated_at=now()
WHERE team_id=public.memoh_current_team_id() AND session_id=$2
  AND item_id=$3 AND status='accepted' AND assigned_run_id IS NULL
RETURNING item_id, team_id, bot_id, session_id, enqueued_during_run_id, assigned_run_id, invocation_id, payload, status, position, claim_run_id, claim_owner_id, claim_fencing_token, created_at, updated_at
`

type UpdateAcceptedFollowUpQueueItemPayloadParams struct {
	Payload   []byte      `json:"payload"`
	SessionID pgtype.UUID `json:"session_id"`
	ItemID    pgtype.UUID `json:"item_id"`
}

func (q *Queries) UpdateAcceptedFollowUpQueueItemPayload(ctx context.Context, arg UpdateAcceptedFollowUpQueueItemPayloadParams) (SessionFollowUpQueue, error) {
	row := q.db.QueryRow(ctx, updateAcceptedFollowUpQueueItemPayload, arg.Payload, arg.SessionID, arg.ItemID)
	var i SessionFollowUpQueue
	err := row.Scan(
		&i.ItemID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.EnqueuedDuringRunID,
		&i.AssignedRunID,
		&i.InvocationID,
		&i.Payload,
		&i.Status,
		&i.Position,
		&i.ClaimRunID,
		&i.ClaimOwnerID,
		&i.ClaimFencingToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAcceptedFollowUpQueuePosition = `-- name: UpdateAcceptedFollowUpQueuePosition :execrows
UPDATE session_follow_up_queue SET position=$1, updated_at=now()
WHERE team_id=public.memoh_current_team_id() AND session_id=$2 AND item_id=$3 AND status='accepted' AND assigned_run_id IS NULL
`

type UpdateAcceptedFollowUpQueuePositionParams struct {
	Position  int64       `json:"position"`
	SessionID pgtype.UUID `json:"session_id"`
	ItemID    pgtype.UUID `json:"item_id"`
}

func (q *Queries) UpdateAcceptedFollowUpQueuePosition(ctx context.Context, arg UpdateAcceptedFollowUpQueuePositionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAcceptedFollowUpQueuePosition, arg.Position, arg.SessionID, arg.ItemID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAcceptedSteerQueueItemPayload = `-- name: UpdateAcceptedSteerQueueItemPayload :one
UPDATE session_steer_queue SET payload=$1, updated_at=now()
WHERE team_id=public.memoh_current_team_id() AND session_id=$2
  AND item_id=$3 AND status='accepted'
RETURNING item_id, team_id, bot_id, session_id, target_run_id, invocation_id, payload, status, position, claim_run_id, claim_owner_id, claim_fencing_token, created_at, updated_at
`

type UpdateAcceptedSteerQueueItemPayloadParams struct {
	Payload   []byte      `json:"payload"`
	SessionID pgtype.UUID `json:"session_id"`
	ItemID    pgtype.UUID `json:"item_id"`
}

func (q *Queries) UpdateAcceptedSteerQueueItemPayload(ctx context.Context, arg UpdateAcceptedSteerQueueItemPayloadParams) (SessionSteerQueue, error) {
	row := q.db.QueryRow(ctx, updateAcceptedSteerQueueItemPayload, arg.Payload, arg.SessionID, arg.ItemID)
	var i SessionSteerQueue
	err := row.Scan(
		&i.ItemID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.TargetRunID,
		&i.InvocationID,
		&i.Payload,
		&i.Status,
		&i.Position,
		&i.ClaimRunID,
		&i.ClaimOwnerID,
		&i.ClaimFencingToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAcceptedSteerQueuePosition = `-- name: UpdateAcceptedSteerQueuePosition :execrows
UPDATE session_steer_queue SET position=$1, updated_at=now()
WHERE team_id=public.memoh_current_team_id() AND session_id=$2 AND item_id=$3 AND status='accepted'
`

type UpdateAcceptedSteerQueuePositionParams struct {
	Position  int64       `json:"position"`
	SessionID pgtype.UUID `json:"session_id"`
	ItemID    pgtype.UUID `json:"item_id"`
}

func (q *Queries) UpdateAcceptedSteerQueuePosition(ctx context.Context, arg UpdateAcceptedSteerQueuePositionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAcceptedSteerQueuePosition, arg.Position, arg.SessionID, arg.ItemID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
