// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_runtime_resets.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireLockedBotRuntimeReset = `-- name: AcquireLockedBotRuntimeReset :one
UPDATE bots bot
SET runtime_reset_token = $1,
    runtime_reset_expires_at = clock_timestamp()
      + $2::bigint * interval '1 millisecond'
WHERE bot.team_id = public.memoh_current_team_id()
  AND bot.id = $3
  AND (
    bot.runtime_reset_token = $1
    OR bot.runtime_reset_expires_at IS NULL
    OR bot.runtime_reset_expires_at <= clock_timestamp()
  )
  AND NOT EXISTS (
    SELECT 1
    FROM bot_sessions session
    WHERE session.team_id = public.memoh_current_team_id()
      AND session.bot_id = bot.id
      AND session.runtime_reset_expires_at > clock_timestamp()
  )
RETURNING runtime_reset_expires_at
`

type AcquireLockedBotRuntimeResetParams struct {
	ResetToken        pgtype.UUID `json:"reset_token"`
	LeaseMilliseconds int64       `json:"lease_milliseconds"`
	BotID             pgtype.UUID `json:"bot_id"`
}

func (q *Queries) AcquireLockedBotRuntimeReset(ctx context.Context, arg AcquireLockedBotRuntimeResetParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, acquireLockedBotRuntimeReset, arg.ResetToken, arg.LeaseMilliseconds, arg.BotID)
	var runtime_reset_expires_at pgtype.Timestamptz
	err := row.Scan(&runtime_reset_expires_at)
	return runtime_reset_expires_at, err
}

const acquireLockedBotSessionRuntimeReset = `-- name: AcquireLockedBotSessionRuntimeReset :one
UPDATE bot_sessions session
SET runtime_reset_token = $1,
    runtime_reset_expires_at = clock_timestamp()
      + $2::bigint * interval '1 millisecond'
WHERE session.team_id = public.memoh_current_team_id()
  AND session.id = $3
  AND session.bot_id = $4
  AND session.deleted_at IS NULL
  AND NOT EXISTS (
    SELECT 1
    FROM bots bot
    WHERE bot.team_id = public.memoh_current_team_id()
      AND bot.id = $4
      AND bot.runtime_reset_expires_at > clock_timestamp()
  )
  AND (
    session.runtime_reset_token = $1
    OR session.runtime_reset_expires_at IS NULL
    OR session.runtime_reset_expires_at <= clock_timestamp()
  )
RETURNING session.runtime_reset_expires_at
`

type AcquireLockedBotSessionRuntimeResetParams struct {
	ResetToken        pgtype.UUID `json:"reset_token"`
	LeaseMilliseconds int64       `json:"lease_milliseconds"`
	SessionID         pgtype.UUID `json:"session_id"`
	BotID             pgtype.UUID `json:"bot_id"`
}

func (q *Queries) AcquireLockedBotSessionRuntimeReset(ctx context.Context, arg AcquireLockedBotSessionRuntimeResetParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, acquireLockedBotSessionRuntimeReset,
		arg.ResetToken,
		arg.LeaseMilliseconds,
		arg.SessionID,
		arg.BotID,
	)
	var runtime_reset_expires_at pgtype.Timestamptz
	err := row.Scan(&runtime_reset_expires_at)
	return runtime_reset_expires_at, err
}

const getBotRuntimeReset = `-- name: GetBotRuntimeReset :one
SELECT runtime_reset_token, runtime_reset_expires_at
FROM bots
WHERE team_id = public.memoh_current_team_id()
  AND id = $1
  AND runtime_reset_token IS NOT NULL
  AND runtime_reset_expires_at > clock_timestamp()
`

type GetBotRuntimeResetRow struct {
	RuntimeResetToken     pgtype.UUID        `json:"runtime_reset_token"`
	RuntimeResetExpiresAt pgtype.Timestamptz `json:"runtime_reset_expires_at"`
}

func (q *Queries) GetBotRuntimeReset(ctx context.Context, botID pgtype.UUID) (GetBotRuntimeResetRow, error) {
	row := q.db.QueryRow(ctx, getBotRuntimeReset, botID)
	var i GetBotRuntimeResetRow
	err := row.Scan(&i.RuntimeResetToken, &i.RuntimeResetExpiresAt)
	return i, err
}

const getEffectiveBotScopeRuntimeReset = `-- name: GetEffectiveBotScopeRuntimeReset :one
SELECT reset.scope, reset.session_id, reset.reset_token, reset.runtime_reset_expires_at
FROM (
  SELECT
    'bot'::text AS scope,
    NULL::uuid AS session_id,
    bot.runtime_reset_token AS reset_token,
    bot.runtime_reset_expires_at
  FROM bots bot
  WHERE bot.team_id = public.memoh_current_team_id()
    AND bot.id = $1
    AND bot.runtime_reset_token IS NOT NULL
    AND bot.runtime_reset_expires_at > clock_timestamp()
  UNION ALL
  SELECT
    'session'::text AS scope,
    session.id AS session_id,
    session.runtime_reset_token AS reset_token,
    session.runtime_reset_expires_at
  FROM bot_sessions session
  WHERE session.team_id = public.memoh_current_team_id()
    AND session.bot_id = $1
    AND session.runtime_reset_token IS NOT NULL
    AND session.runtime_reset_expires_at > clock_timestamp()
) reset
ORDER BY CASE reset.scope WHEN 'bot' THEN 0 ELSE 1 END, reset.session_id
LIMIT 1
`

type GetEffectiveBotScopeRuntimeResetRow struct {
	Scope                 string             `json:"scope"`
	SessionID             pgtype.UUID        `json:"session_id"`
	ResetToken            pgtype.UUID        `json:"reset_token"`
	RuntimeResetExpiresAt pgtype.Timestamptz `json:"runtime_reset_expires_at"`
}

// Mirrors effectiveResetLease in internal/agent/runtime/session/types.go: a
// bot-scope reader is blocked by the bot lease or by ANY active session lease
// of that bot, because a bot-wide operation must not proceed while one of the
// bot's sessions is mid-reset.
func (q *Queries) GetEffectiveBotScopeRuntimeReset(ctx context.Context, botID pgtype.UUID) (GetEffectiveBotScopeRuntimeResetRow, error) {
	row := q.db.QueryRow(ctx, getEffectiveBotScopeRuntimeReset, botID)
	var i GetEffectiveBotScopeRuntimeResetRow
	err := row.Scan(
		&i.Scope,
		&i.SessionID,
		&i.ResetToken,
		&i.RuntimeResetExpiresAt,
	)
	return i, err
}

const getEffectiveSessionRuntimeReset = `-- name: GetEffectiveSessionRuntimeReset :one
SELECT reset.scope, reset.reset_token, reset.runtime_reset_expires_at
FROM (
  SELECT
    'bot'::text AS scope,
    bot.runtime_reset_token AS reset_token,
    bot.runtime_reset_expires_at
  FROM bots bot
  WHERE bot.team_id = public.memoh_current_team_id()
    AND bot.id = $1
    AND bot.runtime_reset_token IS NOT NULL
    AND bot.runtime_reset_expires_at > clock_timestamp()
  UNION ALL
  SELECT
    'session'::text AS scope,
    session.runtime_reset_token AS reset_token,
    session.runtime_reset_expires_at
  FROM bot_sessions session
  WHERE session.team_id = public.memoh_current_team_id()
    AND session.bot_id = $1
    AND session.id = $2
    AND session.runtime_reset_token IS NOT NULL
    AND session.runtime_reset_expires_at > clock_timestamp()
) reset
ORDER BY CASE reset.scope WHEN 'bot' THEN 0 ELSE 1 END
LIMIT 1
`

type GetEffectiveSessionRuntimeResetParams struct {
	BotID     pgtype.UUID `json:"bot_id"`
	SessionID pgtype.UUID `json:"session_id"`
}

type GetEffectiveSessionRuntimeResetRow struct {
	Scope                 string             `json:"scope"`
	ResetToken            pgtype.UUID        `json:"reset_token"`
	RuntimeResetExpiresAt pgtype.Timestamptz `json:"runtime_reset_expires_at"`
}

func (q *Queries) GetEffectiveSessionRuntimeReset(ctx context.Context, arg GetEffectiveSessionRuntimeResetParams) (GetEffectiveSessionRuntimeResetRow, error) {
	row := q.db.QueryRow(ctx, getEffectiveSessionRuntimeReset, arg.BotID, arg.SessionID)
	var i GetEffectiveSessionRuntimeResetRow
	err := row.Scan(&i.Scope, &i.ResetToken, &i.RuntimeResetExpiresAt)
	return i, err
}

const lockBotForRuntimeReset = `-- name: LockBotForRuntimeReset :one
SELECT id
FROM bots
WHERE team_id = public.memoh_current_team_id()
  AND id = $1
FOR UPDATE
`

// This is intentionally a separate statement from acquisition. Under READ
// COMMITTED, a contender that waited here gets a fresh statement snapshot for
// the child/gate check below after the parent owner commits.
func (q *Queries) LockBotForRuntimeReset(ctx context.Context, botID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockBotForRuntimeReset, botID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const refreshLockedBotRuntimeReset = `-- name: RefreshLockedBotRuntimeReset :one
UPDATE bots
SET runtime_reset_expires_at = clock_timestamp()
      + $1::bigint * interval '1 millisecond'
WHERE team_id = public.memoh_current_team_id()
  AND id = $2
  AND runtime_reset_token = $3
RETURNING runtime_reset_expires_at
`

type RefreshLockedBotRuntimeResetParams struct {
	LeaseMilliseconds int64       `json:"lease_milliseconds"`
	BotID             pgtype.UUID `json:"bot_id"`
	ResetToken        pgtype.UUID `json:"reset_token"`
}

// The caller holds the bot parent lock and validated this token before a
// potentially long protected mutation. Token-only CAS may refresh an expiry
// that elapsed while that same transaction prevented every successor.
func (q *Queries) RefreshLockedBotRuntimeReset(ctx context.Context, arg RefreshLockedBotRuntimeResetParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, refreshLockedBotRuntimeReset, arg.LeaseMilliseconds, arg.BotID, arg.ResetToken)
	var runtime_reset_expires_at pgtype.Timestamptz
	err := row.Scan(&runtime_reset_expires_at)
	return runtime_reset_expires_at, err
}

const refreshLockedBotSessionRuntimeReset = `-- name: RefreshLockedBotSessionRuntimeReset :one
UPDATE bot_sessions
SET runtime_reset_expires_at = clock_timestamp()
      + $1::bigint * interval '1 millisecond'
WHERE team_id = public.memoh_current_team_id()
  AND id = $2
  AND bot_id = $3
  AND runtime_reset_token = $4
RETURNING runtime_reset_expires_at
`

type RefreshLockedBotSessionRuntimeResetParams struct {
	LeaseMilliseconds int64       `json:"lease_milliseconds"`
	SessionID         pgtype.UUID `json:"session_id"`
	BotID             pgtype.UUID `json:"bot_id"`
	ResetToken        pgtype.UUID `json:"reset_token"`
}

func (q *Queries) RefreshLockedBotSessionRuntimeReset(ctx context.Context, arg RefreshLockedBotSessionRuntimeResetParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, refreshLockedBotSessionRuntimeReset,
		arg.LeaseMilliseconds,
		arg.SessionID,
		arg.BotID,
		arg.ResetToken,
	)
	var runtime_reset_expires_at pgtype.Timestamptz
	err := row.Scan(&runtime_reset_expires_at)
	return runtime_reset_expires_at, err
}

const releaseBotRuntimeReset = `-- name: ReleaseBotRuntimeReset :one
UPDATE bots
SET runtime_reset_token = NULL,
    runtime_reset_expires_at = NULL
WHERE team_id = public.memoh_current_team_id()
  AND id = $1
  AND runtime_reset_token = $2
RETURNING id
`

type ReleaseBotRuntimeResetParams struct {
	BotID      pgtype.UUID `json:"bot_id"`
	ResetToken pgtype.UUID `json:"reset_token"`
}

func (q *Queries) ReleaseBotRuntimeReset(ctx context.Context, arg ReleaseBotRuntimeResetParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, releaseBotRuntimeReset, arg.BotID, arg.ResetToken)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const releaseBotSessionRuntimeReset = `-- name: ReleaseBotSessionRuntimeReset :one
UPDATE bot_sessions
SET runtime_reset_token = NULL,
    runtime_reset_expires_at = NULL
WHERE team_id = public.memoh_current_team_id()
  AND id = $1
  AND bot_id = $2
  AND runtime_reset_token = $3
RETURNING id
`

type ReleaseBotSessionRuntimeResetParams struct {
	SessionID  pgtype.UUID `json:"session_id"`
	BotID      pgtype.UUID `json:"bot_id"`
	ResetToken pgtype.UUID `json:"reset_token"`
}

func (q *Queries) ReleaseBotSessionRuntimeReset(ctx context.Context, arg ReleaseBotSessionRuntimeResetParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, releaseBotSessionRuntimeReset, arg.SessionID, arg.BotID, arg.ResetToken)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const renewBotRuntimeReset = `-- name: RenewBotRuntimeReset :one
UPDATE bots target
SET runtime_reset_expires_at = clock_timestamp()
      + $1::bigint * interval '1 millisecond'
WHERE target.team_id = public.memoh_current_team_id()
  AND target.id = $2
  AND target.runtime_reset_token = $3
  AND target.runtime_reset_expires_at > clock_timestamp()
  AND NOT EXISTS (
    SELECT 1
    FROM bot_sessions session
    WHERE session.team_id = public.memoh_current_team_id()
      AND session.bot_id = $2
      AND session.runtime_reset_expires_at > clock_timestamp()
  )
RETURNING target.runtime_reset_expires_at
`

type RenewBotRuntimeResetParams struct {
	LeaseMilliseconds int64       `json:"lease_milliseconds"`
	BotID             pgtype.UUID `json:"bot_id"`
	ResetToken        pgtype.UUID `json:"reset_token"`
}

func (q *Queries) RenewBotRuntimeReset(ctx context.Context, arg RenewBotRuntimeResetParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, renewBotRuntimeReset, arg.LeaseMilliseconds, arg.BotID, arg.ResetToken)
	var runtime_reset_expires_at pgtype.Timestamptz
	err := row.Scan(&runtime_reset_expires_at)
	return runtime_reset_expires_at, err
}

const renewBotSessionRuntimeReset = `-- name: RenewBotSessionRuntimeReset :one
UPDATE bot_sessions target
SET runtime_reset_expires_at = clock_timestamp()
      + $1::bigint * interval '1 millisecond'
WHERE target.team_id = public.memoh_current_team_id()
  AND target.id = $2
  AND target.bot_id = $3
  AND target.runtime_reset_token = $4
  AND target.runtime_reset_expires_at > clock_timestamp()
  AND NOT EXISTS (
    SELECT 1
    FROM bots bot
    WHERE bot.team_id = public.memoh_current_team_id()
      AND bot.id = $3
      AND bot.runtime_reset_expires_at > clock_timestamp()
  )
RETURNING target.runtime_reset_expires_at
`

type RenewBotSessionRuntimeResetParams struct {
	LeaseMilliseconds int64       `json:"lease_milliseconds"`
	SessionID         pgtype.UUID `json:"session_id"`
	BotID             pgtype.UUID `json:"bot_id"`
	ResetToken        pgtype.UUID `json:"reset_token"`
}

func (q *Queries) RenewBotSessionRuntimeReset(ctx context.Context, arg RenewBotSessionRuntimeResetParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, renewBotSessionRuntimeReset,
		arg.LeaseMilliseconds,
		arg.SessionID,
		arg.BotID,
		arg.ResetToken,
	)
	var runtime_reset_expires_at pgtype.Timestamptz
	err := row.Scan(&runtime_reset_expires_at)
	return runtime_reset_expires_at, err
}

const sessionLiveForRuntimeReset = `-- name: SessionLiveForRuntimeReset :one
SELECT EXISTS (
  SELECT 1
  FROM bot_sessions session
  WHERE session.team_id = public.memoh_current_team_id()
    AND session.id = $1
    AND session.bot_id = $2
    AND session.deleted_at IS NULL
)::boolean AS live
`

type SessionLiveForRuntimeResetParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	BotID     pgtype.UUID `json:"bot_id"`
}

// Distinguishes "session reset lease is blocked" from "session no longer
// exists": an acquire loop must retry the former and fail fast on the latter.
func (q *Queries) SessionLiveForRuntimeReset(ctx context.Context, arg SessionLiveForRuntimeResetParams) (bool, error) {
	row := q.db.QueryRow(ctx, sessionLiveForRuntimeReset, arg.SessionID, arg.BotID)
	var live bool
	err := row.Scan(&live)
	return live, err
}

const validateLockedBotRuntimeReset = `-- name: ValidateLockedBotRuntimeReset :one
SELECT id
FROM bots
WHERE team_id = public.memoh_current_team_id()
  AND id = $1
  AND runtime_reset_token = $2
  AND runtime_reset_expires_at > clock_timestamp()
`

type ValidateLockedBotRuntimeResetParams struct {
	BotID      pgtype.UUID `json:"bot_id"`
	ResetToken pgtype.UUID `json:"reset_token"`
}

func (q *Queries) ValidateLockedBotRuntimeReset(ctx context.Context, arg ValidateLockedBotRuntimeResetParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, validateLockedBotRuntimeReset, arg.BotID, arg.ResetToken)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const validateLockedBotSessionRuntimeReset = `-- name: ValidateLockedBotSessionRuntimeReset :one
SELECT session.id
FROM bot_sessions session
WHERE session.team_id = public.memoh_current_team_id()
  AND session.bot_id = $1
  AND session.id = $2
  AND session.runtime_reset_token = $3
  AND session.runtime_reset_expires_at > clock_timestamp()
FOR UPDATE OF session
`

type ValidateLockedBotSessionRuntimeResetParams struct {
	BotID      pgtype.UUID `json:"bot_id"`
	SessionID  pgtype.UUID `json:"session_id"`
	ResetToken pgtype.UUID `json:"reset_token"`
}

func (q *Queries) ValidateLockedBotSessionRuntimeReset(ctx context.Context, arg ValidateLockedBotSessionRuntimeResetParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, validateLockedBotSessionRuntimeReset, arg.BotID, arg.SessionID, arg.ResetToken)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
