// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: skill_packages.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBotSkillPackageInstallation = `-- name: DeleteBotSkillPackageInstallation :one
DELETE FROM bot_skill_package_installations
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND id = $2
RETURNING id, team_id, bot_id, workspace_target_id, registry_id, package_id,
          revision, installed_at, updated_at
`

type DeleteBotSkillPackageInstallationParams struct {
	BotID pgtype.UUID `json:"bot_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteBotSkillPackageInstallation(ctx context.Context, arg DeleteBotSkillPackageInstallationParams) (BotSkillPackageInstallation, error) {
	row := q.db.QueryRow(ctx, deleteBotSkillPackageInstallation, arg.BotID, arg.ID)
	var i BotSkillPackageInstallation
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BotID,
		&i.WorkspaceTargetID,
		&i.RegistryID,
		&i.PackageID,
		&i.Revision,
		&i.InstalledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBotSkillPackageInstallation = `-- name: GetBotSkillPackageInstallation :one
SELECT id, team_id, bot_id, workspace_target_id, registry_id, package_id,
       revision, installed_at, updated_at
FROM bot_skill_package_installations
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND workspace_target_id = $2
  AND registry_id = $3
  AND package_id = $4
LIMIT 1
`

type GetBotSkillPackageInstallationParams struct {
	BotID             pgtype.UUID `json:"bot_id"`
	WorkspaceTargetID string      `json:"workspace_target_id"`
	RegistryID        string      `json:"registry_id"`
	PackageID         string      `json:"package_id"`
}

func (q *Queries) GetBotSkillPackageInstallation(ctx context.Context, arg GetBotSkillPackageInstallationParams) (BotSkillPackageInstallation, error) {
	row := q.db.QueryRow(ctx, getBotSkillPackageInstallation,
		arg.BotID,
		arg.WorkspaceTargetID,
		arg.RegistryID,
		arg.PackageID,
	)
	var i BotSkillPackageInstallation
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BotID,
		&i.WorkspaceTargetID,
		&i.RegistryID,
		&i.PackageID,
		&i.Revision,
		&i.InstalledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBotSkillPackageInstallationByID = `-- name: GetBotSkillPackageInstallationByID :one
SELECT id, team_id, bot_id, workspace_target_id, registry_id, package_id,
       revision, installed_at, updated_at
FROM bot_skill_package_installations
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND id = $2
LIMIT 1
`

type GetBotSkillPackageInstallationByIDParams struct {
	BotID pgtype.UUID `json:"bot_id"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) GetBotSkillPackageInstallationByID(ctx context.Context, arg GetBotSkillPackageInstallationByIDParams) (BotSkillPackageInstallation, error) {
	row := q.db.QueryRow(ctx, getBotSkillPackageInstallationByID, arg.BotID, arg.ID)
	var i BotSkillPackageInstallation
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BotID,
		&i.WorkspaceTargetID,
		&i.RegistryID,
		&i.PackageID,
		&i.Revision,
		&i.InstalledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBotSkillPackageInstallations = `-- name: ListBotSkillPackageInstallations :many
SELECT id, team_id, bot_id, workspace_target_id, registry_id, package_id,
       revision, installed_at, updated_at
FROM bot_skill_package_installations
WHERE team_id = public.memoh_current_team_id() AND bot_id = $1
ORDER BY registry_id, package_id, workspace_target_id
`

func (q *Queries) ListBotSkillPackageInstallations(ctx context.Context, botID pgtype.UUID) ([]BotSkillPackageInstallation, error) {
	rows, err := q.db.Query(ctx, listBotSkillPackageInstallations, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotSkillPackageInstallation
	for rows.Next() {
		var i BotSkillPackageInstallation
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.BotID,
			&i.WorkspaceTargetID,
			&i.RegistryID,
			&i.PackageID,
			&i.Revision,
			&i.InstalledAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBotSkillPackageInstallation = `-- name: UpsertBotSkillPackageInstallation :one
INSERT INTO bot_skill_package_installations (
  bot_id, workspace_target_id, registry_id, package_id, revision
)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (team_id, bot_id, workspace_target_id, registry_id, package_id)
DO UPDATE SET revision = EXCLUDED.revision,
              updated_at = now()
RETURNING id, team_id, bot_id, workspace_target_id, registry_id, package_id,
          revision, installed_at, updated_at
`

type UpsertBotSkillPackageInstallationParams struct {
	BotID             pgtype.UUID `json:"bot_id"`
	WorkspaceTargetID string      `json:"workspace_target_id"`
	RegistryID        string      `json:"registry_id"`
	PackageID         string      `json:"package_id"`
	Revision          string      `json:"revision"`
}

func (q *Queries) UpsertBotSkillPackageInstallation(ctx context.Context, arg UpsertBotSkillPackageInstallationParams) (BotSkillPackageInstallation, error) {
	row := q.db.QueryRow(ctx, upsertBotSkillPackageInstallation,
		arg.BotID,
		arg.WorkspaceTargetID,
		arg.RegistryID,
		arg.PackageID,
		arg.Revision,
	)
	var i BotSkillPackageInstallation
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BotID,
		&i.WorkspaceTargetID,
		&i.RegistryID,
		&i.PackageID,
		&i.Revision,
		&i.InstalledAt,
		&i.UpdatedAt,
	)
	return i, err
}
