// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace_dependencies.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimBotDependencyOperation = `-- name: ClaimBotDependencyOperation :one
WITH target_lock AS MATERIALIZED (
  SELECT d.desired_revision FROM bot_dependency_desired_installations d
  WHERE d.team_id = public.memoh_current_team_id() AND d.bot_id = $1 AND d.dependency_id = $2
  FOR UPDATE
), target_lock_count AS MATERIALIZED (
  SELECT count(*) FROM target_lock
), claimed AS (
INSERT INTO bot_dependency_installations (
  bot_id, dependency_id, source, status,
  installed_version, manifest_digest, source_url, registry_id, definition_revision, operation_id, operation_source_url, operation_registry_id, operation_definition_revision, operation_intent
)
VALUES ((SELECT $1::uuid FROM target_lock_count), $2, $3, $4, $5, $6, $7, $8, $9, $10, $7, $8, $9, $11::jsonb)
ON CONFLICT (team_id, bot_id, dependency_id)
DO UPDATE SET status = EXCLUDED.status,
              last_error = '',
              operation_id = EXCLUDED.operation_id,
              operation_source_url = EXCLUDED.operation_source_url,
              operation_registry_id = EXCLUDED.operation_registry_id,
              operation_definition_revision = EXCLUDED.operation_definition_revision,
              operation_intent = EXCLUDED.operation_intent,
              updated_at = now()
WHERE bot_dependency_installations.status NOT IN ('installing', 'updating', 'removing')
RETURNING id, team_id, bot_id, dependency_id, source, status,
          installed_version, latest_version, last_checked_at, last_error,
          manifest_digest, source_url, registry_id, definition_revision, operation_id, last_operation_id, operation_source_url, operation_registry_id, operation_definition_revision, operation_intent, created_at, updated_at
), invalidated AS (
  UPDATE bot_dependency_desired_installations d
  SET desired_revision = c.operation_id, repair_status = 'ready', repair_operation_id = '',
      repair_attempts = 0, repair_next_attempt_at = NULL, repair_last_error_code = '', updated_at = now()
  FROM claimed c
  WHERE d.team_id = c.team_id AND d.bot_id = c.bot_id AND d.dependency_id = c.dependency_id AND c.status <> 'removing'
  RETURNING d.bot_id
), revoked AS (
  DELETE FROM bot_dependency_desired_installations d USING claimed c
  WHERE d.team_id = c.team_id AND d.bot_id = c.bot_id AND d.dependency_id = c.dependency_id AND c.status = 'removing'
  RETURNING d.team_id, d.bot_id, d.dependency_id, d.desired_revision, d.version, d.source_url, d.registry_id, d.definition_revision, d.manifest_digest, d.authorized_at, d.authorized_by_operation_id, d.authorized_by_actor, d.platform_os, d.platform_arch, d.platform_libc, d.entrypoints, d.installation_id, d.payload_path, d.store_root, d.repair_status, d.repair_operation_id, d.repair_attempts, d.repair_next_attempt_at, d.repair_last_error_code, d.created_at, d.updated_at
), audited AS (
  INSERT INTO bot_dependency_authorization_events (bot_id, dependency_id, operation_id, action, actor, version, source_url, registry_id, definition_revision, manifest_digest)
  SELECT r.bot_id, r.dependency_id, c.operation_id, 'revoke', $12::text, r.version, r.source_url, r.registry_id, r.definition_revision, r.manifest_digest
  FROM revoked r JOIN claimed c ON r.bot_id = c.bot_id AND r.dependency_id = c.dependency_id
  ON CONFLICT DO NOTHING
)
SELECT id, team_id, bot_id, dependency_id, source, status, installed_version, latest_version, last_checked_at, last_error, manifest_digest, source_url, registry_id, definition_revision, operation_id, last_operation_id, operation_source_url, operation_registry_id, operation_definition_revision, operation_intent, created_at, updated_at FROM claimed
`

type ClaimBotDependencyOperationParams struct {
	BotID              pgtype.UUID `json:"bot_id"`
	DependencyID       string      `json:"dependency_id"`
	Source             string      `json:"source"`
	Status             string      `json:"status"`
	InstalledVersion   string      `json:"installed_version"`
	ManifestDigest     string      `json:"manifest_digest"`
	SourceUrl          string      `json:"source_url"`
	RegistryID         string      `json:"registry_id"`
	DefinitionRevision string      `json:"definition_revision"`
	OperationID        string      `json:"operation_id"`
	OperationIntent    []byte      `json:"operation_intent"`
	Actor              string      `json:"actor"`
}

type ClaimBotDependencyOperationRow struct {
	ID                          pgtype.UUID        `json:"id"`
	TeamID                      pgtype.UUID        `json:"team_id"`
	BotID                       pgtype.UUID        `json:"bot_id"`
	DependencyID                string             `json:"dependency_id"`
	Source                      string             `json:"source"`
	Status                      string             `json:"status"`
	InstalledVersion            string             `json:"installed_version"`
	LatestVersion               string             `json:"latest_version"`
	LastCheckedAt               pgtype.Timestamptz `json:"last_checked_at"`
	LastError                   string             `json:"last_error"`
	ManifestDigest              string             `json:"manifest_digest"`
	SourceUrl                   string             `json:"source_url"`
	RegistryID                  string             `json:"registry_id"`
	DefinitionRevision          string             `json:"definition_revision"`
	OperationID                 string             `json:"operation_id"`
	LastOperationID             string             `json:"last_operation_id"`
	OperationSourceUrl          string             `json:"operation_source_url"`
	OperationRegistryID         string             `json:"operation_registry_id"`
	OperationDefinitionRevision string             `json:"operation_definition_revision"`
	OperationIntent             []byte             `json:"operation_intent"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                   pgtype.Timestamptz `json:"updated_at"`
}

// All claims and successful finishes lock desired before installation. The
// aggregate preserves one input row when no target has been authorized yet.
func (q *Queries) ClaimBotDependencyOperation(ctx context.Context, arg ClaimBotDependencyOperationParams) (ClaimBotDependencyOperationRow, error) {
	row := q.db.QueryRow(ctx, claimBotDependencyOperation,
		arg.BotID,
		arg.DependencyID,
		arg.Source,
		arg.Status,
		arg.InstalledVersion,
		arg.ManifestDigest,
		arg.SourceUrl,
		arg.RegistryID,
		arg.DefinitionRevision,
		arg.OperationID,
		arg.OperationIntent,
		arg.Actor,
	)
	var i ClaimBotDependencyOperationRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BotID,
		&i.DependencyID,
		&i.Source,
		&i.Status,
		&i.InstalledVersion,
		&i.LatestVersion,
		&i.LastCheckedAt,
		&i.LastError,
		&i.ManifestDigest,
		&i.SourceUrl,
		&i.RegistryID,
		&i.DefinitionRevision,
		&i.OperationID,
		&i.LastOperationID,
		&i.OperationSourceUrl,
		&i.OperationRegistryID,
		&i.OperationDefinitionRevision,
		&i.OperationIntent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBotDependencyInstallation = `-- name: DeleteBotDependencyInstallation :execrows
DELETE FROM bot_dependency_installations
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND dependency_id = $2
  AND operation_id = ''
`

type DeleteBotDependencyInstallationParams struct {
	BotID        pgtype.UUID `json:"bot_id"`
	DependencyID string      `json:"dependency_id"`
}

func (q *Queries) DeleteBotDependencyInstallation(ctx context.Context, arg DeleteBotDependencyInstallationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBotDependencyInstallation, arg.BotID, arg.DependencyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteBotDependencyOperation = `-- name: DeleteBotDependencyOperation :one
DELETE FROM bot_dependency_installations
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND dependency_id = $2
  AND operation_id = $3 AND operation_id <> ''
RETURNING id, team_id, bot_id, dependency_id, source, status,
          installed_version, latest_version, last_checked_at, last_error,
          manifest_digest, source_url, registry_id, definition_revision, operation_id, last_operation_id, operation_source_url, operation_registry_id, operation_definition_revision, operation_intent, created_at, updated_at
`

type DeleteBotDependencyOperationParams struct {
	BotID        pgtype.UUID `json:"bot_id"`
	DependencyID string      `json:"dependency_id"`
	OperationID  string      `json:"operation_id"`
}

func (q *Queries) DeleteBotDependencyOperation(ctx context.Context, arg DeleteBotDependencyOperationParams) (BotDependencyInstallation, error) {
	row := q.db.QueryRow(ctx, deleteBotDependencyOperation, arg.BotID, arg.DependencyID, arg.OperationID)
	var i BotDependencyInstallation
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BotID,
		&i.DependencyID,
		&i.Source,
		&i.Status,
		&i.InstalledVersion,
		&i.LatestVersion,
		&i.LastCheckedAt,
		&i.LastError,
		&i.ManifestDigest,
		&i.SourceUrl,
		&i.RegistryID,
		&i.DefinitionRevision,
		&i.OperationID,
		&i.LastOperationID,
		&i.OperationSourceUrl,
		&i.OperationRegistryID,
		&i.OperationDefinitionRevision,
		&i.OperationIntent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const enrollLegacyDependencyOperationEpoch = `-- name: EnrollLegacyDependencyOperationEpoch :one
UPDATE bot_dependency_installations
SET operation_intent = CASE
    WHEN COALESCE(operation_intent ->> 'control_migration_epoch', '') <> '' THEN operation_intent
    ELSE COALESCE(operation_intent, '{}'::jsonb) || jsonb_build_object('control_migration_epoch', $1::text)
END
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $2 AND dependency_id = $3
  AND operation_id = $4
  AND status IN ('installing', 'updating', 'removing')
RETURNING COALESCE(operation_intent ->> 'control_migration_epoch', '')::text AS epoch
`

type EnrollLegacyDependencyOperationEpochParams struct {
	Epoch        string      `json:"epoch"`
	BotID        pgtype.UUID `json:"bot_id"`
	DependencyID string      `json:"dependency_id"`
	OperationID  string      `json:"operation_id"`
}

// The first observation is a lifetime fence, not a heartbeat or new approval.
// Preserve it across Server restarts and do not change stale-operation timing.
func (q *Queries) EnrollLegacyDependencyOperationEpoch(ctx context.Context, arg EnrollLegacyDependencyOperationEpochParams) (string, error) {
	row := q.db.QueryRow(ctx, enrollLegacyDependencyOperationEpoch,
		arg.Epoch,
		arg.BotID,
		arg.DependencyID,
		arg.OperationID,
	)
	var epoch string
	err := row.Scan(&epoch)
	return epoch, err
}

const finishBotDependencyOperation = `-- name: FinishBotDependencyOperation :one
UPDATE bot_dependency_installations
SET source = $1,
    status = $2,
    installed_version = $3,
    latest_version = $4,
    last_checked_at = $5::timestamptz,
    last_error = $6,
    manifest_digest = $7,
    source_url = $8,
    registry_id = $9,
    definition_revision = $10,
    last_operation_id = operation_id, operation_id = '',
    operation_source_url = '', operation_registry_id = '', operation_definition_revision = '', operation_intent = NULL,
    updated_at = now()
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $11
  AND dependency_id = $12
  AND operation_id = $13 AND operation_id <> ''
RETURNING id, team_id, bot_id, dependency_id, source, status,
          installed_version, latest_version, last_checked_at, last_error,
          manifest_digest, source_url, registry_id, definition_revision, operation_id, last_operation_id, operation_source_url, operation_registry_id, operation_definition_revision, operation_intent, created_at, updated_at
`

type FinishBotDependencyOperationParams struct {
	Source             string             `json:"source"`
	Status             string             `json:"status"`
	InstalledVersion   string             `json:"installed_version"`
	LatestVersion      string             `json:"latest_version"`
	LastCheckedAt      pgtype.Timestamptz `json:"last_checked_at"`
	LastError          string             `json:"last_error"`
	ManifestDigest     string             `json:"manifest_digest"`
	SourceUrl          string             `json:"source_url"`
	RegistryID         string             `json:"registry_id"`
	DefinitionRevision string             `json:"definition_revision"`
	BotID              pgtype.UUID        `json:"bot_id"`
	DependencyID       string             `json:"dependency_id"`
	OperationID        string             `json:"operation_id"`
}

func (q *Queries) FinishBotDependencyOperation(ctx context.Context, arg FinishBotDependencyOperationParams) (BotDependencyInstallation, error) {
	row := q.db.QueryRow(ctx, finishBotDependencyOperation,
		arg.Source,
		arg.Status,
		arg.InstalledVersion,
		arg.LatestVersion,
		arg.LastCheckedAt,
		arg.LastError,
		arg.ManifestDigest,
		arg.SourceUrl,
		arg.RegistryID,
		arg.DefinitionRevision,
		arg.BotID,
		arg.DependencyID,
		arg.OperationID,
	)
	var i BotDependencyInstallation
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BotID,
		&i.DependencyID,
		&i.Source,
		&i.Status,
		&i.InstalledVersion,
		&i.LatestVersion,
		&i.LastCheckedAt,
		&i.LastError,
		&i.ManifestDigest,
		&i.SourceUrl,
		&i.RegistryID,
		&i.DefinitionRevision,
		&i.OperationID,
		&i.LastOperationID,
		&i.OperationSourceUrl,
		&i.OperationRegistryID,
		&i.OperationDefinitionRevision,
		&i.OperationIntent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBotDependencyInstallation = `-- name: GetBotDependencyInstallation :one
SELECT id, team_id, bot_id, dependency_id, source, status,
       installed_version, latest_version, last_checked_at, last_error,
       manifest_digest, source_url, registry_id, definition_revision, operation_id, last_operation_id, operation_source_url, operation_registry_id, operation_definition_revision, operation_intent, created_at, updated_at
FROM bot_dependency_installations
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND dependency_id = $2
LIMIT 1
`

type GetBotDependencyInstallationParams struct {
	BotID        pgtype.UUID `json:"bot_id"`
	DependencyID string      `json:"dependency_id"`
}

func (q *Queries) GetBotDependencyInstallation(ctx context.Context, arg GetBotDependencyInstallationParams) (BotDependencyInstallation, error) {
	row := q.db.QueryRow(ctx, getBotDependencyInstallation, arg.BotID, arg.DependencyID)
	var i BotDependencyInstallation
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BotID,
		&i.DependencyID,
		&i.Source,
		&i.Status,
		&i.InstalledVersion,
		&i.LatestVersion,
		&i.LastCheckedAt,
		&i.LastError,
		&i.ManifestDigest,
		&i.SourceUrl,
		&i.RegistryID,
		&i.DefinitionRevision,
		&i.OperationID,
		&i.LastOperationID,
		&i.OperationSourceUrl,
		&i.OperationRegistryID,
		&i.OperationDefinitionRevision,
		&i.OperationIntent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBotDependencyInstallations = `-- name: ListBotDependencyInstallations :many
SELECT id, team_id, bot_id, dependency_id, source, status,
       installed_version, latest_version, last_checked_at, last_error,
       manifest_digest, source_url, registry_id, definition_revision, operation_id, last_operation_id, operation_source_url, operation_registry_id, operation_definition_revision, operation_intent, created_at, updated_at
FROM bot_dependency_installations
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
ORDER BY dependency_id
`

func (q *Queries) ListBotDependencyInstallations(ctx context.Context, botID pgtype.UUID) ([]BotDependencyInstallation, error) {
	rows, err := q.db.Query(ctx, listBotDependencyInstallations, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotDependencyInstallation
	for rows.Next() {
		var i BotDependencyInstallation
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.BotID,
			&i.DependencyID,
			&i.Source,
			&i.Status,
			&i.InstalledVersion,
			&i.LatestVersion,
			&i.LastCheckedAt,
			&i.LastError,
			&i.ManifestDigest,
			&i.SourceUrl,
			&i.RegistryID,
			&i.DefinitionRevision,
			&i.OperationID,
			&i.LastOperationID,
			&i.OperationSourceUrl,
			&i.OperationRegistryID,
			&i.OperationDefinitionRevision,
			&i.OperationIntent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBotDependencyInstallationsByStatus = `-- name: ListBotDependencyInstallationsByStatus :many
SELECT id, team_id, bot_id, dependency_id, source, status,
       installed_version, latest_version, last_checked_at, last_error,
       manifest_digest, source_url, registry_id, definition_revision, operation_id, last_operation_id, operation_source_url, operation_registry_id, operation_definition_revision, operation_intent, created_at, updated_at
FROM bot_dependency_installations
WHERE team_id = public.memoh_current_team_id()
  AND status = $1
ORDER BY bot_id, dependency_id
`

func (q *Queries) ListBotDependencyInstallationsByStatus(ctx context.Context, status string) ([]BotDependencyInstallation, error) {
	rows, err := q.db.Query(ctx, listBotDependencyInstallationsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotDependencyInstallation
	for rows.Next() {
		var i BotDependencyInstallation
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.BotID,
			&i.DependencyID,
			&i.Source,
			&i.Status,
			&i.InstalledVersion,
			&i.LatestVersion,
			&i.LastCheckedAt,
			&i.LastError,
			&i.ManifestDigest,
			&i.SourceUrl,
			&i.RegistryID,
			&i.DefinitionRevision,
			&i.OperationID,
			&i.LastOperationID,
			&i.OperationSourceUrl,
			&i.OperationRegistryID,
			&i.OperationDefinitionRevision,
			&i.OperationIntent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleBotDependencyOperations = `-- name: ListStaleBotDependencyOperations :many
SELECT id, team_id, bot_id, dependency_id, source, status,
       installed_version, latest_version, last_checked_at, last_error,
       manifest_digest, source_url, registry_id, definition_revision, operation_id, last_operation_id, operation_source_url, operation_registry_id, operation_definition_revision, operation_intent, created_at, updated_at
FROM bot_dependency_installations
WHERE team_id = public.memoh_current_team_id()
  AND status IN ('installing', 'updating', 'removing')
  AND updated_at < now() - make_interval(secs => $1::double precision)
ORDER BY updated_at, id
`

func (q *Queries) ListStaleBotDependencyOperations(ctx context.Context, olderThanSeconds float64) ([]BotDependencyInstallation, error) {
	rows, err := q.db.Query(ctx, listStaleBotDependencyOperations, olderThanSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotDependencyInstallation
	for rows.Next() {
		var i BotDependencyInstallation
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.BotID,
			&i.DependencyID,
			&i.Source,
			&i.Status,
			&i.InstalledVersion,
			&i.LatestVersion,
			&i.LastCheckedAt,
			&i.LastError,
			&i.ManifestDigest,
			&i.SourceUrl,
			&i.RegistryID,
			&i.DefinitionRevision,
			&i.OperationID,
			&i.LastOperationID,
			&i.OperationSourceUrl,
			&i.OperationRegistryID,
			&i.OperationDefinitionRevision,
			&i.OperationIntent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBotDependencyInstallationObserved = `-- name: UpdateBotDependencyInstallationObserved :one
UPDATE bot_dependency_installations
SET source = COALESCE($1::text, source),
    installed_version = COALESCE($2::text, installed_version),
    latest_version = COALESCE($3::text, latest_version),
    last_checked_at = COALESCE($4::timestamptz, last_checked_at),
    last_error = COALESCE($5::text, last_error),
    manifest_digest = COALESCE($6::text, manifest_digest),
    source_url = COALESCE($7::text, source_url),
    registry_id = COALESCE($8::text, registry_id),
    definition_revision = COALESCE($9::text, definition_revision),
    updated_at = now()
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $10
  AND dependency_id = $11
  AND operation_id = ''
RETURNING id, team_id, bot_id, dependency_id, source, status,
          installed_version, latest_version, last_checked_at, last_error,
          manifest_digest, source_url, registry_id, definition_revision, operation_id, last_operation_id, operation_source_url, operation_registry_id, operation_definition_revision, operation_intent, created_at, updated_at
`

type UpdateBotDependencyInstallationObservedParams struct {
	Source             pgtype.Text        `json:"source"`
	InstalledVersion   pgtype.Text        `json:"installed_version"`
	LatestVersion      pgtype.Text        `json:"latest_version"`
	LastCheckedAt      pgtype.Timestamptz `json:"last_checked_at"`
	LastError          pgtype.Text        `json:"last_error"`
	ManifestDigest     pgtype.Text        `json:"manifest_digest"`
	SourceUrl          pgtype.Text        `json:"source_url"`
	RegistryID         pgtype.Text        `json:"registry_id"`
	DefinitionRevision pgtype.Text        `json:"definition_revision"`
	BotID              pgtype.UUID        `json:"bot_id"`
	DependencyID       string             `json:"dependency_id"`
}

func (q *Queries) UpdateBotDependencyInstallationObserved(ctx context.Context, arg UpdateBotDependencyInstallationObservedParams) (BotDependencyInstallation, error) {
	row := q.db.QueryRow(ctx, updateBotDependencyInstallationObserved,
		arg.Source,
		arg.InstalledVersion,
		arg.LatestVersion,
		arg.LastCheckedAt,
		arg.LastError,
		arg.ManifestDigest,
		arg.SourceUrl,
		arg.RegistryID,
		arg.DefinitionRevision,
		arg.BotID,
		arg.DependencyID,
	)
	var i BotDependencyInstallation
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BotID,
		&i.DependencyID,
		&i.Source,
		&i.Status,
		&i.InstalledVersion,
		&i.LatestVersion,
		&i.LastCheckedAt,
		&i.LastError,
		&i.ManifestDigest,
		&i.SourceUrl,
		&i.RegistryID,
		&i.DefinitionRevision,
		&i.OperationID,
		&i.LastOperationID,
		&i.OperationSourceUrl,
		&i.OperationRegistryID,
		&i.OperationDefinitionRevision,
		&i.OperationIntent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBotDependencyInstallationStatus = `-- name: UpdateBotDependencyInstallationStatus :one
UPDATE bot_dependency_installations
SET status = $1,
    last_error = $2,
    updated_at = now()
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $3
  AND dependency_id = $4
  AND operation_id = ''
RETURNING id, team_id, bot_id, dependency_id, source, status,
          installed_version, latest_version, last_checked_at, last_error,
          manifest_digest, source_url, registry_id, definition_revision, operation_id, last_operation_id, operation_source_url, operation_registry_id, operation_definition_revision, operation_intent, created_at, updated_at
`

type UpdateBotDependencyInstallationStatusParams struct {
	Status       string      `json:"status"`
	LastError    string      `json:"last_error"`
	BotID        pgtype.UUID `json:"bot_id"`
	DependencyID string      `json:"dependency_id"`
}

func (q *Queries) UpdateBotDependencyInstallationStatus(ctx context.Context, arg UpdateBotDependencyInstallationStatusParams) (BotDependencyInstallation, error) {
	row := q.db.QueryRow(ctx, updateBotDependencyInstallationStatus,
		arg.Status,
		arg.LastError,
		arg.BotID,
		arg.DependencyID,
	)
	var i BotDependencyInstallation
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BotID,
		&i.DependencyID,
		&i.Source,
		&i.Status,
		&i.InstalledVersion,
		&i.LatestVersion,
		&i.LastCheckedAt,
		&i.LastError,
		&i.ManifestDigest,
		&i.SourceUrl,
		&i.RegistryID,
		&i.DefinitionRevision,
		&i.OperationID,
		&i.LastOperationID,
		&i.OperationSourceUrl,
		&i.OperationRegistryID,
		&i.OperationDefinitionRevision,
		&i.OperationIntent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBotDependencyInstallationIntent = `-- name: UpsertBotDependencyInstallationIntent :one
INSERT INTO bot_dependency_installations (
  bot_id, dependency_id, source, status,
  installed_version, manifest_digest, source_url, registry_id, definition_revision
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (team_id, bot_id, dependency_id)
DO UPDATE SET source = EXCLUDED.source,
              last_error = '',
              status = EXCLUDED.status,
              installed_version = EXCLUDED.installed_version,
              manifest_digest = EXCLUDED.manifest_digest,
              source_url = EXCLUDED.source_url, registry_id = EXCLUDED.registry_id,
              definition_revision = EXCLUDED.definition_revision,
              updated_at = now()
WHERE bot_dependency_installations.operation_id = ''
RETURNING id, team_id, bot_id, dependency_id, source, status,
          installed_version, latest_version, last_checked_at, last_error,
          manifest_digest, source_url, registry_id, definition_revision, operation_id, last_operation_id, operation_source_url, operation_registry_id, operation_definition_revision, operation_intent, created_at, updated_at
`

type UpsertBotDependencyInstallationIntentParams struct {
	BotID              pgtype.UUID `json:"bot_id"`
	DependencyID       string      `json:"dependency_id"`
	Source             string      `json:"source"`
	Status             string      `json:"status"`
	InstalledVersion   string      `json:"installed_version"`
	ManifestDigest     string      `json:"manifest_digest"`
	SourceUrl          string      `json:"source_url"`
	RegistryID         string      `json:"registry_id"`
	DefinitionRevision string      `json:"definition_revision"`
}

func (q *Queries) UpsertBotDependencyInstallationIntent(ctx context.Context, arg UpsertBotDependencyInstallationIntentParams) (BotDependencyInstallation, error) {
	row := q.db.QueryRow(ctx, upsertBotDependencyInstallationIntent,
		arg.BotID,
		arg.DependencyID,
		arg.Source,
		arg.Status,
		arg.InstalledVersion,
		arg.ManifestDigest,
		arg.SourceUrl,
		arg.RegistryID,
		arg.DefinitionRevision,
	)
	var i BotDependencyInstallation
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BotID,
		&i.DependencyID,
		&i.Source,
		&i.Status,
		&i.InstalledVersion,
		&i.LatestVersion,
		&i.LastCheckedAt,
		&i.LastError,
		&i.ManifestDigest,
		&i.SourceUrl,
		&i.RegistryID,
		&i.DefinitionRevision,
		&i.OperationID,
		&i.LastOperationID,
		&i.OperationSourceUrl,
		&i.OperationRegistryID,
		&i.OperationDefinitionRevision,
		&i.OperationIntent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
