// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace_dependencies.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBotDependencyInstallation = `-- name: DeleteBotDependencyInstallation :execrows
DELETE FROM bot_dependency_installations
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND workspace_target_id = $2
  AND dependency_id = $3
`

type DeleteBotDependencyInstallationParams struct {
	BotID             pgtype.UUID `json:"bot_id"`
	WorkspaceTargetID string      `json:"workspace_target_id"`
	DependencyID      string      `json:"dependency_id"`
}

func (q *Queries) DeleteBotDependencyInstallation(ctx context.Context, arg DeleteBotDependencyInstallationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBotDependencyInstallation, arg.BotID, arg.WorkspaceTargetID, arg.DependencyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBotDependencyInstallation = `-- name: GetBotDependencyInstallation :one
SELECT id, team_id, bot_id, workspace_target_id, dependency_id, source, status,
       installed_version, latest_version, last_checked_at, last_error,
       manifest_digest, created_at, updated_at
FROM bot_dependency_installations
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND workspace_target_id = $2
  AND dependency_id = $3
LIMIT 1
`

type GetBotDependencyInstallationParams struct {
	BotID             pgtype.UUID `json:"bot_id"`
	WorkspaceTargetID string      `json:"workspace_target_id"`
	DependencyID      string      `json:"dependency_id"`
}

func (q *Queries) GetBotDependencyInstallation(ctx context.Context, arg GetBotDependencyInstallationParams) (BotDependencyInstallation, error) {
	row := q.db.QueryRow(ctx, getBotDependencyInstallation, arg.BotID, arg.WorkspaceTargetID, arg.DependencyID)
	var i BotDependencyInstallation
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BotID,
		&i.WorkspaceTargetID,
		&i.DependencyID,
		&i.Source,
		&i.Status,
		&i.InstalledVersion,
		&i.LatestVersion,
		&i.LastCheckedAt,
		&i.LastError,
		&i.ManifestDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBotDependencyInstallations = `-- name: ListBotDependencyInstallations :many
SELECT id, team_id, bot_id, workspace_target_id, dependency_id, source, status,
       installed_version, latest_version, last_checked_at, last_error,
       manifest_digest, created_at, updated_at
FROM bot_dependency_installations
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
ORDER BY workspace_target_id, dependency_id
`

func (q *Queries) ListBotDependencyInstallations(ctx context.Context, botID pgtype.UUID) ([]BotDependencyInstallation, error) {
	rows, err := q.db.Query(ctx, listBotDependencyInstallations, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotDependencyInstallation
	for rows.Next() {
		var i BotDependencyInstallation
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.BotID,
			&i.WorkspaceTargetID,
			&i.DependencyID,
			&i.Source,
			&i.Status,
			&i.InstalledVersion,
			&i.LatestVersion,
			&i.LastCheckedAt,
			&i.LastError,
			&i.ManifestDigest,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBotDependencyInstallationsByStatus = `-- name: ListBotDependencyInstallationsByStatus :many
SELECT id, team_id, bot_id, workspace_target_id, dependency_id, source, status,
       installed_version, latest_version, last_checked_at, last_error,
       manifest_digest, created_at, updated_at
FROM bot_dependency_installations
WHERE team_id = public.memoh_current_team_id()
  AND status = $1
ORDER BY bot_id, workspace_target_id, dependency_id
`

func (q *Queries) ListBotDependencyInstallationsByStatus(ctx context.Context, status string) ([]BotDependencyInstallation, error) {
	rows, err := q.db.Query(ctx, listBotDependencyInstallationsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotDependencyInstallation
	for rows.Next() {
		var i BotDependencyInstallation
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.BotID,
			&i.WorkspaceTargetID,
			&i.DependencyID,
			&i.Source,
			&i.Status,
			&i.InstalledVersion,
			&i.LatestVersion,
			&i.LastCheckedAt,
			&i.LastError,
			&i.ManifestDigest,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBotDependencyInstallationsForTarget = `-- name: ListBotDependencyInstallationsForTarget :many
SELECT id, team_id, bot_id, workspace_target_id, dependency_id, source, status,
       installed_version, latest_version, last_checked_at, last_error,
       manifest_digest, created_at, updated_at
FROM bot_dependency_installations
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $1
  AND workspace_target_id = $2
ORDER BY dependency_id
`

type ListBotDependencyInstallationsForTargetParams struct {
	BotID             pgtype.UUID `json:"bot_id"`
	WorkspaceTargetID string      `json:"workspace_target_id"`
}

func (q *Queries) ListBotDependencyInstallationsForTarget(ctx context.Context, arg ListBotDependencyInstallationsForTargetParams) ([]BotDependencyInstallation, error) {
	rows, err := q.db.Query(ctx, listBotDependencyInstallationsForTarget, arg.BotID, arg.WorkspaceTargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotDependencyInstallation
	for rows.Next() {
		var i BotDependencyInstallation
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.BotID,
			&i.WorkspaceTargetID,
			&i.DependencyID,
			&i.Source,
			&i.Status,
			&i.InstalledVersion,
			&i.LatestVersion,
			&i.LastCheckedAt,
			&i.LastError,
			&i.ManifestDigest,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleBotDependencyOperations = `-- name: ListStaleBotDependencyOperations :many
SELECT id, team_id, bot_id, workspace_target_id, dependency_id, source, status,
       installed_version, latest_version, last_checked_at, last_error,
       manifest_digest, created_at, updated_at
FROM bot_dependency_installations
WHERE team_id = public.memoh_current_team_id()
  AND status IN ('installing', 'updating', 'removing')
  AND updated_at < now() - make_interval(secs => $1::double precision)
ORDER BY updated_at, id
`

func (q *Queries) ListStaleBotDependencyOperations(ctx context.Context, olderThanSeconds float64) ([]BotDependencyInstallation, error) {
	rows, err := q.db.Query(ctx, listStaleBotDependencyOperations, olderThanSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotDependencyInstallation
	for rows.Next() {
		var i BotDependencyInstallation
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.BotID,
			&i.WorkspaceTargetID,
			&i.DependencyID,
			&i.Source,
			&i.Status,
			&i.InstalledVersion,
			&i.LatestVersion,
			&i.LastCheckedAt,
			&i.LastError,
			&i.ManifestDigest,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBotDependencyInstallationObserved = `-- name: UpdateBotDependencyInstallationObserved :one
UPDATE bot_dependency_installations
SET source = COALESCE($1::text, source),
    installed_version = COALESCE($2::text, installed_version),
    latest_version = COALESCE($3::text, latest_version),
    last_checked_at = COALESCE($4::timestamptz, last_checked_at),
    last_error = COALESCE($5::text, last_error),
    manifest_digest = COALESCE($6::text, manifest_digest),
    updated_at = now()
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $7
  AND workspace_target_id = $8
  AND dependency_id = $9
RETURNING id, team_id, bot_id, workspace_target_id, dependency_id, source, status,
          installed_version, latest_version, last_checked_at, last_error,
          manifest_digest, created_at, updated_at
`

type UpdateBotDependencyInstallationObservedParams struct {
	Source            pgtype.Text        `json:"source"`
	InstalledVersion  pgtype.Text        `json:"installed_version"`
	LatestVersion     pgtype.Text        `json:"latest_version"`
	LastCheckedAt     pgtype.Timestamptz `json:"last_checked_at"`
	LastError         pgtype.Text        `json:"last_error"`
	ManifestDigest    pgtype.Text        `json:"manifest_digest"`
	BotID             pgtype.UUID        `json:"bot_id"`
	WorkspaceTargetID string             `json:"workspace_target_id"`
	DependencyID      string             `json:"dependency_id"`
}

func (q *Queries) UpdateBotDependencyInstallationObserved(ctx context.Context, arg UpdateBotDependencyInstallationObservedParams) (BotDependencyInstallation, error) {
	row := q.db.QueryRow(ctx, updateBotDependencyInstallationObserved,
		arg.Source,
		arg.InstalledVersion,
		arg.LatestVersion,
		arg.LastCheckedAt,
		arg.LastError,
		arg.ManifestDigest,
		arg.BotID,
		arg.WorkspaceTargetID,
		arg.DependencyID,
	)
	var i BotDependencyInstallation
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BotID,
		&i.WorkspaceTargetID,
		&i.DependencyID,
		&i.Source,
		&i.Status,
		&i.InstalledVersion,
		&i.LatestVersion,
		&i.LastCheckedAt,
		&i.LastError,
		&i.ManifestDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBotDependencyInstallationStatus = `-- name: UpdateBotDependencyInstallationStatus :one
UPDATE bot_dependency_installations
SET status = $1,
    last_error = $2,
    updated_at = now()
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $3
  AND workspace_target_id = $4
  AND dependency_id = $5
RETURNING id, team_id, bot_id, workspace_target_id, dependency_id, source, status,
          installed_version, latest_version, last_checked_at, last_error,
          manifest_digest, created_at, updated_at
`

type UpdateBotDependencyInstallationStatusParams struct {
	Status            string      `json:"status"`
	LastError         string      `json:"last_error"`
	BotID             pgtype.UUID `json:"bot_id"`
	WorkspaceTargetID string      `json:"workspace_target_id"`
	DependencyID      string      `json:"dependency_id"`
}

func (q *Queries) UpdateBotDependencyInstallationStatus(ctx context.Context, arg UpdateBotDependencyInstallationStatusParams) (BotDependencyInstallation, error) {
	row := q.db.QueryRow(ctx, updateBotDependencyInstallationStatus,
		arg.Status,
		arg.LastError,
		arg.BotID,
		arg.WorkspaceTargetID,
		arg.DependencyID,
	)
	var i BotDependencyInstallation
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BotID,
		&i.WorkspaceTargetID,
		&i.DependencyID,
		&i.Source,
		&i.Status,
		&i.InstalledVersion,
		&i.LatestVersion,
		&i.LastCheckedAt,
		&i.LastError,
		&i.ManifestDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBotDependencyInstallationIntent = `-- name: UpsertBotDependencyInstallationIntent :one
INSERT INTO bot_dependency_installations (
  bot_id, workspace_target_id, dependency_id, source, status,
  installed_version, manifest_digest
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (team_id, bot_id, workspace_target_id, dependency_id)
DO UPDATE SET source = EXCLUDED.source,
              status = EXCLUDED.status,
              installed_version = EXCLUDED.installed_version,
              manifest_digest = EXCLUDED.manifest_digest,
              updated_at = now()
RETURNING id, team_id, bot_id, workspace_target_id, dependency_id, source, status,
          installed_version, latest_version, last_checked_at, last_error,
          manifest_digest, created_at, updated_at
`

type UpsertBotDependencyInstallationIntentParams struct {
	BotID             pgtype.UUID `json:"bot_id"`
	WorkspaceTargetID string      `json:"workspace_target_id"`
	DependencyID      string      `json:"dependency_id"`
	Source            string      `json:"source"`
	Status            string      `json:"status"`
	InstalledVersion  string      `json:"installed_version"`
	ManifestDigest    string      `json:"manifest_digest"`
}

func (q *Queries) UpsertBotDependencyInstallationIntent(ctx context.Context, arg UpsertBotDependencyInstallationIntentParams) (BotDependencyInstallation, error) {
	row := q.db.QueryRow(ctx, upsertBotDependencyInstallationIntent,
		arg.BotID,
		arg.WorkspaceTargetID,
		arg.DependencyID,
		arg.Source,
		arg.Status,
		arg.InstalledVersion,
		arg.ManifestDigest,
	)
	var i BotDependencyInstallation
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BotID,
		&i.WorkspaceTargetID,
		&i.DependencyID,
		&i.Source,
		&i.Status,
		&i.InstalledVersion,
		&i.LatestVersion,
		&i.LastCheckedAt,
		&i.LastError,
		&i.ManifestDigest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
