// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace_dependency_desired.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDesiredDependencyRepair = `-- name: ClaimDesiredDependencyRepair :one
WITH target AS (
  SELECT d.team_id, d.bot_id, d.dependency_id, d.desired_revision, d.version, d.source_url, d.registry_id, d.definition_revision, d.manifest_digest, d.authorized_at, d.authorized_by_operation_id, d.authorized_by_actor, d.platform_os, d.platform_arch, d.platform_libc, d.entrypoints, d.installation_id, d.payload_path, d.store_root, d.repair_status, d.repair_operation_id, d.repair_attempts, d.repair_next_attempt_at, d.repair_last_error_code, d.created_at, d.updated_at FROM bot_dependency_desired_installations d
  WHERE d.team_id = public.memoh_current_team_id() AND d.bot_id = $1 AND d.dependency_id = $2
    AND d.desired_revision = $3 AND d.repair_status = 'queued' AND d.repair_operation_id = $4
  FOR UPDATE
), claimed AS (
  INSERT INTO bot_dependency_installations (bot_id, dependency_id, source, status, installed_version, manifest_digest, source_url, registry_id, definition_revision, operation_id, operation_source_url, operation_registry_id, operation_definition_revision, operation_intent)
  SELECT bot_id, dependency_id, 'managed', 'installing', version, manifest_digest, source_url, registry_id, definition_revision, $4, source_url, registry_id, definition_revision, $5::jsonb FROM target
  ON CONFLICT (team_id, bot_id, dependency_id) DO UPDATE
  SET status = 'installing', operation_id = EXCLUDED.operation_id,
      operation_source_url = EXCLUDED.operation_source_url, operation_registry_id = EXCLUDED.operation_registry_id, operation_definition_revision = EXCLUDED.operation_definition_revision, operation_intent = EXCLUDED.operation_intent,
      last_error = '', updated_at = now()
  WHERE bot_dependency_installations.status NOT IN ('installing','updating','removing')
  RETURNING id, team_id, bot_id, dependency_id, source, status, installed_version, latest_version, last_checked_at, last_error, manifest_digest, source_url, registry_id, definition_revision, operation_id, last_operation_id, operation_source_url, operation_registry_id, operation_definition_revision, operation_intent, created_at, updated_at
), started AS (
  UPDATE bot_dependency_desired_installations d SET repair_status = 'installing', repair_attempts = repair_attempts + 1, updated_at = now()
  WHERE d.team_id = public.memoh_current_team_id() AND d.bot_id = $1 AND d.dependency_id = $2
    AND EXISTS (SELECT 1 FROM claimed) RETURNING d.bot_id
)
SELECT claimed.id, claimed.team_id, claimed.bot_id, claimed.dependency_id, claimed.source, claimed.status, claimed.installed_version, claimed.latest_version, claimed.last_checked_at, claimed.last_error, claimed.manifest_digest, claimed.source_url, claimed.registry_id, claimed.definition_revision, claimed.operation_id, claimed.last_operation_id, claimed.operation_source_url, claimed.operation_registry_id, claimed.operation_definition_revision, claimed.operation_intent, claimed.created_at, claimed.updated_at FROM claimed, started
`

type ClaimDesiredDependencyRepairParams struct {
	BotID           pgtype.UUID `json:"bot_id"`
	DependencyID    string      `json:"dependency_id"`
	DesiredRevision string      `json:"desired_revision"`
	OperationID     string      `json:"operation_id"`
	OperationIntent []byte      `json:"operation_intent"`
}

type ClaimDesiredDependencyRepairRow struct {
	ID                          pgtype.UUID        `json:"id"`
	TeamID                      pgtype.UUID        `json:"team_id"`
	BotID                       pgtype.UUID        `json:"bot_id"`
	DependencyID                string             `json:"dependency_id"`
	Source                      string             `json:"source"`
	Status                      string             `json:"status"`
	InstalledVersion            string             `json:"installed_version"`
	LatestVersion               string             `json:"latest_version"`
	LastCheckedAt               pgtype.Timestamptz `json:"last_checked_at"`
	LastError                   string             `json:"last_error"`
	ManifestDigest              string             `json:"manifest_digest"`
	SourceUrl                   string             `json:"source_url"`
	RegistryID                  string             `json:"registry_id"`
	DefinitionRevision          string             `json:"definition_revision"`
	OperationID                 string             `json:"operation_id"`
	LastOperationID             string             `json:"last_operation_id"`
	OperationSourceUrl          string             `json:"operation_source_url"`
	OperationRegistryID         string             `json:"operation_registry_id"`
	OperationDefinitionRevision string             `json:"operation_definition_revision"`
	OperationIntent             []byte             `json:"operation_intent"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ClaimDesiredDependencyRepair(ctx context.Context, arg ClaimDesiredDependencyRepairParams) (ClaimDesiredDependencyRepairRow, error) {
	row := q.db.QueryRow(ctx, claimDesiredDependencyRepair,
		arg.BotID,
		arg.DependencyID,
		arg.DesiredRevision,
		arg.OperationID,
		arg.OperationIntent,
	)
	var i ClaimDesiredDependencyRepairRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BotID,
		&i.DependencyID,
		&i.Source,
		&i.Status,
		&i.InstalledVersion,
		&i.LatestVersion,
		&i.LastCheckedAt,
		&i.LastError,
		&i.ManifestDigest,
		&i.SourceUrl,
		&i.RegistryID,
		&i.DefinitionRevision,
		&i.OperationID,
		&i.LastOperationID,
		&i.OperationSourceUrl,
		&i.OperationRegistryID,
		&i.OperationDefinitionRevision,
		&i.OperationIntent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finishAuthorizedDependencyOperation = `-- name: FinishAuthorizedDependencyOperation :one
WITH target_lock AS MATERIALIZED (
  SELECT d.desired_revision FROM bot_dependency_desired_installations d
  WHERE d.team_id = public.memoh_current_team_id() AND d.bot_id = $1 AND d.dependency_id = $2
  FOR UPDATE
), owned AS (
  UPDATE bot_dependency_installations i
  SET source = 'managed', status = 'installed', installed_version = $3, manifest_digest = $4,
      source_url = $5, registry_id = $6, definition_revision = $7,
      last_operation_id = i.operation_id, operation_id = '', operation_source_url = '', operation_registry_id = '', operation_definition_revision = '', operation_intent = NULL, last_error = '', updated_at = now()
  WHERE i.team_id = public.memoh_current_team_id() AND i.bot_id = $1 AND i.dependency_id = $2
    AND i.operation_id = $8 AND i.operation_id <> ''
    AND (SELECT count(*) FROM target_lock) >= 0 RETURNING i.id, i.team_id, i.bot_id, i.dependency_id, i.source, i.status, i.installed_version, i.latest_version, i.last_checked_at, i.last_error, i.manifest_digest, i.source_url, i.registry_id, i.definition_revision, i.operation_id, i.last_operation_id, i.operation_source_url, i.operation_registry_id, i.operation_definition_revision, i.operation_intent, i.created_at, i.updated_at
), desired AS (
  INSERT INTO bot_dependency_desired_installations (bot_id, dependency_id, desired_revision, version, source_url, registry_id, definition_revision, manifest_digest,
      authorized_by_operation_id, authorized_by_actor, platform_os, platform_arch, platform_libc, entrypoints, installation_id, payload_path, store_root)
  SELECT bot_id, dependency_id, $8, installed_version, source_url, registry_id, definition_revision, manifest_digest,
      $8, $9, $10, $11, $12, $13::jsonb, $14, $15, $16 FROM owned
  ON CONFLICT (team_id, bot_id, dependency_id) DO UPDATE
  SET desired_revision = EXCLUDED.desired_revision, version = EXCLUDED.version, source_url = EXCLUDED.source_url, registry_id = EXCLUDED.registry_id,
      definition_revision = EXCLUDED.definition_revision, manifest_digest = EXCLUDED.manifest_digest,
      authorized_at = now(), authorized_by_operation_id = EXCLUDED.authorized_by_operation_id, authorized_by_actor = EXCLUDED.authorized_by_actor,
      platform_os = EXCLUDED.platform_os, platform_arch = EXCLUDED.platform_arch, platform_libc = EXCLUDED.platform_libc,
      entrypoints = EXCLUDED.entrypoints, installation_id = EXCLUDED.installation_id, payload_path = EXCLUDED.payload_path, store_root = EXCLUDED.store_root,
      repair_status = 'ready', repair_operation_id = '', repair_attempts = 0, repair_next_attempt_at = NULL, repair_last_error_code = '', updated_at = now()
  RETURNING team_id, bot_id, dependency_id, desired_revision, version, source_url, registry_id, definition_revision, manifest_digest, authorized_at, authorized_by_operation_id, authorized_by_actor, platform_os, platform_arch, platform_libc, entrypoints, installation_id, payload_path, store_root, repair_status, repair_operation_id, repair_attempts, repair_next_attempt_at, repair_last_error_code, created_at, updated_at
), audited AS (
  INSERT INTO bot_dependency_authorization_events (bot_id, dependency_id, operation_id, action, actor, version, source_url, registry_id, definition_revision, manifest_digest)
  SELECT bot_id, dependency_id, authorized_by_operation_id, 'authorize', authorized_by_actor, version, source_url, registry_id, definition_revision, manifest_digest FROM desired
  ON CONFLICT DO NOTHING
)
SELECT id, team_id, bot_id, dependency_id, source, status, installed_version, latest_version, last_checked_at, last_error, manifest_digest, source_url, registry_id, definition_revision, operation_id, last_operation_id, operation_source_url, operation_registry_id, operation_definition_revision, operation_intent, created_at, updated_at FROM owned
`

type FinishAuthorizedDependencyOperationParams struct {
	BotID              pgtype.UUID `json:"bot_id"`
	DependencyID       string      `json:"dependency_id"`
	Version            string      `json:"version"`
	ManifestDigest     string      `json:"manifest_digest"`
	SourceUrl          string      `json:"source_url"`
	RegistryID         string      `json:"registry_id"`
	DefinitionRevision string      `json:"definition_revision"`
	OperationID        string      `json:"operation_id"`
	Actor              string      `json:"actor"`
	PlatformOs         string      `json:"platform_os"`
	PlatformArch       string      `json:"platform_arch"`
	PlatformLibc       string      `json:"platform_libc"`
	Entrypoints        []byte      `json:"entrypoints"`
	InstallationID     string      `json:"installation_id"`
	PayloadPath        string      `json:"payload_path"`
	StoreRoot          string      `json:"store_root"`
}

type FinishAuthorizedDependencyOperationRow struct {
	ID                          pgtype.UUID        `json:"id"`
	TeamID                      pgtype.UUID        `json:"team_id"`
	BotID                       pgtype.UUID        `json:"bot_id"`
	DependencyID                string             `json:"dependency_id"`
	Source                      string             `json:"source"`
	Status                      string             `json:"status"`
	InstalledVersion            string             `json:"installed_version"`
	LatestVersion               string             `json:"latest_version"`
	LastCheckedAt               pgtype.Timestamptz `json:"last_checked_at"`
	LastError                   string             `json:"last_error"`
	ManifestDigest              string             `json:"manifest_digest"`
	SourceUrl                   string             `json:"source_url"`
	RegistryID                  string             `json:"registry_id"`
	DefinitionRevision          string             `json:"definition_revision"`
	OperationID                 string             `json:"operation_id"`
	LastOperationID             string             `json:"last_operation_id"`
	OperationSourceUrl          string             `json:"operation_source_url"`
	OperationRegistryID         string             `json:"operation_registry_id"`
	OperationDefinitionRevision string             `json:"operation_definition_revision"`
	OperationIntent             []byte             `json:"operation_intent"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                   pgtype.Timestamptz `json:"updated_at"`
}

// Match repair claims: acquire the optional desired row before installation.
func (q *Queries) FinishAuthorizedDependencyOperation(ctx context.Context, arg FinishAuthorizedDependencyOperationParams) (FinishAuthorizedDependencyOperationRow, error) {
	row := q.db.QueryRow(ctx, finishAuthorizedDependencyOperation,
		arg.BotID,
		arg.DependencyID,
		arg.Version,
		arg.ManifestDigest,
		arg.SourceUrl,
		arg.RegistryID,
		arg.DefinitionRevision,
		arg.OperationID,
		arg.Actor,
		arg.PlatformOs,
		arg.PlatformArch,
		arg.PlatformLibc,
		arg.Entrypoints,
		arg.InstallationID,
		arg.PayloadPath,
		arg.StoreRoot,
	)
	var i FinishAuthorizedDependencyOperationRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BotID,
		&i.DependencyID,
		&i.Source,
		&i.Status,
		&i.InstalledVersion,
		&i.LatestVersion,
		&i.LastCheckedAt,
		&i.LastError,
		&i.ManifestDigest,
		&i.SourceUrl,
		&i.RegistryID,
		&i.DefinitionRevision,
		&i.OperationID,
		&i.LastOperationID,
		&i.OperationSourceUrl,
		&i.OperationRegistryID,
		&i.OperationDefinitionRevision,
		&i.OperationIntent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finishDesiredDependencyRepair = `-- name: FinishDesiredDependencyRepair :one
WITH target_lock AS MATERIALIZED (
  SELECT d.desired_revision FROM bot_dependency_desired_installations d
  WHERE d.team_id = public.memoh_current_team_id() AND d.bot_id = $2 AND d.dependency_id = $3
  FOR UPDATE
), owned AS (
  SELECT i.id, i.team_id, i.bot_id, i.dependency_id, i.source, i.status, i.installed_version, i.latest_version, i.last_checked_at, i.last_error, i.manifest_digest, i.source_url, i.registry_id, i.definition_revision, i.operation_id, i.last_operation_id, i.operation_source_url, i.operation_registry_id, i.operation_definition_revision, i.operation_intent, i.created_at, i.updated_at FROM bot_dependency_installations i
  WHERE i.team_id = public.memoh_current_team_id() AND i.bot_id = $2 AND i.dependency_id = $3
    AND i.operation_id = $1 AND operation_id <> ''
    AND (SELECT count(*) FROM target_lock) >= 0 FOR UPDATE
), repaired AS (
  UPDATE bot_dependency_desired_installations d
  SET entrypoints = $4::jsonb, installation_id = $5, payload_path = $6, store_root = $7,
      repair_status = 'ready', repair_operation_id = '', repair_next_attempt_at = NULL, repair_last_error_code = '', updated_at = now()
  WHERE d.team_id = public.memoh_current_team_id() AND d.bot_id = $2 AND d.dependency_id = $3
    AND d.desired_revision = $8 AND d.repair_operation_id = $1
    AND d.version = $9 AND EXISTS (SELECT 1 FROM owned) RETURNING team_id, bot_id, dependency_id, desired_revision, version, source_url, registry_id, definition_revision, manifest_digest, authorized_at, authorized_by_operation_id, authorized_by_actor, platform_os, platform_arch, platform_libc, entrypoints, installation_id, payload_path, store_root, repair_status, repair_operation_id, repair_attempts, repair_next_attempt_at, repair_last_error_code, created_at, updated_at
)
UPDATE bot_dependency_installations i
SET source = 'managed', status = 'installed', installed_version = d.version, manifest_digest = d.manifest_digest,
    source_url = d.source_url, registry_id = d.registry_id, definition_revision = d.definition_revision,
    last_operation_id = i.operation_id, operation_id = '', operation_source_url = '', operation_registry_id = '', operation_definition_revision = '', operation_intent = NULL, last_error = '', updated_at = now()
FROM repaired d
WHERE i.team_id = d.team_id AND i.bot_id = d.bot_id AND i.dependency_id = d.dependency_id AND i.operation_id = $1
RETURNING i.id, i.team_id, i.bot_id, i.dependency_id, i.source, i.status, i.installed_version, i.latest_version, i.last_checked_at, i.last_error, i.manifest_digest, i.source_url, i.registry_id, i.definition_revision, i.operation_id, i.last_operation_id, i.operation_source_url, i.operation_registry_id, i.operation_definition_revision, i.operation_intent, i.created_at, i.updated_at
`

type FinishDesiredDependencyRepairParams struct {
	OperationID     string      `json:"operation_id"`
	BotID           pgtype.UUID `json:"bot_id"`
	DependencyID    string      `json:"dependency_id"`
	Entrypoints     []byte      `json:"entrypoints"`
	InstallationID  string      `json:"installation_id"`
	PayloadPath     string      `json:"payload_path"`
	StoreRoot       string      `json:"store_root"`
	DesiredRevision string      `json:"desired_revision"`
	Version         string      `json:"version"`
}

// Keep the desired -> installation lock order shared by all managed writes.
func (q *Queries) FinishDesiredDependencyRepair(ctx context.Context, arg FinishDesiredDependencyRepairParams) (BotDependencyInstallation, error) {
	row := q.db.QueryRow(ctx, finishDesiredDependencyRepair,
		arg.OperationID,
		arg.BotID,
		arg.DependencyID,
		arg.Entrypoints,
		arg.InstallationID,
		arg.PayloadPath,
		arg.StoreRoot,
		arg.DesiredRevision,
		arg.Version,
	)
	var i BotDependencyInstallation
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BotID,
		&i.DependencyID,
		&i.Source,
		&i.Status,
		&i.InstalledVersion,
		&i.LatestVersion,
		&i.LastCheckedAt,
		&i.LastError,
		&i.ManifestDigest,
		&i.SourceUrl,
		&i.RegistryID,
		&i.DefinitionRevision,
		&i.OperationID,
		&i.LastOperationID,
		&i.OperationSourceUrl,
		&i.OperationRegistryID,
		&i.OperationDefinitionRevision,
		&i.OperationIntent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDesiredDependencyInstallation = `-- name: GetDesiredDependencyInstallation :one
SELECT team_id, bot_id, dependency_id, desired_revision, version, source_url, registry_id, definition_revision, manifest_digest, authorized_at, authorized_by_operation_id, authorized_by_actor, platform_os, platform_arch, platform_libc, entrypoints, installation_id, payload_path, store_root, repair_status, repair_operation_id, repair_attempts, repair_next_attempt_at, repair_last_error_code, created_at, updated_at FROM bot_dependency_desired_installations
WHERE team_id = public.memoh_current_team_id() AND bot_id = $1 AND dependency_id = $2
`

type GetDesiredDependencyInstallationParams struct {
	BotID        pgtype.UUID `json:"bot_id"`
	DependencyID string      `json:"dependency_id"`
}

func (q *Queries) GetDesiredDependencyInstallation(ctx context.Context, arg GetDesiredDependencyInstallationParams) (BotDependencyDesiredInstallation, error) {
	row := q.db.QueryRow(ctx, getDesiredDependencyInstallation, arg.BotID, arg.DependencyID)
	var i BotDependencyDesiredInstallation
	err := row.Scan(
		&i.TeamID,
		&i.BotID,
		&i.DependencyID,
		&i.DesiredRevision,
		&i.Version,
		&i.SourceUrl,
		&i.RegistryID,
		&i.DefinitionRevision,
		&i.ManifestDigest,
		&i.AuthorizedAt,
		&i.AuthorizedByOperationID,
		&i.AuthorizedByActor,
		&i.PlatformOs,
		&i.PlatformArch,
		&i.PlatformLibc,
		&i.Entrypoints,
		&i.InstallationID,
		&i.PayloadPath,
		&i.StoreRoot,
		&i.RepairStatus,
		&i.RepairOperationID,
		&i.RepairAttempts,
		&i.RepairNextAttemptAt,
		&i.RepairLastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const invalidateQueuedDesiredDependencyRepair = `-- name: InvalidateQueuedDesiredDependencyRepair :execrows
UPDATE bot_dependency_desired_installations d
SET desired_revision = $1, repair_status = 'ready', repair_operation_id = '',
    repair_attempts = 0, repair_next_attempt_at = NULL, repair_last_error_code = '', updated_at = now()
WHERE d.team_id = public.memoh_current_team_id() AND d.bot_id = $2 AND d.dependency_id = $3
  AND EXISTS (SELECT 1 FROM bot_dependency_installations i WHERE i.team_id = d.team_id AND i.bot_id = d.bot_id AND i.dependency_id = d.dependency_id AND i.operation_id = $1)
`

type InvalidateQueuedDesiredDependencyRepairParams struct {
	OperationID  string      `json:"operation_id"`
	BotID        pgtype.UUID `json:"bot_id"`
	DependencyID string      `json:"dependency_id"`
}

// An admitted management operation supersedes older queued recovery without
// changing the previous successfully installed target or its authorization.
func (q *Queries) InvalidateQueuedDesiredDependencyRepair(ctx context.Context, arg InvalidateQueuedDesiredDependencyRepairParams) (int64, error) {
	result, err := q.db.Exec(ctx, invalidateQueuedDesiredDependencyRepair, arg.OperationID, arg.BotID, arg.DependencyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listDesiredDependencyInstallations = `-- name: ListDesiredDependencyInstallations :many
SELECT team_id, bot_id, dependency_id, desired_revision, version, source_url, registry_id, definition_revision, manifest_digest, authorized_at, authorized_by_operation_id, authorized_by_actor, platform_os, platform_arch, platform_libc, entrypoints, installation_id, payload_path, store_root, repair_status, repair_operation_id, repair_attempts, repair_next_attempt_at, repair_last_error_code, created_at, updated_at FROM bot_dependency_desired_installations
WHERE team_id = public.memoh_current_team_id() AND bot_id = $1 ORDER BY dependency_id
`

func (q *Queries) ListDesiredDependencyInstallations(ctx context.Context, botID pgtype.UUID) ([]BotDependencyDesiredInstallation, error) {
	rows, err := q.db.Query(ctx, listDesiredDependencyInstallations, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotDependencyDesiredInstallation
	for rows.Next() {
		var i BotDependencyDesiredInstallation
		if err := rows.Scan(
			&i.TeamID,
			&i.BotID,
			&i.DependencyID,
			&i.DesiredRevision,
			&i.Version,
			&i.SourceUrl,
			&i.RegistryID,
			&i.DefinitionRevision,
			&i.ManifestDigest,
			&i.AuthorizedAt,
			&i.AuthorizedByOperationID,
			&i.AuthorizedByActor,
			&i.PlatformOs,
			&i.PlatformArch,
			&i.PlatformLibc,
			&i.Entrypoints,
			&i.InstallationID,
			&i.PayloadPath,
			&i.StoreRoot,
			&i.RepairStatus,
			&i.RepairOperationID,
			&i.RepairAttempts,
			&i.RepairNextAttemptAt,
			&i.RepairLastErrorCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDesiredDependencyRepairPage = `-- name: ListDesiredDependencyRepairPage :many
SELECT team_id, bot_id, dependency_id, desired_revision, version, source_url, registry_id, definition_revision, manifest_digest, authorized_at, authorized_by_operation_id, authorized_by_actor, platform_os, platform_arch, platform_libc, entrypoints, installation_id, payload_path, store_root, repair_status, repair_operation_id, repair_attempts, repair_next_attempt_at, repair_last_error_code, created_at, updated_at FROM bot_dependency_desired_installations
WHERE team_id = public.memoh_current_team_id()
  AND (bot_id, dependency_id) > ($1::uuid, $2::text)
ORDER BY bot_id, dependency_id LIMIT $3
`

type ListDesiredDependencyRepairPageParams struct {
	AfterBotID        pgtype.UUID `json:"after_bot_id"`
	AfterDependencyID string      `json:"after_dependency_id"`
	PageSize          int32       `json:"page_size"`
}

func (q *Queries) ListDesiredDependencyRepairPage(ctx context.Context, arg ListDesiredDependencyRepairPageParams) ([]BotDependencyDesiredInstallation, error) {
	rows, err := q.db.Query(ctx, listDesiredDependencyRepairPage, arg.AfterBotID, arg.AfterDependencyID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotDependencyDesiredInstallation
	for rows.Next() {
		var i BotDependencyDesiredInstallation
		if err := rows.Scan(
			&i.TeamID,
			&i.BotID,
			&i.DependencyID,
			&i.DesiredRevision,
			&i.Version,
			&i.SourceUrl,
			&i.RegistryID,
			&i.DefinitionRevision,
			&i.ManifestDigest,
			&i.AuthorizedAt,
			&i.AuthorizedByOperationID,
			&i.AuthorizedByActor,
			&i.PlatformOs,
			&i.PlatformArch,
			&i.PlatformLibc,
			&i.Entrypoints,
			&i.InstallationID,
			&i.PayloadPath,
			&i.StoreRoot,
			&i.RepairStatus,
			&i.RepairOperationID,
			&i.RepairAttempts,
			&i.RepairNextAttemptAt,
			&i.RepairLastErrorCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queueDesiredDependencyRepair = `-- name: QueueDesiredDependencyRepair :one
UPDATE bot_dependency_desired_installations
SET repair_status = 'queued', repair_operation_id = $1,
    repair_attempts = CASE WHEN $2::boolean THEN 0 ELSE repair_attempts END,
    repair_next_attempt_at = NULL, repair_last_error_code = '', updated_at = now()
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $3 AND dependency_id = $4
  AND desired_revision = $5
  AND (repair_status = 'ready'
    OR (repair_status = 'backoff' AND repair_next_attempt_at <= $6::timestamptz)
    OR ($2::boolean AND repair_status IN ('backoff','manual_required')))
RETURNING team_id, bot_id, dependency_id, desired_revision, version, source_url, registry_id, definition_revision, manifest_digest, authorized_at, authorized_by_operation_id, authorized_by_actor, platform_os, platform_arch, platform_libc, entrypoints, installation_id, payload_path, store_root, repair_status, repair_operation_id, repair_attempts, repair_next_attempt_at, repair_last_error_code, created_at, updated_at
`

type QueueDesiredDependencyRepairParams struct {
	OperationID     string             `json:"operation_id"`
	ManualRetry     bool               `json:"manual_retry"`
	BotID           pgtype.UUID        `json:"bot_id"`
	DependencyID    string             `json:"dependency_id"`
	DesiredRevision string             `json:"desired_revision"`
	NowAt           pgtype.Timestamptz `json:"now_at"`
}

func (q *Queries) QueueDesiredDependencyRepair(ctx context.Context, arg QueueDesiredDependencyRepairParams) (BotDependencyDesiredInstallation, error) {
	row := q.db.QueryRow(ctx, queueDesiredDependencyRepair,
		arg.OperationID,
		arg.ManualRetry,
		arg.BotID,
		arg.DependencyID,
		arg.DesiredRevision,
		arg.NowAt,
	)
	var i BotDependencyDesiredInstallation
	err := row.Scan(
		&i.TeamID,
		&i.BotID,
		&i.DependencyID,
		&i.DesiredRevision,
		&i.Version,
		&i.SourceUrl,
		&i.RegistryID,
		&i.DefinitionRevision,
		&i.ManifestDigest,
		&i.AuthorizedAt,
		&i.AuthorizedByOperationID,
		&i.AuthorizedByActor,
		&i.PlatformOs,
		&i.PlatformArch,
		&i.PlatformLibc,
		&i.Entrypoints,
		&i.InstallationID,
		&i.PayloadPath,
		&i.StoreRoot,
		&i.RepairStatus,
		&i.RepairOperationID,
		&i.RepairAttempts,
		&i.RepairNextAttemptAt,
		&i.RepairLastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeDesiredDependencyInstallation = `-- name: RevokeDesiredDependencyInstallation :execrows
WITH removed AS (
  DELETE FROM bot_dependency_desired_installations d
  WHERE d.team_id = public.memoh_current_team_id() AND d.bot_id = $3 AND d.dependency_id = $4
    AND EXISTS (SELECT 1 FROM bot_dependency_installations i WHERE i.team_id = d.team_id AND i.bot_id = d.bot_id AND i.dependency_id = d.dependency_id AND i.operation_id = $1 AND i.status = 'removing')
  RETURNING team_id, bot_id, dependency_id, desired_revision, version, source_url, registry_id, definition_revision, manifest_digest, authorized_at, authorized_by_operation_id, authorized_by_actor, platform_os, platform_arch, platform_libc, entrypoints, installation_id, payload_path, store_root, repair_status, repair_operation_id, repair_attempts, repair_next_attempt_at, repair_last_error_code, created_at, updated_at
)
INSERT INTO bot_dependency_authorization_events (bot_id, dependency_id, operation_id, action, actor, version, source_url, registry_id, definition_revision, manifest_digest)
SELECT bot_id, dependency_id, $1, 'revoke', $2, version, source_url, registry_id, definition_revision, manifest_digest FROM removed
ON CONFLICT DO NOTHING
`

type RevokeDesiredDependencyInstallationParams struct {
	OperationID  string      `json:"operation_id"`
	Actor        string      `json:"actor"`
	BotID        pgtype.UUID `json:"bot_id"`
	DependencyID string      `json:"dependency_id"`
}

func (q *Queries) RevokeDesiredDependencyInstallation(ctx context.Context, arg RevokeDesiredDependencyInstallationParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeDesiredDependencyInstallation,
		arg.OperationID,
		arg.Actor,
		arg.BotID,
		arg.DependencyID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setDesiredDependencyRepairResult = `-- name: SetDesiredDependencyRepairResult :one
UPDATE bot_dependency_desired_installations
SET repair_status = $1,
    repair_operation_id = '', repair_attempts = $2,
    repair_next_attempt_at = $3::timestamptz,
    repair_last_error_code = $4, updated_at = now()
WHERE team_id = public.memoh_current_team_id()
  AND bot_id = $5 AND dependency_id = $6
  AND desired_revision = $7
  AND repair_operation_id = $8
  AND repair_status = $9
RETURNING team_id, bot_id, dependency_id, desired_revision, version, source_url, registry_id, definition_revision, manifest_digest, authorized_at, authorized_by_operation_id, authorized_by_actor, platform_os, platform_arch, platform_libc, entrypoints, installation_id, payload_path, store_root, repair_status, repair_operation_id, repair_attempts, repair_next_attempt_at, repair_last_error_code, created_at, updated_at
`

type SetDesiredDependencyRepairResultParams struct {
	RepairStatus         string             `json:"repair_status"`
	RepairAttempts       int32              `json:"repair_attempts"`
	RepairNextAttemptAt  pgtype.Timestamptz `json:"repair_next_attempt_at"`
	RepairLastErrorCode  string             `json:"repair_last_error_code"`
	BotID                pgtype.UUID        `json:"bot_id"`
	DependencyID         string             `json:"dependency_id"`
	DesiredRevision      string             `json:"desired_revision"`
	OperationID          string             `json:"operation_id"`
	ExpectedRepairStatus string             `json:"expected_repair_status"`
}

func (q *Queries) SetDesiredDependencyRepairResult(ctx context.Context, arg SetDesiredDependencyRepairResultParams) (BotDependencyDesiredInstallation, error) {
	row := q.db.QueryRow(ctx, setDesiredDependencyRepairResult,
		arg.RepairStatus,
		arg.RepairAttempts,
		arg.RepairNextAttemptAt,
		arg.RepairLastErrorCode,
		arg.BotID,
		arg.DependencyID,
		arg.DesiredRevision,
		arg.OperationID,
		arg.ExpectedRepairStatus,
	)
	var i BotDependencyDesiredInstallation
	err := row.Scan(
		&i.TeamID,
		&i.BotID,
		&i.DependencyID,
		&i.DesiredRevision,
		&i.Version,
		&i.SourceUrl,
		&i.RegistryID,
		&i.DefinitionRevision,
		&i.ManifestDigest,
		&i.AuthorizedAt,
		&i.AuthorizedByOperationID,
		&i.AuthorizedByActor,
		&i.PlatformOs,
		&i.PlatformArch,
		&i.PlatformLibc,
		&i.Entrypoints,
		&i.InstallationID,
		&i.PayloadPath,
		&i.StoreRoot,
		&i.RepairStatus,
		&i.RepairOperationID,
		&i.RepairAttempts,
		&i.RepairNextAttemptAt,
		&i.RepairLastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
