// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSettingsByBotID = `-- name: GetSettingsByBotID :one
SELECT
  id AS bot_id,
  language,
  reasoning_enabled,
  reasoning_effort,
  heartbeat_enabled,
  heartbeat_interval,
  heartbeat_prompt,
  compaction_enabled,
  compaction_threshold,
  compaction_ratio,
  timezone,
  chat_model_id,
  chat_runtime,
  chat_acp_agent_id,
  chat_acp_project_path,
  chat_acp_project_mode,
  heartbeat_model_id,
  compaction_model_id,
  search_provider_id,
  fetch_provider_id,
  memory_provider_id,
  image_model_id,
  tts_model_id,
  transcription_model_id,
  video_model_id,
  persist_full_tool_results,
  show_tool_calls_in_im,
  tool_approval_config,
  display_enabled,
  overlay_provider,
  overlay_enabled,
  overlay_config,
  command_ui_language
FROM api.bots
WHERE team_id = iam.memoh_current_team_id() AND id = $1
`

type GetSettingsByBotIDRow struct {
	BotID                  pgtype.UUID `json:"bot_id"`
	Language               string      `json:"language"`
	ReasoningEnabled       bool        `json:"reasoning_enabled"`
	ReasoningEffort        string      `json:"reasoning_effort"`
	HeartbeatEnabled       bool        `json:"heartbeat_enabled"`
	HeartbeatInterval      int32       `json:"heartbeat_interval"`
	HeartbeatPrompt        string      `json:"heartbeat_prompt"`
	CompactionEnabled      bool        `json:"compaction_enabled"`
	CompactionThreshold    int32       `json:"compaction_threshold"`
	CompactionRatio        int32       `json:"compaction_ratio"`
	Timezone               pgtype.Text `json:"timezone"`
	ChatModelID            pgtype.UUID `json:"chat_model_id"`
	ChatRuntime            string      `json:"chat_runtime"`
	ChatAcpAgentID         pgtype.Text `json:"chat_acp_agent_id"`
	ChatAcpProjectPath     string      `json:"chat_acp_project_path"`
	ChatAcpProjectMode     string      `json:"chat_acp_project_mode"`
	HeartbeatModelID       pgtype.UUID `json:"heartbeat_model_id"`
	CompactionModelID      pgtype.UUID `json:"compaction_model_id"`
	SearchProviderID       pgtype.UUID `json:"search_provider_id"`
	FetchProviderID        pgtype.UUID `json:"fetch_provider_id"`
	MemoryProviderID       pgtype.UUID `json:"memory_provider_id"`
	ImageModelID           pgtype.UUID `json:"image_model_id"`
	TtsModelID             pgtype.UUID `json:"tts_model_id"`
	TranscriptionModelID   pgtype.UUID `json:"transcription_model_id"`
	VideoModelID           pgtype.UUID `json:"video_model_id"`
	PersistFullToolResults bool        `json:"persist_full_tool_results"`
	ShowToolCallsInIm      bool        `json:"show_tool_calls_in_im"`
	ToolApprovalConfig     []byte      `json:"tool_approval_config"`
	DisplayEnabled         bool        `json:"display_enabled"`
	OverlayProvider        string      `json:"overlay_provider"`
	OverlayEnabled         bool        `json:"overlay_enabled"`
	OverlayConfig          []byte      `json:"overlay_config"`
	CommandUiLanguage      string      `json:"command_ui_language"`
}

func (q *Queries) GetSettingsByBotID(ctx context.Context, id pgtype.UUID) (GetSettingsByBotIDRow, error) {
	row := q.db.QueryRow(ctx, getSettingsByBotID, id)
	var i GetSettingsByBotIDRow
	err := row.Scan(
		&i.BotID,
		&i.Language,
		&i.ReasoningEnabled,
		&i.ReasoningEffort,
		&i.HeartbeatEnabled,
		&i.HeartbeatInterval,
		&i.HeartbeatPrompt,
		&i.CompactionEnabled,
		&i.CompactionThreshold,
		&i.CompactionRatio,
		&i.Timezone,
		&i.ChatModelID,
		&i.ChatRuntime,
		&i.ChatAcpAgentID,
		&i.ChatAcpProjectPath,
		&i.ChatAcpProjectMode,
		&i.HeartbeatModelID,
		&i.CompactionModelID,
		&i.SearchProviderID,
		&i.FetchProviderID,
		&i.MemoryProviderID,
		&i.ImageModelID,
		&i.TtsModelID,
		&i.TranscriptionModelID,
		&i.VideoModelID,
		&i.PersistFullToolResults,
		&i.ShowToolCallsInIm,
		&i.ToolApprovalConfig,
		&i.DisplayEnabled,
		&i.OverlayProvider,
		&i.OverlayEnabled,
		&i.OverlayConfig,
		&i.CommandUiLanguage,
	)
	return i, err
}

const upsertBotSettings = `-- name: UpsertBotSettings :one
UPDATE api.bots
SET language = $1,
    reasoning_enabled = $2,
    reasoning_effort = $3,
    heartbeat_enabled = $4,
    heartbeat_interval = $5,
    heartbeat_prompt = $6,
    compaction_enabled = $7,
    compaction_threshold = $8,
    compaction_ratio = $9,
    timezone = COALESCE($10::text, api.bots.timezone),
    chat_model_id = COALESCE($11::uuid, api.bots.chat_model_id),
    chat_runtime = $12,
    chat_acp_agent_id = $13::text,
    chat_acp_project_path = $14,
    chat_acp_project_mode = $15,
    heartbeat_model_id = COALESCE($16::uuid, api.bots.heartbeat_model_id),
    compaction_model_id = COALESCE($17::uuid, api.bots.compaction_model_id),
    search_provider_id = COALESCE($18::uuid, api.bots.search_provider_id),
    fetch_provider_id = CASE
      WHEN $19::boolean THEN $20::uuid
      ELSE api.bots.fetch_provider_id
    END,
    memory_provider_id = COALESCE($21::uuid, api.bots.memory_provider_id),
    image_model_id = COALESCE($22::uuid, api.bots.image_model_id),
    tts_model_id = COALESCE($23::uuid, api.bots.tts_model_id),
    transcription_model_id = COALESCE($24::uuid, api.bots.transcription_model_id),
    video_model_id = COALESCE($25::uuid, api.bots.video_model_id),
    persist_full_tool_results = $26,
    show_tool_calls_in_im = $27,
    tool_approval_config = $28,
    display_enabled = $29,
    overlay_provider = $30,
    overlay_enabled = $31,
    overlay_config = $32,
    command_ui_language = $33,
    updated_at = now()
WHERE team_id = iam.memoh_current_team_id() AND id = $34
RETURNING
  id AS bot_id,
  language,
  reasoning_enabled,
  reasoning_effort,
  heartbeat_enabled,
  heartbeat_interval,
  heartbeat_prompt,
  compaction_enabled,
  compaction_threshold,
  compaction_ratio,
  timezone,
  chat_model_id,
  chat_runtime,
  chat_acp_agent_id,
  chat_acp_project_path,
  chat_acp_project_mode,
  heartbeat_model_id,
  compaction_model_id,
  search_provider_id,
  fetch_provider_id,
  memory_provider_id,
  image_model_id,
  tts_model_id,
  transcription_model_id,
  video_model_id,
  persist_full_tool_results,
  show_tool_calls_in_im,
  tool_approval_config,
  display_enabled,
  overlay_provider,
  overlay_enabled,
  overlay_config,
  command_ui_language
`

type UpsertBotSettingsParams struct {
	Language               string      `json:"language"`
	ReasoningEnabled       bool        `json:"reasoning_enabled"`
	ReasoningEffort        string      `json:"reasoning_effort"`
	HeartbeatEnabled       bool        `json:"heartbeat_enabled"`
	HeartbeatInterval      int32       `json:"heartbeat_interval"`
	HeartbeatPrompt        string      `json:"heartbeat_prompt"`
	CompactionEnabled      bool        `json:"compaction_enabled"`
	CompactionThreshold    int32       `json:"compaction_threshold"`
	CompactionRatio        int32       `json:"compaction_ratio"`
	Timezone               pgtype.Text `json:"timezone"`
	ChatModelID            pgtype.UUID `json:"chat_model_id"`
	ChatRuntime            string      `json:"chat_runtime"`
	ChatAcpAgentID         pgtype.Text `json:"chat_acp_agent_id"`
	ChatAcpProjectPath     string      `json:"chat_acp_project_path"`
	ChatAcpProjectMode     string      `json:"chat_acp_project_mode"`
	HeartbeatModelID       pgtype.UUID `json:"heartbeat_model_id"`
	CompactionModelID      pgtype.UUID `json:"compaction_model_id"`
	SearchProviderID       pgtype.UUID `json:"search_provider_id"`
	FetchProviderIDSet     bool        `json:"fetch_provider_id_set"`
	FetchProviderID        pgtype.UUID `json:"fetch_provider_id"`
	MemoryProviderID       pgtype.UUID `json:"memory_provider_id"`
	ImageModelID           pgtype.UUID `json:"image_model_id"`
	TtsModelID             pgtype.UUID `json:"tts_model_id"`
	TranscriptionModelID   pgtype.UUID `json:"transcription_model_id"`
	VideoModelID           pgtype.UUID `json:"video_model_id"`
	PersistFullToolResults bool        `json:"persist_full_tool_results"`
	ShowToolCallsInIm      bool        `json:"show_tool_calls_in_im"`
	ToolApprovalConfig     []byte      `json:"tool_approval_config"`
	DisplayEnabled         bool        `json:"display_enabled"`
	OverlayProvider        string      `json:"overlay_provider"`
	OverlayEnabled         bool        `json:"overlay_enabled"`
	OverlayConfig          []byte      `json:"overlay_config"`
	CommandUiLanguage      string      `json:"command_ui_language"`
	ID                     pgtype.UUID `json:"id"`
}

type UpsertBotSettingsRow struct {
	BotID                  pgtype.UUID `json:"bot_id"`
	Language               string      `json:"language"`
	ReasoningEnabled       bool        `json:"reasoning_enabled"`
	ReasoningEffort        string      `json:"reasoning_effort"`
	HeartbeatEnabled       bool        `json:"heartbeat_enabled"`
	HeartbeatInterval      int32       `json:"heartbeat_interval"`
	HeartbeatPrompt        string      `json:"heartbeat_prompt"`
	CompactionEnabled      bool        `json:"compaction_enabled"`
	CompactionThreshold    int32       `json:"compaction_threshold"`
	CompactionRatio        int32       `json:"compaction_ratio"`
	Timezone               pgtype.Text `json:"timezone"`
	ChatModelID            pgtype.UUID `json:"chat_model_id"`
	ChatRuntime            string      `json:"chat_runtime"`
	ChatAcpAgentID         pgtype.Text `json:"chat_acp_agent_id"`
	ChatAcpProjectPath     string      `json:"chat_acp_project_path"`
	ChatAcpProjectMode     string      `json:"chat_acp_project_mode"`
	HeartbeatModelID       pgtype.UUID `json:"heartbeat_model_id"`
	CompactionModelID      pgtype.UUID `json:"compaction_model_id"`
	SearchProviderID       pgtype.UUID `json:"search_provider_id"`
	FetchProviderID        pgtype.UUID `json:"fetch_provider_id"`
	MemoryProviderID       pgtype.UUID `json:"memory_provider_id"`
	ImageModelID           pgtype.UUID `json:"image_model_id"`
	TtsModelID             pgtype.UUID `json:"tts_model_id"`
	TranscriptionModelID   pgtype.UUID `json:"transcription_model_id"`
	VideoModelID           pgtype.UUID `json:"video_model_id"`
	PersistFullToolResults bool        `json:"persist_full_tool_results"`
	ShowToolCallsInIm      bool        `json:"show_tool_calls_in_im"`
	ToolApprovalConfig     []byte      `json:"tool_approval_config"`
	DisplayEnabled         bool        `json:"display_enabled"`
	OverlayProvider        string      `json:"overlay_provider"`
	OverlayEnabled         bool        `json:"overlay_enabled"`
	OverlayConfig          []byte      `json:"overlay_config"`
	CommandUiLanguage      string      `json:"command_ui_language"`
}

func (q *Queries) UpsertBotSettings(ctx context.Context, arg UpsertBotSettingsParams) (UpsertBotSettingsRow, error) {
	row := q.db.QueryRow(ctx, upsertBotSettings,
		arg.Language,
		arg.ReasoningEnabled,
		arg.ReasoningEffort,
		arg.HeartbeatEnabled,
		arg.HeartbeatInterval,
		arg.HeartbeatPrompt,
		arg.CompactionEnabled,
		arg.CompactionThreshold,
		arg.CompactionRatio,
		arg.Timezone,
		arg.ChatModelID,
		arg.ChatRuntime,
		arg.ChatAcpAgentID,
		arg.ChatAcpProjectPath,
		arg.ChatAcpProjectMode,
		arg.HeartbeatModelID,
		arg.CompactionModelID,
		arg.SearchProviderID,
		arg.FetchProviderIDSet,
		arg.FetchProviderID,
		arg.MemoryProviderID,
		arg.ImageModelID,
		arg.TtsModelID,
		arg.TranscriptionModelID,
		arg.VideoModelID,
		arg.PersistFullToolResults,
		arg.ShowToolCallsInIm,
		arg.ToolApprovalConfig,
		arg.DisplayEnabled,
		arg.OverlayProvider,
		arg.OverlayEnabled,
		arg.OverlayConfig,
		arg.CommandUiLanguage,
		arg.ID,
	)
	var i UpsertBotSettingsRow
	err := row.Scan(
		&i.BotID,
		&i.Language,
		&i.ReasoningEnabled,
		&i.ReasoningEffort,
		&i.HeartbeatEnabled,
		&i.HeartbeatInterval,
		&i.HeartbeatPrompt,
		&i.CompactionEnabled,
		&i.CompactionThreshold,
		&i.CompactionRatio,
		&i.Timezone,
		&i.ChatModelID,
		&i.ChatRuntime,
		&i.ChatAcpAgentID,
		&i.ChatAcpProjectPath,
		&i.ChatAcpProjectMode,
		&i.HeartbeatModelID,
		&i.CompactionModelID,
		&i.SearchProviderID,
		&i.FetchProviderID,
		&i.MemoryProviderID,
		&i.ImageModelID,
		&i.TtsModelID,
		&i.TranscriptionModelID,
		&i.VideoModelID,
		&i.PersistFullToolResults,
		&i.ShowToolCallsInIm,
		&i.ToolApprovalConfig,
		&i.DisplayEnabled,
		&i.OverlayProvider,
		&i.OverlayEnabled,
		&i.OverlayConfig,
		&i.CommandUiLanguage,
	)
	return i, err
}
