// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_channel_bindings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserChannelBinding = `-- name: GetUserChannelBinding :one
SELECT id, user_id, channel_type, config, created_at, updated_at, team_id
FROM api.user_channel_bindings
WHERE team_id = iam.memoh_current_team_id() AND user_id = $1 AND channel_type = $2
LIMIT 1
`

type GetUserChannelBindingParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	ChannelType string      `json:"channel_type"`
}

func (q *Queries) GetUserChannelBinding(ctx context.Context, arg GetUserChannelBindingParams) (ApiUserChannelBinding, error) {
	row := q.db.QueryRow(ctx, getUserChannelBinding, arg.UserID, arg.ChannelType)
	var i ApiUserChannelBinding
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChannelType,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
	)
	return i, err
}

const listUserChannelBindingsByPlatform = `-- name: ListUserChannelBindingsByPlatform :many
SELECT id, user_id, channel_type, config, created_at, updated_at, team_id
FROM api.user_channel_bindings
WHERE team_id = iam.memoh_current_team_id() AND channel_type = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUserChannelBindingsByPlatform(ctx context.Context, channelType string) ([]ApiUserChannelBinding, error) {
	rows, err := q.db.Query(ctx, listUserChannelBindingsByPlatform, channelType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiUserChannelBinding
	for rows.Next() {
		var i ApiUserChannelBinding
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChannelType,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserChannelBinding = `-- name: UpsertUserChannelBinding :one
INSERT INTO api.user_channel_bindings (user_id, channel_type, config)
VALUES ($1, $2, $3)
ON CONFLICT (team_id, user_id, channel_type)
DO UPDATE SET
  config = EXCLUDED.config,
  updated_at = now()
RETURNING id, user_id, channel_type, config, created_at, updated_at, team_id
`

type UpsertUserChannelBindingParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	ChannelType string      `json:"channel_type"`
	Config      []byte      `json:"config"`
}

func (q *Queries) UpsertUserChannelBinding(ctx context.Context, arg UpsertUserChannelBindingParams) (ApiUserChannelBinding, error) {
	row := q.db.QueryRow(ctx, upsertUserChannelBinding, arg.UserID, arg.ChannelType, arg.Config)
	var i ApiUserChannelBinding
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChannelType,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamID,
	)
	return i, err
}
