// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: internal/rpc/runtimepb/runtime.proto

package runtimepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RuntimeService_Call_FullMethodName              = "/memoh.runtime.v1.RuntimeService/Call"
	RuntimeService_ResolveAttachment_FullMethodName = "/memoh.runtime.v1.RuntimeService/ResolveAttachment"
	RuntimeService_ReadAttachment_FullMethodName    = "/memoh.runtime.v1.RuntimeService/ReadAttachment"
)

// RuntimeServiceClient is the client API for RuntimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RuntimeService is the narrow control plane shared by the Server and Channel
// processes. Method names are stable protocol identifiers; payloads are JSON
// encodings of package-owned DTOs, never database or Fx types.
type RuntimeServiceClient interface {
	Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error)
	ResolveAttachment(ctx context.Context, in *ResolveAttachmentRequest, opts ...grpc.CallOption) (*ResolveAttachmentResponse, error)
	ReadAttachment(ctx context.Context, in *ReadAttachmentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AttachmentChunk], error)
}

type runtimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRuntimeServiceClient(cc grpc.ClientConnInterface) RuntimeServiceClient {
	return &runtimeServiceClient{cc}
}

func (c *runtimeServiceClient) Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallResponse)
	err := c.cc.Invoke(ctx, RuntimeService_Call_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) ResolveAttachment(ctx context.Context, in *ResolveAttachmentRequest, opts ...grpc.CallOption) (*ResolveAttachmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveAttachmentResponse)
	err := c.cc.Invoke(ctx, RuntimeService_ResolveAttachment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeServiceClient) ReadAttachment(ctx context.Context, in *ReadAttachmentRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AttachmentChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RuntimeService_ServiceDesc.Streams[0], RuntimeService_ReadAttachment_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadAttachmentRequest, AttachmentChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuntimeService_ReadAttachmentClient = grpc.ServerStreamingClient[AttachmentChunk]

// RuntimeServiceServer is the server API for RuntimeService service.
// All implementations must embed UnimplementedRuntimeServiceServer
// for forward compatibility.
//
// RuntimeService is the narrow control plane shared by the Server and Channel
// processes. Method names are stable protocol identifiers; payloads are JSON
// encodings of package-owned DTOs, never database or Fx types.
type RuntimeServiceServer interface {
	Call(context.Context, *CallRequest) (*CallResponse, error)
	ResolveAttachment(context.Context, *ResolveAttachmentRequest) (*ResolveAttachmentResponse, error)
	ReadAttachment(*ReadAttachmentRequest, grpc.ServerStreamingServer[AttachmentChunk]) error
	mustEmbedUnimplementedRuntimeServiceServer()
}

// UnimplementedRuntimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuntimeServiceServer struct{}

func (UnimplementedRuntimeServiceServer) Call(context.Context, *CallRequest) (*CallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedRuntimeServiceServer) ResolveAttachment(context.Context, *ResolveAttachmentRequest) (*ResolveAttachmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveAttachment not implemented")
}
func (UnimplementedRuntimeServiceServer) ReadAttachment(*ReadAttachmentRequest, grpc.ServerStreamingServer[AttachmentChunk]) error {
	return status.Error(codes.Unimplemented, "method ReadAttachment not implemented")
}
func (UnimplementedRuntimeServiceServer) mustEmbedUnimplementedRuntimeServiceServer() {}
func (UnimplementedRuntimeServiceServer) testEmbeddedByValue()                        {}

// UnsafeRuntimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuntimeServiceServer will
// result in compilation errors.
type UnsafeRuntimeServiceServer interface {
	mustEmbedUnimplementedRuntimeServiceServer()
}

func RegisterRuntimeServiceServer(s grpc.ServiceRegistrar, srv RuntimeServiceServer) {
	// If the following call panics, it indicates UnimplementedRuntimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RuntimeService_ServiceDesc, srv)
}

func _RuntimeService_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_Call_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).Call(ctx, req.(*CallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_ResolveAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveAttachmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServiceServer).ResolveAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeService_ResolveAttachment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServiceServer).ResolveAttachment(ctx, req.(*ResolveAttachmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeService_ReadAttachment_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadAttachmentRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RuntimeServiceServer).ReadAttachment(m, &grpc.GenericServerStream[ReadAttachmentRequest, AttachmentChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuntimeService_ReadAttachmentServer = grpc.ServerStreamingServer[AttachmentChunk]

// RuntimeService_ServiceDesc is the grpc.ServiceDesc for RuntimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuntimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "memoh.runtime.v1.RuntimeService",
	HandlerType: (*RuntimeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _RuntimeService_Call_Handler,
		},
		{
			MethodName: "ResolveAttachment",
			Handler:    _RuntimeService_ResolveAttachment_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadAttachment",
			Handler:       _RuntimeService_ReadAttachment_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/rpc/runtimepb/runtime.proto",
}
