-- name: GetSettingsByBotID :one
SELECT
  id AS bot_id,
  language,
  reasoning_enabled,
  reasoning_effort,
  heartbeat_enabled,
  heartbeat_interval,
  heartbeat_prompt,
  compaction_enabled,
  compaction_threshold,
  compaction_ratio,
  timezone,
  chat_model_id,
  chat_runtime,
  chat_acp_agent_id,
  chat_acp_project_path,
  chat_acp_project_mode,
  heartbeat_model_id,
  compaction_model_id,
  search_provider_id,
  fetch_provider_id,
  memory_provider_id,
  image_model_id,
  tts_model_id,
  transcription_model_id,
  video_model_id,
  persist_full_tool_results,
  show_tool_calls_in_im,
  tool_approval_config,
  display_enabled,
  overlay_provider,
  overlay_enabled,
  overlay_config,
  command_ui_language
FROM api.bots
WHERE team_id = iam.memoh_current_team_id() AND id = $1;

-- name: UpsertBotSettings :one
UPDATE api.bots
SET language = sqlc.arg(language),
    reasoning_enabled = sqlc.arg(reasoning_enabled),
    reasoning_effort = sqlc.arg(reasoning_effort),
    heartbeat_enabled = sqlc.arg(heartbeat_enabled),
    heartbeat_interval = sqlc.arg(heartbeat_interval),
    heartbeat_prompt = sqlc.arg(heartbeat_prompt),
    compaction_enabled = sqlc.arg(compaction_enabled),
    compaction_threshold = sqlc.arg(compaction_threshold),
    compaction_ratio = sqlc.arg(compaction_ratio),
    timezone = COALESCE(sqlc.narg(timezone)::text, api.bots.timezone),
    chat_model_id = COALESCE(sqlc.narg(chat_model_id)::uuid, api.bots.chat_model_id),
    chat_runtime = sqlc.arg(chat_runtime),
    chat_acp_agent_id = sqlc.narg(chat_acp_agent_id)::text,
    chat_acp_project_path = sqlc.arg(chat_acp_project_path),
    chat_acp_project_mode = sqlc.arg(chat_acp_project_mode),
    heartbeat_model_id = COALESCE(sqlc.narg(heartbeat_model_id)::uuid, api.bots.heartbeat_model_id),
    compaction_model_id = COALESCE(sqlc.narg(compaction_model_id)::uuid, api.bots.compaction_model_id),
    search_provider_id = COALESCE(sqlc.narg(search_provider_id)::uuid, api.bots.search_provider_id),
    fetch_provider_id = CASE
      WHEN sqlc.arg(fetch_provider_id_set)::boolean THEN sqlc.narg(fetch_provider_id)::uuid
      ELSE api.bots.fetch_provider_id
    END,
    memory_provider_id = COALESCE(sqlc.narg(memory_provider_id)::uuid, api.bots.memory_provider_id),
    image_model_id = COALESCE(sqlc.narg(image_model_id)::uuid, api.bots.image_model_id),
    tts_model_id = COALESCE(sqlc.narg(tts_model_id)::uuid, api.bots.tts_model_id),
    transcription_model_id = COALESCE(sqlc.narg(transcription_model_id)::uuid, api.bots.transcription_model_id),
    video_model_id = COALESCE(sqlc.narg(video_model_id)::uuid, api.bots.video_model_id),
    persist_full_tool_results = sqlc.arg(persist_full_tool_results),
    show_tool_calls_in_im = sqlc.arg(show_tool_calls_in_im),
    tool_approval_config = sqlc.arg(tool_approval_config),
    display_enabled = sqlc.arg(display_enabled),
    overlay_provider = sqlc.arg(overlay_provider),
    overlay_enabled = sqlc.arg(overlay_enabled),
    overlay_config = sqlc.arg(overlay_config),
    command_ui_language = sqlc.arg(command_ui_language),
    updated_at = now()
WHERE team_id = iam.memoh_current_team_id() AND id = sqlc.arg(id)
RETURNING
  id AS bot_id,
  language,
  reasoning_enabled,
  reasoning_effort,
  heartbeat_enabled,
  heartbeat_interval,
  heartbeat_prompt,
  compaction_enabled,
  compaction_threshold,
  compaction_ratio,
  timezone,
  chat_model_id,
  chat_runtime,
  chat_acp_agent_id,
  chat_acp_project_path,
  chat_acp_project_mode,
  heartbeat_model_id,
  compaction_model_id,
  search_provider_id,
  fetch_provider_id,
  memory_provider_id,
  image_model_id,
  tts_model_id,
  transcription_model_id,
  video_model_id,
  persist_full_tool_results,
  show_tool_calls_in_im,
  tool_approval_config,
  display_enabled,
  overlay_provider,
  overlay_enabled,
  overlay_config,
  command_ui_language;
