// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MemoryMemoryEdge struct {
	ID        int64              `json:"id"`
	BotID     pgtype.UUID        `json:"bot_id"`
	SrcNode   string             `json:"src_node"`
	DstNode   string             `json:"dst_node"`
	Rel       string             `json:"rel"`
	Weight    float32            `json:"weight"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	TeamID    pgtype.UUID        `json:"team_id"`
}

type MemoryMemoryNode struct {
	ID               string             `json:"id"`
	BotID            pgtype.UUID        `json:"bot_id"`
	Body             string             `json:"body"`
	Hash             string             `json:"hash"`
	Layer            string             `json:"layer"`
	FactType         string             `json:"fact_type"`
	Subject          string             `json:"subject"`
	Confidence       float32            `json:"confidence"`
	Metadata         []byte             `json:"metadata"`
	SourceMessageIds []byte             `json:"source_message_ids"`
	ProfileRef       string             `json:"profile_ref"`
	Topic            string             `json:"topic"`
	CapturedAt       pgtype.Timestamptz `json:"captured_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	TeamID           pgtype.UUID        `json:"team_id"`
}

type MemoryMemoryProvider struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Provider  string             `json:"provider"`
	Config    []byte             `json:"config"`
	IsDefault bool               `json:"is_default"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	TeamID    pgtype.UUID        `json:"team_id"`
}
