// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ChannelBotChannelConfig struct {
	ID               pgtype.UUID        `json:"id"`
	BotID            pgtype.UUID        `json:"bot_id"`
	ChannelType      string             `json:"channel_type"`
	Credentials      []byte             `json:"credentials"`
	ExternalIdentity pgtype.Text        `json:"external_identity"`
	SelfIdentity     []byte             `json:"self_identity"`
	Routing          []byte             `json:"routing"`
	Capabilities     []byte             `json:"capabilities"`
	Disabled         bool               `json:"disabled"`
	VerifiedAt       pgtype.Timestamptz `json:"verified_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	TeamID           pgtype.UUID        `json:"team_id"`
}

type ChannelBotEmailBinding struct {
	ID              pgtype.UUID        `json:"id"`
	BotID           pgtype.UUID        `json:"bot_id"`
	EmailProviderID pgtype.UUID        `json:"email_provider_id"`
	EmailAddress    string             `json:"email_address"`
	CanRead         bool               `json:"can_read"`
	CanWrite        bool               `json:"can_write"`
	CanDelete       bool               `json:"can_delete"`
	Config          []byte             `json:"config"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	TeamID          pgtype.UUID        `json:"team_id"`
}

type ChannelBotSessionDiscussCursor struct {
	SessionID      pgtype.UUID        `json:"session_id"`
	BotID          pgtype.UUID        `json:"bot_id"`
	ScopeKey       string             `json:"scope_key"`
	RouteID        pgtype.UUID        `json:"route_id"`
	Source         string             `json:"source"`
	ConsumedCursor int64              `json:"consumed_cursor"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	TeamID         pgtype.UUID        `json:"team_id"`
}

type ChannelBotSessionEvent struct {
	ID                      pgtype.UUID        `json:"id"`
	BotID                   pgtype.UUID        `json:"bot_id"`
	SessionID               pgtype.UUID        `json:"session_id"`
	EventKind               string             `json:"event_kind"`
	EventData               []byte             `json:"event_data"`
	ExternalMessageID       pgtype.Text        `json:"external_message_id"`
	SenderChannelIdentityID pgtype.UUID        `json:"sender_channel_identity_id"`
	ReceivedAtMs            int64              `json:"received_at_ms"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	TeamID                  pgtype.UUID        `json:"team_id"`
}

type ChannelChannelIdentity struct {
	ID               pgtype.UUID        `json:"id"`
	ChannelType      string             `json:"channel_type"`
	ChannelSubjectID string             `json:"channel_subject_id"`
	DisplayName      pgtype.Text        `json:"display_name"`
	AvatarUrl        pgtype.Text        `json:"avatar_url"`
	Metadata         []byte             `json:"metadata"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	TeamID           pgtype.UUID        `json:"team_id"`
}

type ChannelEmailOauthToken struct {
	ID              pgtype.UUID        `json:"id"`
	EmailProviderID pgtype.UUID        `json:"email_provider_id"`
	EmailAddress    string             `json:"email_address"`
	AccessToken     string             `json:"access_token"`
	RefreshToken    string             `json:"refresh_token"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	Scope           string             `json:"scope"`
	State           string             `json:"state"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	TeamID          pgtype.UUID        `json:"team_id"`
}

type ChannelEmailOutbox struct {
	ID          pgtype.UUID        `json:"id"`
	ProviderID  pgtype.UUID        `json:"provider_id"`
	BotID       pgtype.UUID        `json:"bot_id"`
	MessageID   string             `json:"message_id"`
	FromAddress string             `json:"from_address"`
	ToAddresses []byte             `json:"to_addresses"`
	Subject     string             `json:"subject"`
	BodyText    string             `json:"body_text"`
	BodyHtml    string             `json:"body_html"`
	Attachments []byte             `json:"attachments"`
	Status      string             `json:"status"`
	Error       string             `json:"error"`
	SentAt      pgtype.Timestamptz `json:"sent_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	TeamID      pgtype.UUID        `json:"team_id"`
}

type ChannelEmailProvider struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	Provider  string             `json:"provider"`
	Config    []byte             `json:"config"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	TeamID    pgtype.UUID        `json:"team_id"`
}
