// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ModelFetchProvider struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Provider  string             `json:"provider"`
	Config    []byte             `json:"config"`
	Enable    bool               `json:"enable"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	TeamID    pgtype.UUID        `json:"team_id"`
}

type ModelModel struct {
	ID         pgtype.UUID        `json:"id"`
	ModelID    string             `json:"model_id"`
	Name       pgtype.Text        `json:"name"`
	ProviderID pgtype.UUID        `json:"provider_id"`
	Type       string             `json:"type"`
	Enable     bool               `json:"enable"`
	Config     []byte             `json:"config"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	TeamID     pgtype.UUID        `json:"team_id"`
}

type ModelModelVariant struct {
	ID        pgtype.UUID        `json:"id"`
	ModelUuid pgtype.UUID        `json:"model_uuid"`
	VariantID string             `json:"variant_id"`
	Weight    int32              `json:"weight"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	TeamID    pgtype.UUID        `json:"team_id"`
}

type ModelProvider struct {
	ID                 pgtype.UUID        `json:"id"`
	ProviderTemplateID pgtype.UUID        `json:"provider_template_id"`
	Name               string             `json:"name"`
	ClientType         string             `json:"client_type"`
	Icon               pgtype.Text        `json:"icon"`
	Enable             bool               `json:"enable"`
	Config             []byte             `json:"config"`
	Metadata           []byte             `json:"metadata"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	TeamID             pgtype.UUID        `json:"team_id"`
}

type ModelProviderOauthToken struct {
	ID               pgtype.UUID        `json:"id"`
	ProviderID       pgtype.UUID        `json:"provider_id"`
	AccessToken      string             `json:"access_token"`
	RefreshToken     string             `json:"refresh_token"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	Scope            string             `json:"scope"`
	TokenType        string             `json:"token_type"`
	State            string             `json:"state"`
	PkceCodeVerifier string             `json:"pkce_code_verifier"`
	Metadata         []byte             `json:"metadata"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	TeamID           pgtype.UUID        `json:"team_id"`
}

type ModelProviderTemplate struct {
	ID            pgtype.UUID        `json:"id"`
	Key           string             `json:"key"`
	Domain        string             `json:"domain"`
	Name          string             `json:"name"`
	Description   string             `json:"description"`
	Icon          pgtype.Text        `json:"icon"`
	Driver        string             `json:"driver"`
	ConfigSchema  []byte             `json:"config_schema"`
	DefaultConfig []byte             `json:"default_config"`
	Metadata      []byte             `json:"metadata"`
	Source        string             `json:"source"`
	ContentHash   string             `json:"content_hash"`
	SortOrder     int32              `json:"sort_order"`
	Active        bool               `json:"active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type ModelProviderTemplateModel struct {
	ID                 pgtype.UUID        `json:"id"`
	ProviderTemplateID pgtype.UUID        `json:"provider_template_id"`
	ModelID            string             `json:"model_id"`
	Name               string             `json:"name"`
	Type               string             `json:"type"`
	Config             []byte             `json:"config"`
	Metadata           []byte             `json:"metadata"`
	SortOrder          int32              `json:"sort_order"`
	Active             bool               `json:"active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type ModelSearchProvider struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Provider  string             `json:"provider"`
	Config    []byte             `json:"config"`
	Enable    bool               `json:"enable"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	TeamID    pgtype.UUID        `json:"team_id"`
}

type ModelUserProviderOauthToken struct {
	ID               pgtype.UUID        `json:"id"`
	ProviderID       pgtype.UUID        `json:"provider_id"`
	UserID           pgtype.UUID        `json:"user_id"`
	AccessToken      string             `json:"access_token"`
	RefreshToken     string             `json:"refresh_token"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	Scope            string             `json:"scope"`
	TokenType        string             `json:"token_type"`
	State            string             `json:"state"`
	PkceCodeVerifier string             `json:"pkce_code_verifier"`
	Metadata         []byte             `json:"metadata"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	TeamID           pgtype.UUID        `json:"team_id"`
}
