// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.1
// source: internal/rpc/channel/channelpb/channel.proto

// memoh:plane=control

package channelpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChannelAdminService_UpsertConfig_FullMethodName                = "/memoh.channel.ChannelAdminService/UpsertConfig"
	ChannelAdminService_SetStatus_FullMethodName                   = "/memoh.channel.ChannelAdminService/SetStatus"
	ChannelAdminService_DeleteConfig_FullMethodName                = "/memoh.channel.ChannelAdminService/DeleteConfig"
	ChannelAdminService_SetWebhookEndpoint_FullMethodName          = "/memoh.channel.ChannelAdminService/SetWebhookEndpoint"
	ChannelAdminService_ListIdentityProjections_FullMethodName     = "/memoh.channel.ChannelAdminService/ListIdentityProjections"
	ChannelAdminService_ListConversationProjections_FullMethodName = "/memoh.channel.ChannelAdminService/ListConversationProjections"
)

// ChannelAdminServiceClient is the client API for ChannelAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChannelAdminServiceClient interface {
	UpsertConfig(ctx context.Context, in *UpsertConfigRequest, opts ...grpc.CallOption) (*ChannelConfigResponse, error)
	SetStatus(ctx context.Context, in *SetStatusRequest, opts ...grpc.CallOption) (*ChannelConfigResponse, error)
	DeleteConfig(ctx context.Context, in *DeleteConfigRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SetWebhookEndpoint(ctx context.Context, in *SetWebhookEndpointRequest, opts ...grpc.CallOption) (*SetWebhookEndpointResponse, error)
	ListIdentityProjections(ctx context.Context, in *ListIdentityProjectionsRequest, opts ...grpc.CallOption) (*ListIdentityProjectionsResponse, error)
	ListConversationProjections(ctx context.Context, in *ListConversationProjectionsRequest, opts ...grpc.CallOption) (*ListConversationProjectionsResponse, error)
}

type channelAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChannelAdminServiceClient(cc grpc.ClientConnInterface) ChannelAdminServiceClient {
	return &channelAdminServiceClient{cc}
}

func (c *channelAdminServiceClient) UpsertConfig(ctx context.Context, in *UpsertConfigRequest, opts ...grpc.CallOption) (*ChannelConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChannelConfigResponse)
	err := c.cc.Invoke(ctx, ChannelAdminService_UpsertConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelAdminServiceClient) SetStatus(ctx context.Context, in *SetStatusRequest, opts ...grpc.CallOption) (*ChannelConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChannelConfigResponse)
	err := c.cc.Invoke(ctx, ChannelAdminService_SetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelAdminServiceClient) DeleteConfig(ctx context.Context, in *DeleteConfigRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ChannelAdminService_DeleteConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelAdminServiceClient) SetWebhookEndpoint(ctx context.Context, in *SetWebhookEndpointRequest, opts ...grpc.CallOption) (*SetWebhookEndpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetWebhookEndpointResponse)
	err := c.cc.Invoke(ctx, ChannelAdminService_SetWebhookEndpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelAdminServiceClient) ListIdentityProjections(ctx context.Context, in *ListIdentityProjectionsRequest, opts ...grpc.CallOption) (*ListIdentityProjectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIdentityProjectionsResponse)
	err := c.cc.Invoke(ctx, ChannelAdminService_ListIdentityProjections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelAdminServiceClient) ListConversationProjections(ctx context.Context, in *ListConversationProjectionsRequest, opts ...grpc.CallOption) (*ListConversationProjectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConversationProjectionsResponse)
	err := c.cc.Invoke(ctx, ChannelAdminService_ListConversationProjections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChannelAdminServiceServer is the server API for ChannelAdminService service.
// All implementations must embed UnimplementedChannelAdminServiceServer
// for forward compatibility.
type ChannelAdminServiceServer interface {
	UpsertConfig(context.Context, *UpsertConfigRequest) (*ChannelConfigResponse, error)
	SetStatus(context.Context, *SetStatusRequest) (*ChannelConfigResponse, error)
	DeleteConfig(context.Context, *DeleteConfigRequest) (*emptypb.Empty, error)
	SetWebhookEndpoint(context.Context, *SetWebhookEndpointRequest) (*SetWebhookEndpointResponse, error)
	ListIdentityProjections(context.Context, *ListIdentityProjectionsRequest) (*ListIdentityProjectionsResponse, error)
	ListConversationProjections(context.Context, *ListConversationProjectionsRequest) (*ListConversationProjectionsResponse, error)
	mustEmbedUnimplementedChannelAdminServiceServer()
}

// UnimplementedChannelAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChannelAdminServiceServer struct{}

func (UnimplementedChannelAdminServiceServer) UpsertConfig(context.Context, *UpsertConfigRequest) (*ChannelConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertConfig not implemented")
}
func (UnimplementedChannelAdminServiceServer) SetStatus(context.Context, *SetStatusRequest) (*ChannelConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetStatus not implemented")
}
func (UnimplementedChannelAdminServiceServer) DeleteConfig(context.Context, *DeleteConfigRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteConfig not implemented")
}
func (UnimplementedChannelAdminServiceServer) SetWebhookEndpoint(context.Context, *SetWebhookEndpointRequest) (*SetWebhookEndpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetWebhookEndpoint not implemented")
}
func (UnimplementedChannelAdminServiceServer) ListIdentityProjections(context.Context, *ListIdentityProjectionsRequest) (*ListIdentityProjectionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIdentityProjections not implemented")
}
func (UnimplementedChannelAdminServiceServer) ListConversationProjections(context.Context, *ListConversationProjectionsRequest) (*ListConversationProjectionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConversationProjections not implemented")
}
func (UnimplementedChannelAdminServiceServer) mustEmbedUnimplementedChannelAdminServiceServer() {}
func (UnimplementedChannelAdminServiceServer) testEmbeddedByValue()                             {}

// UnsafeChannelAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChannelAdminServiceServer will
// result in compilation errors.
type UnsafeChannelAdminServiceServer interface {
	mustEmbedUnimplementedChannelAdminServiceServer()
}

func RegisterChannelAdminServiceServer(s grpc.ServiceRegistrar, srv ChannelAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedChannelAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChannelAdminService_ServiceDesc, srv)
}

func _ChannelAdminService_UpsertConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelAdminServiceServer).UpsertConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelAdminService_UpsertConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelAdminServiceServer).UpsertConfig(ctx, req.(*UpsertConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelAdminService_SetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelAdminServiceServer).SetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelAdminService_SetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelAdminServiceServer).SetStatus(ctx, req.(*SetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelAdminService_DeleteConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelAdminServiceServer).DeleteConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelAdminService_DeleteConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelAdminServiceServer).DeleteConfig(ctx, req.(*DeleteConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelAdminService_SetWebhookEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetWebhookEndpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelAdminServiceServer).SetWebhookEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelAdminService_SetWebhookEndpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelAdminServiceServer).SetWebhookEndpoint(ctx, req.(*SetWebhookEndpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelAdminService_ListIdentityProjections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIdentityProjectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelAdminServiceServer).ListIdentityProjections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelAdminService_ListIdentityProjections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelAdminServiceServer).ListIdentityProjections(ctx, req.(*ListIdentityProjectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelAdminService_ListConversationProjections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConversationProjectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelAdminServiceServer).ListConversationProjections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelAdminService_ListConversationProjections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelAdminServiceServer).ListConversationProjections(ctx, req.(*ListConversationProjectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChannelAdminService_ServiceDesc is the grpc.ServiceDesc for ChannelAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChannelAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "memoh.channel.ChannelAdminService",
	HandlerType: (*ChannelAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertConfig",
			Handler:    _ChannelAdminService_UpsertConfig_Handler,
		},
		{
			MethodName: "SetStatus",
			Handler:    _ChannelAdminService_SetStatus_Handler,
		},
		{
			MethodName: "DeleteConfig",
			Handler:    _ChannelAdminService_DeleteConfig_Handler,
		},
		{
			MethodName: "SetWebhookEndpoint",
			Handler:    _ChannelAdminService_SetWebhookEndpoint_Handler,
		},
		{
			MethodName: "ListIdentityProjections",
			Handler:    _ChannelAdminService_ListIdentityProjections_Handler,
		},
		{
			MethodName: "ListConversationProjections",
			Handler:    _ChannelAdminService_ListConversationProjections_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/rpc/channel/channelpb/channel.proto",
}

const (
	ChannelDeliveryService_React_FullMethodName = "/memoh.channel.ChannelDeliveryService/React"
)

// ChannelDeliveryServiceClient is the client API for ChannelDeliveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SendMessage is intentionally absent until AD1 and D11 close the complete capability.
type ChannelDeliveryServiceClient interface {
	React(ctx context.Context, in *ReactRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type channelDeliveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChannelDeliveryServiceClient(cc grpc.ClientConnInterface) ChannelDeliveryServiceClient {
	return &channelDeliveryServiceClient{cc}
}

func (c *channelDeliveryServiceClient) React(ctx context.Context, in *ReactRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ChannelDeliveryService_React_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChannelDeliveryServiceServer is the server API for ChannelDeliveryService service.
// All implementations must embed UnimplementedChannelDeliveryServiceServer
// for forward compatibility.
//
// SendMessage is intentionally absent until AD1 and D11 close the complete capability.
type ChannelDeliveryServiceServer interface {
	React(context.Context, *ReactRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedChannelDeliveryServiceServer()
}

// UnimplementedChannelDeliveryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChannelDeliveryServiceServer struct{}

func (UnimplementedChannelDeliveryServiceServer) React(context.Context, *ReactRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method React not implemented")
}
func (UnimplementedChannelDeliveryServiceServer) mustEmbedUnimplementedChannelDeliveryServiceServer() {
}
func (UnimplementedChannelDeliveryServiceServer) testEmbeddedByValue() {}

// UnsafeChannelDeliveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChannelDeliveryServiceServer will
// result in compilation errors.
type UnsafeChannelDeliveryServiceServer interface {
	mustEmbedUnimplementedChannelDeliveryServiceServer()
}

func RegisterChannelDeliveryServiceServer(s grpc.ServiceRegistrar, srv ChannelDeliveryServiceServer) {
	// If the following call panics, it indicates UnimplementedChannelDeliveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChannelDeliveryService_ServiceDesc, srv)
}

func _ChannelDeliveryService_React_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelDeliveryServiceServer).React(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelDeliveryService_React_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelDeliveryServiceServer).React(ctx, req.(*ReactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChannelDeliveryService_ServiceDesc is the grpc.ServiceDesc for ChannelDeliveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChannelDeliveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "memoh.channel.ChannelDeliveryService",
	HandlerType: (*ChannelDeliveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "React",
			Handler:    _ChannelDeliveryService_React_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/rpc/channel/channelpb/channel.proto",
}

const (
	ChannelStatusService_ListConnectionStatuses_FullMethodName = "/memoh.channel.ChannelStatusService/ListConnectionStatuses"
	ChannelStatusService_GetTunnelStatus_FullMethodName        = "/memoh.channel.ChannelStatusService/GetTunnelStatus"
)

// ChannelStatusServiceClient is the client API for ChannelStatusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChannelStatusServiceClient interface {
	ListConnectionStatuses(ctx context.Context, in *ListConnectionStatusesRequest, opts ...grpc.CallOption) (*ListConnectionStatusesResponse, error)
	GetTunnelStatus(ctx context.Context, in *GetTunnelStatusRequest, opts ...grpc.CallOption) (*GetTunnelStatusResponse, error)
}

type channelStatusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChannelStatusServiceClient(cc grpc.ClientConnInterface) ChannelStatusServiceClient {
	return &channelStatusServiceClient{cc}
}

func (c *channelStatusServiceClient) ListConnectionStatuses(ctx context.Context, in *ListConnectionStatusesRequest, opts ...grpc.CallOption) (*ListConnectionStatusesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConnectionStatusesResponse)
	err := c.cc.Invoke(ctx, ChannelStatusService_ListConnectionStatuses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelStatusServiceClient) GetTunnelStatus(ctx context.Context, in *GetTunnelStatusRequest, opts ...grpc.CallOption) (*GetTunnelStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTunnelStatusResponse)
	err := c.cc.Invoke(ctx, ChannelStatusService_GetTunnelStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChannelStatusServiceServer is the server API for ChannelStatusService service.
// All implementations must embed UnimplementedChannelStatusServiceServer
// for forward compatibility.
type ChannelStatusServiceServer interface {
	ListConnectionStatuses(context.Context, *ListConnectionStatusesRequest) (*ListConnectionStatusesResponse, error)
	GetTunnelStatus(context.Context, *GetTunnelStatusRequest) (*GetTunnelStatusResponse, error)
	mustEmbedUnimplementedChannelStatusServiceServer()
}

// UnimplementedChannelStatusServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChannelStatusServiceServer struct{}

func (UnimplementedChannelStatusServiceServer) ListConnectionStatuses(context.Context, *ListConnectionStatusesRequest) (*ListConnectionStatusesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConnectionStatuses not implemented")
}
func (UnimplementedChannelStatusServiceServer) GetTunnelStatus(context.Context, *GetTunnelStatusRequest) (*GetTunnelStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTunnelStatus not implemented")
}
func (UnimplementedChannelStatusServiceServer) mustEmbedUnimplementedChannelStatusServiceServer() {}
func (UnimplementedChannelStatusServiceServer) testEmbeddedByValue()                              {}

// UnsafeChannelStatusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChannelStatusServiceServer will
// result in compilation errors.
type UnsafeChannelStatusServiceServer interface {
	mustEmbedUnimplementedChannelStatusServiceServer()
}

func RegisterChannelStatusServiceServer(s grpc.ServiceRegistrar, srv ChannelStatusServiceServer) {
	// If the following call panics, it indicates UnimplementedChannelStatusServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChannelStatusService_ServiceDesc, srv)
}

func _ChannelStatusService_ListConnectionStatuses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConnectionStatusesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelStatusServiceServer).ListConnectionStatuses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelStatusService_ListConnectionStatuses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelStatusServiceServer).ListConnectionStatuses(ctx, req.(*ListConnectionStatusesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelStatusService_GetTunnelStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTunnelStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelStatusServiceServer).GetTunnelStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelStatusService_GetTunnelStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelStatusServiceServer).GetTunnelStatus(ctx, req.(*GetTunnelStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChannelStatusService_ServiceDesc is the grpc.ServiceDesc for ChannelStatusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChannelStatusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "memoh.channel.ChannelStatusService",
	HandlerType: (*ChannelStatusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListConnectionStatuses",
			Handler:    _ChannelStatusService_ListConnectionStatuses_Handler,
		},
		{
			MethodName: "GetTunnelStatus",
			Handler:    _ChannelStatusService_GetTunnelStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/rpc/channel/channelpb/channel.proto",
}

const (
	ChannelEmailService_RefreshProvider_FullMethodName = "/memoh.channel.ChannelEmailService/RefreshProvider"
	ChannelEmailService_SendEmail_FullMethodName       = "/memoh.channel.ChannelEmailService/SendEmail"
)

// ChannelEmailServiceClient is the client API for ChannelEmailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChannelEmailServiceClient interface {
	RefreshProvider(ctx context.Context, in *RefreshProviderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error)
}

type channelEmailServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChannelEmailServiceClient(cc grpc.ClientConnInterface) ChannelEmailServiceClient {
	return &channelEmailServiceClient{cc}
}

func (c *channelEmailServiceClient) RefreshProvider(ctx context.Context, in *RefreshProviderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ChannelEmailService_RefreshProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelEmailServiceClient) SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendEmailResponse)
	err := c.cc.Invoke(ctx, ChannelEmailService_SendEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChannelEmailServiceServer is the server API for ChannelEmailService service.
// All implementations must embed UnimplementedChannelEmailServiceServer
// for forward compatibility.
type ChannelEmailServiceServer interface {
	RefreshProvider(context.Context, *RefreshProviderRequest) (*emptypb.Empty, error)
	SendEmail(context.Context, *SendEmailRequest) (*SendEmailResponse, error)
	mustEmbedUnimplementedChannelEmailServiceServer()
}

// UnimplementedChannelEmailServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChannelEmailServiceServer struct{}

func (UnimplementedChannelEmailServiceServer) RefreshProvider(context.Context, *RefreshProviderRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshProvider not implemented")
}
func (UnimplementedChannelEmailServiceServer) SendEmail(context.Context, *SendEmailRequest) (*SendEmailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendEmail not implemented")
}
func (UnimplementedChannelEmailServiceServer) mustEmbedUnimplementedChannelEmailServiceServer() {}
func (UnimplementedChannelEmailServiceServer) testEmbeddedByValue()                             {}

// UnsafeChannelEmailServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChannelEmailServiceServer will
// result in compilation errors.
type UnsafeChannelEmailServiceServer interface {
	mustEmbedUnimplementedChannelEmailServiceServer()
}

func RegisterChannelEmailServiceServer(s grpc.ServiceRegistrar, srv ChannelEmailServiceServer) {
	// If the following call panics, it indicates UnimplementedChannelEmailServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChannelEmailService_ServiceDesc, srv)
}

func _ChannelEmailService_RefreshProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelEmailServiceServer).RefreshProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelEmailService_RefreshProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelEmailServiceServer).RefreshProvider(ctx, req.(*RefreshProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelEmailService_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelEmailServiceServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChannelEmailService_SendEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelEmailServiceServer).SendEmail(ctx, req.(*SendEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChannelEmailService_ServiceDesc is the grpc.ServiceDesc for ChannelEmailService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChannelEmailService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "memoh.channel.ChannelEmailService",
	HandlerType: (*ChannelEmailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RefreshProvider",
			Handler:    _ChannelEmailService_RefreshProvider_Handler,
		},
		{
			MethodName: "SendEmail",
			Handler:    _ChannelEmailService_SendEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/rpc/channel/channelpb/channel.proto",
}
