// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type IamUserRole string

const (
	IamUserRoleMember IamUserRole = "member"
	IamUserRoleAdmin  IamUserRole = "admin"
)

func (e *IamUserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IamUserRole(s)
	case string:
		*e = IamUserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for IamUserRole: %T", src)
	}
	return nil
}

type NullIamUserRole struct {
	IamUserRole IamUserRole `json:"iam_user_role"`
	Valid       bool        `json:"valid"` // Valid is true if IamUserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIamUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.IamUserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IamUserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIamUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IamUserRole), nil
}

type IamTeam struct {
	ID        pgtype.UUID        `json:"id"`
	Slug      pgtype.Text        `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Metadata  []byte             `json:"metadata"`
}

type IamTeamAccount struct {
	ID                  pgtype.UUID        `json:"id"`
	Username            pgtype.Text        `json:"username"`
	Email               pgtype.Text        `json:"email"`
	PasswordHash        pgtype.Text        `json:"password_hash"`
	Role                string             `json:"role"`
	DisplayName         pgtype.Text        `json:"display_name"`
	AvatarUrl           pgtype.Text        `json:"avatar_url"`
	Timezone            string             `json:"timezone"`
	LastLoginAt         pgtype.Timestamptz `json:"last_login_at"`
	IsActive            pgtype.Bool        `json:"is_active"`
	Metadata            []byte             `json:"metadata"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	TeamID              pgtype.UUID        `json:"team_id"`
	PrincipalIsActive   bool               `json:"principal_is_active"`
	MembershipIsActive  bool               `json:"membership_is_active"`
	JoinedAt            pgtype.Timestamptz `json:"joined_at"`
	MembershipUpdatedAt pgtype.Timestamptz `json:"membership_updated_at"`
	TitleModelID        pgtype.UUID        `json:"title_model_id"`
}

type IamTeamMember struct {
	TeamID       pgtype.UUID        `json:"team_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Role         string             `json:"role"`
	IsActive     bool               `json:"is_active"`
	TitleModelID pgtype.UUID        `json:"title_model_id"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type IamUser struct {
	ID           pgtype.UUID        `json:"id"`
	Username     pgtype.Text        `json:"username"`
	Email        pgtype.Text        `json:"email"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	DisplayName  pgtype.Text        `json:"display_name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	Timezone     string             `json:"timezone"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	IsActive     bool               `json:"is_active"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
