// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type PlatformUserRole string

const (
	PlatformUserRoleMember PlatformUserRole = "member"
	PlatformUserRoleAdmin  PlatformUserRole = "admin"
)

func (e *PlatformUserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlatformUserRole(s)
	case string:
		*e = PlatformUserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for PlatformUserRole: %T", src)
	}
	return nil
}

type NullPlatformUserRole struct {
	PlatformUserRole PlatformUserRole `json:"platform_user_role"`
	Valid            bool             `json:"valid"` // Valid is true if PlatformUserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlatformUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.PlatformUserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlatformUserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlatformUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlatformUserRole), nil
}

type PlatformTeam struct {
	ID        pgtype.UUID        `json:"id"`
	Slug      pgtype.Text        `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Metadata  []byte             `json:"metadata"`
}

type PlatformTeamAccount struct {
	ID                  pgtype.UUID        `json:"id"`
	Username            pgtype.Text        `json:"username"`
	Email               pgtype.Text        `json:"email"`
	PasswordHash        pgtype.Text        `json:"password_hash"`
	Role                string             `json:"role"`
	DisplayName         pgtype.Text        `json:"display_name"`
	AvatarUrl           pgtype.Text        `json:"avatar_url"`
	Timezone            string             `json:"timezone"`
	DataRoot            pgtype.Text        `json:"data_root"`
	LastLoginAt         pgtype.Timestamptz `json:"last_login_at"`
	IsActive            pgtype.Bool        `json:"is_active"`
	Metadata            []byte             `json:"metadata"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	TeamID              pgtype.UUID        `json:"team_id"`
	PrincipalIsActive   bool               `json:"principal_is_active"`
	MembershipIsActive  bool               `json:"membership_is_active"`
	JoinedAt            pgtype.Timestamptz `json:"joined_at"`
	MembershipUpdatedAt pgtype.Timestamptz `json:"membership_updated_at"`
	TitleModelID        pgtype.UUID        `json:"title_model_id"`
}

type PlatformTeamMember struct {
	TeamID       pgtype.UUID        `json:"team_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Role         string             `json:"role"`
	IsActive     bool               `json:"is_active"`
	DataRoot     pgtype.Text        `json:"data_root"`
	TitleModelID pgtype.UUID        `json:"title_model_id"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type PlatformUser struct {
	ID           pgtype.UUID        `json:"id"`
	Username     pgtype.Text        `json:"username"`
	Email        pgtype.Text        `json:"email"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	DisplayName  pgtype.Text        `json:"display_name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	Timezone     string             `json:"timezone"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
	IsActive     bool               `json:"is_active"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
