import { beforeEach, describe, expect, it, vi } from 'vitest'
import {
  apiErrorStatus,
  isApiErrorAnswered,
  isApiErrorCode,
  parseMemohError,
  resolveApiErrorMessage,
  UserFacingError,
} from '@/utils/api-error'

describe('resolveApiErrorMessage', () => {
  let locale = 'en'

  beforeEach(() => {
    locale = 'en'
    vi.stubGlobal('localStorage', {
      getItem: (key: string) => key === 'language' ? locale : null,
      setItem: vi.fn(),
      removeItem: vi.fn(),
      clear: vi.fn(),
    })
  })

  it('renders ACP feedback i18n keys before raw backend messages', () => {
    locale = 'zh'

    const message = resolveApiErrorMessage({
      body: {
        code: 'no_workspace_exec',
        args: {},
        message: 'raw backend message',
      },
    }, 'fallback')

    expect(message).toBe('你没有执行该 Bot 工作区命令的权限。')
  })

  it('renders ACP feedback when structured payload is nested under message', () => {
    const message = resolveApiErrorMessage({
      message: {
        code: 'no_workspace_exec',
        args: {},
        message: 'raw backend message',
      },
    }, 'fallback')

    expect(message).toBe('You do not have permission to run workspace commands for this bot.')
  })

  it('renders a WebSocket error frame by its top-level code', () => {
    locale = 'zh'

    const message = resolveApiErrorMessage({
      type: 'error',
      code: 'no_workspace_exec',
      args: {},
      message: 'raw backend message',
    }, 'fallback')

    expect(message).toBe('你没有执行该 Bot 工作区命令的权限。')
  })

  it('does not render copy from an i18n_key without a code', () => {
    expect(resolveApiErrorMessage({
      i18n_key: 'chat.externalAgent.noWorkspaceExec',
      message: 'raw backend message',
    }, 'fallback')).toBe('fallback')
  })

  it('reads error_code when code is absent', () => {
    expect(parseMemohError({
      error_code: 'agent.response_timeout',
      error: 'The model did not respond in time. Please try again.',
    })).toMatchObject({ code: 'agent.response_timeout' })
    expect(resolveApiErrorMessage({
      error_code: 'agent.response_timeout',
      error: 'backend fallback',
    }, 'fallback')).toBe('The model did not respond in time. Please try again.')
  })

  it.each([
    'plain detail',
    new Error('plain detail'),
    { detail: 'plain detail' },
    { message: 'plain detail' },
    { response: { data: { error: 'plain detail' } } },
    new SyntaxError('Unexpected token < in JSON at position 0'),
  ])('does not show the text of an error without a code: %s', (error) => {
    expect(resolveApiErrorMessage(error, 'fallback')).toBe('fallback')
    expect(resolveApiErrorMessage(error, 'fallback', { prefixFallback: true })).toBe('fallback')
  })

  it.each([
    [404, 'The requested resource was not found.'],
    [422, 'The request is invalid.'],
    [502, 'Something went wrong on the server. Please try again.'],
  ])('describes an error without a code or fault by its status %d', (status, expected) => {
    const error = { status, message: 'raw gateway text' }

    expect(resolveApiErrorMessage(error, 'fallback')).toBe(expected)
    expect(resolveApiErrorMessage(error, 'Save failed', { prefixFallback: true })).toBe(`Save failed: ${expected}`)
  })

  it('shows the message of a UserFacingError', () => {
    const error = new UserFacingError('Enter at least one GPU device.')

    expect(resolveApiErrorMessage(error, 'fallback')).toBe('Enter at least one GPU device.')
    expect(resolveApiErrorMessage(error, 'Save failed', { prefixFallback: true }))
      .toBe('Save failed: Enter at least one GPU device.')
  })

  it.each(['en', 'zh', 'ja'])('localizes durable runtime notices in %s', (language) => {
    locale = language
    const message = resolveApiErrorMessage({
      code: 'native_history_lost',
      detail: 'backend fallback',
    }, 'fallback')
    expect(message).not.toBe('backend fallback')
    expect(message).not.toBe('fallback')
    expect(message).not.toContain('errors.native_history_lost')
  })

  it.each([
    '<html><head><title>413 Request Entity Too Large</title></head></html>',
    '\n<!DOCTYPE html><html><body>Bad gateway</body></html>',
    new Error('<html><body>nginx</body></html>'),
    { response: { data: { detail: '<HTML><BODY>nginx</BODY></HTML>' } } },
    '<!-- generated by gateway -->\n<!DOCTYPE html><html><body>nginx</body></html>',
    '\n<!-- gateway\nerror -->\n<HTML><BODY>nginx</BODY></HTML>',
    new Error('<!-- proxy --><!-- upstream -->\n<html><body>Bad gateway</body></html>'),
    { response: { data: { detail: '<!-- proxy -->\n<!doctype html><html><body>nginx</body></html>' } } },
  ])('does not display an HTML error page: %s', (error) => {
    expect(resolveApiErrorMessage(error, '无法预览备份')).toBe('无法预览备份')
    expect(resolveApiErrorMessage(error, '无法预览备份', { prefixFallback: true })).toBe('无法预览备份')
  })

  it.each([
    '<html><body>Gateway timeout</body></html>',
    '<!-- proxy -->\n<html><body>Gateway timeout</body></html>',
  ])('prefers a known error code over an HTML detail: %s', (detail) => {
    expect(resolveApiErrorMessage({
      code: 'agent.response_timeout',
      detail,
    }, 'fallback')).toBe('The model did not respond in time. Please try again.')
  })

  it.each([
    ['en', 'Network connection failed. Check your connection and try again.'],
    ['zh', '网络连接失败，请检查网络后重试。'],
    ['ja', 'ネットワークに接続できません。接続を確認してもう一度お試しください。'],
  ])('localizes native fetch failures for %s', (language, expected) => {
    locale = language

    expect(resolveApiErrorMessage(
      new TypeError('NetworkError when attempting to fetch resource.'),
      'fallback',
    )).toBe(expected)
  })

  it.each([
    ['zh', '启动工作区失败，请重试。'],
    ['ja', 'Workspace を起動できませんでした。もう一度お試しください。'],
  ])('localizes workspace errors for %s by code, ignoring a legacy i18n_key', (language, expected) => {
    locale = language

    const message = resolveApiErrorMessage({
      code: 'workspace_start_failed',
      i18n_key: 'bots.container.startFailed',
      args: {},
      message: 'failed to start container: connection refused',
    }, 'fallback')

    expect(message).toBe(expected)
  })

  it.each([
    ['en', 'This name is already taken.'],
    ['zh', '该名称已被占用。'],
    ['ja', 'この名前はすでに使用されています。'],
  ])('derives the localized message from the stable code for %s', (language, expected) => {
    locale = language

    const error = {
      code: 'bot.name_taken',
      args: { field: 'name' },
      detail: 'This name is already taken.',
      request_id: 'req-1',
      status: 409,
    }

    expect(resolveApiErrorMessage(error, 'fallback')).toBe(expected)
    expect(isApiErrorCode(error, 'bot.name_taken')).toBe(true)
    expect(parseMemohError(error)).toEqual({
      code: 'bot.name_taken',
      args: { field: 'name' },
      message: 'This name is already taken.',
      requestId: 'req-1',
      status: 409,
    })
  })

  it.each([
    ['en', 'skill.builtin_read_only', 'Built-in Skills are managed by Memoh and cannot be edited or deleted.'],
    ['zh', 'skill.builtin_read_only', 'Memoh 自带 Skill 由系统管理，无法编辑或删除。'],
    ['ja', 'skill.builtin_read_only', 'Memoh 組み込みの Skill はシステムによって管理されているため、編集または削除できません。'],
    ['en', 'skill.name_taken', 'A Skill with this name already exists. Choose a different name.'],
    ['zh', 'skill.name_taken', '已存在同名 Skill，请换一个名称。'],
    ['ja', 'skill.name_taken', '同じ名前の Skill がすでに存在します。別の名前を使用してください。'],
    ['en', 'skill.save_failed', 'The Skill could not be saved. Please try again.'],
    ['zh', 'skill.save_failed', 'Skill 保存失败，请重试。'],
    ['ja', 'skill.save_failed', 'Skill を保存できませんでした。もう一度お試しください。'],
    ['en', 'registry.unavailable', 'The Supermarket is unavailable. Please try again later.'],
    ['zh', 'registry.unavailable', '暂时无法连接 Supermarket，请稍后重试。'],
    ['ja', 'registry.unavailable', 'Supermarket に接続できません。しばらくしてからもう一度お試しください。'],
    ['en', 'registry.app_not_found', 'This app is no longer available.'],
    ['zh', 'registry.app_not_found', '该应用已不存在。'],
    ['ja', 'registry.app_not_found', 'このアプリは現在利用できません。'],
    ['en', 'registry.app_invalid', 'This app is invalid and cannot be installed.'],
    ['zh', 'registry.app_invalid', '该应用无效，无法安装。'],
    ['ja', 'registry.app_invalid', 'このアプリは無効なため、インストールできません。'],
    ['en', 'registry.app_install_failed', 'The app could not be installed. Please try again.'],
    ['zh', 'registry.app_install_failed', '应用安装失败，请重试。'],
    ['ja', 'registry.app_install_failed', 'アプリをインストールできませんでした。もう一度お試しください。'],
  ])('localizes %s error %s', (language, code, expected) => {
    locale = language
    expect(resolveApiErrorMessage({ code, detail: 'backend fallback' }, 'fallback')).toBe(expected)
  })

  it.each([
    ['en', 'The workspace could not be reached.'],
    ['zh', '暂时无法连接工作区，请稍后重试。'],
    ['ja', 'Workspace に接続できません。しばらくしてからもう一度お試しください。'],
  ])('localizes workspace.unreachable for %s', (language, expected) => {
    locale = language

    expect(resolveApiErrorMessage({
      code: 'workspace.unreachable',
      args: {},
      detail: 'The workspace could not be reached.',
    }, 'fallback')).toBe(expected)
  })

  it.each([
    ['en', 'The channel configuration could not be verified. Check the credentials, then try again.'],
    ['zh', '无法验证平台配置，请检查凭据后重试。'],
    ['ja', 'プラットフォーム設定を検証できませんでした。認証情報を確認して、もう一度お試しください。'],
  ])('localizes channel.verification_failed for %s', (language, expected) => {
    locale = language

    expect(resolveApiErrorMessage({
      code: 'channel.verification_failed',
      args: {},
      detail: 'backend platform error',
    }, 'fallback')).toBe(expected)
  })

  it.each([
    ['context.budget_unsatisfied', 'en', 'The model context window is too small for this request. Shorten the request, or switch to a model with a larger context window.'],
    ['context.budget_unsatisfied', 'zh', '模型上下文窗口不足，无法处理当前请求。可尝试缩短请求，或改用上下文窗口更大的模型。'],
    ['context.budget_unsatisfied', 'ja', 'モデルのコンテキストウィンドウが不足しているため、このリクエストを処理できません。リクエストを短くするか、より大きなコンテキストウィンドウのモデルをお試しください。'],
    ['context.protected_overflow', 'en', 'Required context exceeds the model context budget. Switch to a model with a larger context window.'],
    ['context.protected_overflow', 'zh', '必要的上下文内容超出了模型上下文预算。可尝试改用上下文窗口更大的模型。'],
    ['context.protected_overflow', 'ja', '必須コンテキストがモデルのコンテキスト予算を超えています。より大きなコンテキストウィンドウのモデルをお試しください。'],
  ])('localizes %s for %s', (code, language, expected) => {
    locale = language

    expect(resolveApiErrorMessage({
      type: 'error',
      code,
      message: 'backend English fallback',
    }, 'fallback')).toBe(expected)
  })

  it.each([
    ['agent.response_timeout', 'en', 'The model did not respond in time. Please try again.'],
    ['agent.response_timeout', 'zh', '模型未能及时响应，请重试。'],
    ['agent.response_timeout', 'ja', 'モデルから時間内に応答がありませんでした。もう一度お試しください。'],
    ['agent.response_interrupted', 'en', 'The model response was interrupted. Please try again.'],
    ['agent.response_interrupted', 'zh', '模型响应意外中断，请重试。'],
    ['agent.response_interrupted', 'ja', 'モデルの応答が中断されました。もう一度お試しください。'],
    ['agent.provider_overloaded', 'en', 'The model provider is unavailable or overloaded right now. Please try again in a moment.'],
    ['agent.provider_overloaded', 'zh', '模型服务暂时不可用或过载，请稍后重试。'],
    ['agent.provider_overloaded', 'ja', 'モデルプロバイダーは現在利用できないか、過負荷の状態です。しばらくしてからもう一度お試しください。'],
    ['agent.provider_rate_limited', 'zh', '已达到模型服务的速率上限，请稍后再发送。'],
    ['agent.provider_quota_exhausted', 'en', 'The model provider account has no remaining balance or quota.'],
    ['agent.provider_quota_exhausted', 'zh', '模型服务账户的余额或配额已用尽。'],
    ['agent.provider_auth_failed', 'en', 'The model provider rejected the credentials. Check the provider API key.'],
    ['agent.provider_auth_failed', 'zh', '模型服务拒绝了当前凭据，请检查该服务商的 API Key。'],
    ['agent.provider_permission_denied', 'en', 'The model provider denied access to this model or resource. Check that the provider account can use this model.'],
    ['agent.provider_permission_denied', 'zh', '模型服务商拒绝访问该模型或资源，请确认该账号有权使用此模型。'],
    ['agent.provider_permission_denied', 'ja', 'モデルプロバイダーがこのモデルまたはリソースへのアクセスを拒否しました。プロバイダーのアカウントがこのモデルを利用できるか確認してください。'],
    ['agent.provider_request_rejected', 'en', 'The model provider rejected the request. Check the model settings, or try another model.'],
    ['agent.provider_request_rejected', 'zh', '模型服务商拒绝了这次请求，请检查模型设置，或换一个模型。'],
    ['agent.provider_request_rejected', 'ja', 'モデルプロバイダーがリクエストを拒否しました。モデル設定を確認するか、別のモデルをお試しください。'],
    ['agent.provider_unreachable', 'en', 'Memoh could not reach the model provider. Check the provider address and that the service is running.'],
    ['agent.provider_unreachable', 'zh', '无法连接到模型服务商，请检查服务地址是否正确、服务是否在运行。'],
    ['agent.provider_unreachable', 'ja', 'Memoh からモデルプロバイダーに接続できませんでした。プロバイダーのアドレスとサービスが稼働中か確認してください。'],
  ])('localizes structural stream failure %s for %s', (code, language, expected) => {
    locale = language

    expect(resolveApiErrorMessage({ code, detail: 'backend fallback' }, 'fallback')).toBe(expected)
  })

  it('keeps unknown codes as open strings and uses their safe fallback', () => {
    const error = {
      code: 'future.new_condition',
      args: {},
      detail: 'A future error occurred.',
    }

    expect(parseMemohError(error)?.code).toBe('future.new_condition')
    expect(resolveApiErrorMessage(error, 'fallback')).toBe('fallback')
  })

  it.each([
    ['client', 409, 'The request conflicts with the current state. Refresh and try again.'],
    ['client', 422, 'The request is invalid.'],
    ['server', 500, 'Something went wrong on the server. Please try again.'],
    ['dependency', 502, 'Something went wrong on the server. Please try again.'],
  ])('describes an unrecognized code with a %s fault and status %d by its fault', (fault, status, expected) => {
    const problem = { code: 'future.new_condition', status, fault, args: {}, detail: 'raw server detail' }

    expect(resolveApiErrorMessage(problem, 'fallback')).toBe(expected)
    expect(resolveApiErrorMessage(problem, 'Save failed', { prefixFallback: true })).toBe(`Save failed: ${expected}`)
  })

  it('shows nothing for an unrecognized code of a canceled request', () => {
    const problem = { code: 'future.new_condition', status: 499, fault: 'canceled', args: {}, detail: 'raw server detail' }

    expect(resolveApiErrorMessage(problem, 'fallback', { prefixFallback: true })).toBe('')
  })

  it('prefers the copy of a recognized code over its fault', () => {
    const problem = { code: 'bot.name_taken', status: 409, fault: 'client', args: {}, detail: 'raw server detail' }

    expect(resolveApiErrorMessage(problem, 'fallback')).toBe('This name is already taken.')
  })

  it('reads the fault and trace of a Problem', () => {
    expect(parseMemohError({ code: 'internal', status: 500, fault: 'server', trace_id: 'trace-1', request_id: 'req-1' })).toMatchObject({
      code: 'internal', status: 500, fault: 'server', traceId: 'trace-1', requestId: 'req-1',
    })
    expect(parseMemohError({ code: 'internal', fault: 'unheard-of' })?.fault).toBeUndefined()
  })

  it.each([
    ['a client rejection', { code: 'http.conflict', status: 409, fault: 'client' }, true],
    ['a server failure', { code: 'internal', status: 500, fault: 'server' }, true],
    ['a canceled request', { code: 'canceled', status: 499, fault: 'canceled' }, false],
    ['a network failure', new TypeError('Failed to fetch'), false],
  ])('tells whether the server answered %s', (_case, error, answered) => {
    expect(isApiErrorAnswered(error)).toBe(answered)
  })

  it('reads legacy HTTP status without parsing a message', () => {
    expect(apiErrorStatus({ response: { status: 409 }, message: 'legacy' })).toBe(409)
  })
})
